# Editorial regression checks; no fit or runtime evidence is required.
args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) args[[1L]] else "."
read_text <- function(path) paste(readLines(file.path(root, path), warn = FALSE), collapse = "\n")
bib <- read_text("refs.bib")
entry <- function(key) {
  blocks <- strsplit(bib, "\n(?=@)", perl = TRUE)[[1L]]
  selected <- blocks[grepl(paste0("^@[A-Za-z]+\\{", key, ","), blocks)]
  stopifnot(length(selected) == 1L)
  selected
}
has_field <- function(key, field, value) {
  pattern <- paste0("(?m)^\\s*", field, "\\s*=\\s*\\{([^}]*)\\}")
  found <- regmatches(entry(key), regexec(pattern, entry(key), perl = TRUE))[[1L]]
  stopifnot(length(found) == 2L, identical(found[[2L]], value))
}
has_field("NishimuraSuchard2023SSS", "doi", "10.1214/22-BA1308")
has_field("NishimuraSuchard2023SSS", "year", "2023")
has_field("NishimuraSuchard2023SSS", "volume", "18")
has_field("NishimuraSuchard2023SSS", "number", "2")
has_field("NishimuraSuchard2023SSS", "pages", "367--390")
has_field("yan2025new", "year", "2026")
has_field("yan2025new", "volume", "21")
has_field("yan2025new", "number", "3")
has_field("yan2025new", "pages", "1029--1057")
has_field("JiLeeRabeHesketh2025ValidSE", "year", "2026")
has_field("JiLeeRabeHesketh2025ValidSE", "volume", "51")
has_field("JiLeeRabeHesketh2025ValidSE", "number", "5")
has_field("JiLeeRabeHesketh2025ValidSE", "pages", "1055--1084")
has_field("wang2013nonconjugatevb", "title", "Variational Inference in Nonconjugate Models")
has_field("wang2013nonconjugatevb", "url", "https://jmlr.org/papers/volume14/wang13b/wang13b.pdf")
has_field("bhattacharya-khare-pal", "author", "Bhattacharya, Suman and Khare, Kshitij and Pal, Subhadip")
has_field("bhattacharya-khare-pal", "doi", "10.1214/21-EJS1932")
has_field("bhattacharya-khare-pal", "year", "2022")
has_field("bhattacharya-khare-pal", "volume", "16")
has_field("bhattacharya-khare-pal", "number", "1")
has_field("bhattacharya-khare-pal", "pages", "1--57")
has_field("WuNarisetty2021ScoreLikelihood", "author", "Wu, Teng and Narisetty, Naveen N.")
has_field("WuNarisetty2021ScoreLikelihood", "year", "2021")
has_field("WuNarisetty2021ScoreLikelihood", "volume", "16")
has_field("WuNarisetty2021ScoreLikelihood", "doi", "10.1214/20-BA1217")
has_field("WuNarisetty2021ScoreLikelihood", "number", "3")
has_field("WuNarisetty2021ScoreLikelihood", "pages", "875--903")
has_field("exdqlmRPackage", "author", "Raquel Barata and Antonio Aguirre")
has_field("exdqlmRPackage", "year", "2026")
stopifnot(grepl("package version 1.1.1", entry("exdqlmRPackage"), fixed = TRUE))
stopifnot(grepl("https://CRAN.R-project.org/package=exdqlm", entry("exdqlmRPackage"), fixed = TRUE))
caption <- read_text("figures/quantile_initialization/quantile_initialization_caption.tex")
picture <- read_text("figures/quantile_initialization/quantile_initialization_picture.tex")
alt <- read_text("figures/quantile_initialization/quantile_initialization_accessibility.txt")
stopifnot(grepl("PriceFM uses independent VB fits only", caption, fixed = TRUE))
stopifnot(grepl("both applications", caption, fixed = TRUE))
stopifnot(grepl("prior calibration", caption, fixed = TRUE))
stopifnot(grepl("MCMC (joint simulation)", picture, fixed = TRUE))
stopifnot(grepl("PriceFM: independent VB only", picture, fixed = TRUE))
stopifnot(grepl("development data only", picture, fixed = TRUE))
stopifnot(grepl("prior calibration", alt, fixed = TRUE))
stopifnot(grepl("separate procedure", caption, fixed = TRUE))
cat("PRO_REVIEW_BIBLIOGRAPHY_INITIALIZATION_PASS\n")
