#!/usr/bin/env Rscript
arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
root <- normalizePath(file.path(dirname(sub("^--file=", "", arg[[1]])), "..", ".."), mustWork = TRUE)
source(file.path(root, "application/R/glofas_search3_article_projection.R"))
stopifnot(identical(g3_tex_escape("search3_ref_001"), "search3\\_ref\\_001"))
dates <- as.character(as.Date("2022-12-26") + 0:1)
rows <- do.call(rbind, lapply(1:2, function(i) data.frame(target_date = dates[i], horizon = i, quantile_level = g3_tau, y_reference = 0, qhat = -3:3)))
m <- g3_metrics(rows)
stopifnot(m[["n_scored_horizons"]] == 2, m[["coverage90"]] == 1, m[["crossing_pairs"]] == 0)
loss <- ifelse(-rows$qhat >= 0, rows$quantile_level * -rows$qhat, (1 - rows$quantile_level) * rows$qhat)
stopifnot(isTRUE(all.equal(m[["mean_check_loss"]], mean(loss))))
stopifnot(isTRUE(all.equal(m[["crps_grid_log1p"]], .495)), m[["median_mae_log1p"]] == 0, m[["median_rmse_log1p"]] == 0)
bad <- rows; bad$qhat[2] <- -4
stopifnot(g3_metrics(bad)[["crossing_pairs"]] == 1)
bad <- rows[-1, ]; stopifnot(inherits(try(g3_metrics(bad), silent = TRUE), "try-error"))
tmp <- tempfile("glofas-precision-", fileext = ".csv")
values <- data.frame(x = c(pi, 5.2043087445082e-5, NA_real_), flag = c(TRUE, FALSE, TRUE))
g3_csv(values, tmp); stopifnot(identical(g3_read(tmp)$x, values$x)); unlink(tmp)
manifest <- file.path(root, g3_path("tables", "publication_manifest", "csv"))
if (file.exists(manifest)) g3_check(root)
cat("GLOFAS_SEARCH3_ARTICLE_PROJECTION_TEST_PASS\n")
