cfg <- app_read_config(app_path("application/config/glofas_discrepancy_application.yaml"))
schema <- app_read_yaml(app_config_path(cfg, "schema"))
stopifnot(!is.null(schema$inputs))
template <- app_read_csv(app_config_path(cfg, "input_manifest_template"))
stopifnot(identical(names(template), app_required_manifest_columns()))
stopifnot(nrow(template) >= 4L)
bundle_template <- app_read_csv(app_config_path(cfg, "input_bundle_manifest_template"))
stopifnot(all(c("bundle_id", "input_id", "local_path", "sha256", "required", "status") %in% names(bundle_template)))
stopifnot(nrow(bundle_template) >= 4L)
