#!/usr/bin/env Rscript

file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)[1]
repo_root <- if (!is.na(file_arg)) {
  script_path <- normalizePath(sub("^--file=", "", file_arg), mustWork = TRUE)
  normalizePath(file.path(dirname(script_path), "..", ".."), mustWork = TRUE)
} else {
  normalizePath(".", mustWork = TRUE)
}

source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/joint_qvp_qdesn.R"))

args <- app_parse_args(list(
  fixture_dir = "application/cache/joint_qdesn_simulation_dgp_fixtures_20260706",
  fit_dir = "application/cache/joint_qdesn_simulation_vb_fit_validation_article_20260706",
  forecast_dir = "application/cache/joint_qdesn_simulation_vb_forecast_validation_article_20260706",
  post_vb_audit_dir = "application/cache/joint_qdesn_simulation_post_vb_validation_audit_20260706",
  tail_diagnostic_dir = "application/cache/joint_qdesn_independent_exal_tail_failure_diagnostic_20260706",
  convergence_audit_dir = "application/cache/joint_qdesn_vb_convergence_readiness_20260706",
  tables_dir = "tables",
  figures_dir = "figures/joint_qdesn_simulation",
  output_dir = "application/cache/joint_qdesn_article_evidence_pack_phase105_20260706",
  include_independent_exal_main = "false"
))

arg_value <- function(name) {
  hyphen_name <- gsub("_", "-", name, fixed = TRUE)
  if (!is.null(args[[hyphen_name]])) return(args[[hyphen_name]])
  args[[name]]
}

resolve_repo_path <- function(path, must_work = FALSE) {
  path <- as.character(path)[[1L]]
  out <- if (grepl("^/", path)) path else app_path(path)
  normalizePath(out, winslash = "/", mustWork = must_work)
}

write_csv <- function(x, path) {
  app_ensure_dir(dirname(path))
  utils::write.csv(x, path, row.names = FALSE, na = "")
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

bind_rows <- function(rows) app_bind_rows_fill(rows)

latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

fmt_num <- function(x, digits = 3) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  if (abs(x) >= 1000) return(formatC(x, format = "f", digits = 1, big.mark = ","))
  if (abs(x) >= 100) return(formatC(x, format = "f", digits = 1))
  formatC(x, format = "f", digits = digits)
}

fmt_int <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  formatC(round(x), format = "d", big.mark = ",")
}

fmt_pair <- function(mae, rmse) sprintf("%s (%s)", fmt_num(mae, 3), fmt_num(rmse, 3))

article_model_label <- function(x) {
  x <- as.character(x)
  out <- ifelse(x == "JOINT QDESN RHS", "Joint QDESN RHS", x)
  out <- ifelse(out == "QDESN RHS", "Independent QDESN RHS", out)
  out <- ifelse(out == "JOINT exQDESN RHS", "Joint exQDESN RHS", out)
  out <- ifelse(out == "exQDESN RHS", "Independent exQDESN RHS", out)
  out
}

scenario_label <- function(x) {
  x <- gsub("_", " ", as.character(x), fixed = TRUE)
  x <- tools::toTitleCase(x)
  x <- ifelse(x == "Student t Location Scale", "Student-t Location-Scale", x)
  x
}

family_label <- function(x) {
  x <- gsub("_", " ", as.character(x), fixed = TRUE)
  x <- tools::toTitleCase(x)
  x <- ifelse(x == "Student T", "Student-t", x)
  x <- ifelse(x == "Student t", "Student-t", x)
  x
}

figure_model_label <- function(x) {
  gsub(" RHS$", "", article_model_label(x))
}

figure_scenario_label <- function(x) {
  out <- scenario_label(x)
  out <- ifelse(out == "Nonlinear Reservoir Friendly", "Nonlinear Reservoir", out)
  out <- ifelse(out == "Student T Location Scale", "Student-t Loc.-Scale", out)
  out <- ifelse(out == "Student t Location Scale", "Student-t Loc.-Scale", out)
  out <- ifelse(out == "Gaussian Mixture Bridge", "Gaussian-Mixture Bridge", out)
  out
}

write_latex_table <- function(x, path, caption, label, align = NULL, size = "\\small", resize = FALSE) {
  app_ensure_dir(dirname(path))
  if (is.null(align)) {
    align <- paste0("@{}", paste(ifelse(vapply(x, is.numeric, logical(1L)), "r", "l"), collapse = ""), "@{}")
  }
  body <- lapply(seq_len(nrow(x)), function(ii) {
    paste(latex_escape(unlist(x[ii, , drop = FALSE], use.names = FALSE)), collapse = " & ")
  })
  lines <- c(
    "% Generated by application/scripts/105_prepare_joint_qdesn_article_validation_tables_figures.R.",
    "\\begin{table}[!htbp]",
    "\\centering",
    size
  )
  if (isTRUE(resize)) {
    lines <- c(lines, "\\resizebox{\\textwidth}{!}{%")
  }
  lines <- c(
    lines,
    sprintf("\\begin{tabular}{%s}", align),
    "\\toprule",
    paste(latex_escape(names(x)), collapse = " & "),
    "\\\\",
    "\\midrule",
    paste0(body, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}"
  )
  if (isTRUE(resize)) {
    lines <- c(lines, "}%")
  }
  lines <- c(
    lines,
    sprintf("\\caption{%s}", caption),
    sprintf("\\label{%s}", label),
    "\\end{table}"
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

write_wrapper <- function(paths, path) {
  app_ensure_dir(dirname(path))
  rel <- vapply(paths, app_prefer_repo_relative_path, character(1L))
  lines <- c(
    "% Generated by application/scripts/105_prepare_joint_qdesn_article_validation_tables_figures.R.",
    "% Joint QDESN VB article evidence pack.",
    sprintf("\\input{%s}", rel)
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

verify_manifest <- function(dir, stage) {
  manifest_path <- file.path(dir, "artifact_manifest.csv")
  if (!file.exists(manifest_path)) {
    return(data.frame(
      stage = stage,
      label = "artifact_manifest",
      relative_path = "artifact_manifest.csv",
      path = manifest_path,
      exists = FALSE,
      declared_sha256 = NA_character_,
      actual_sha256 = NA_character_,
      declared_size_bytes = NA_real_,
      actual_size_bytes = NA_real_,
      status = "fail",
      stringsAsFactors = FALSE
    ))
  }
  manifest <- app_read_csv(manifest_path)
  app_check_required_columns(manifest, c("label", "relative_path", "size_bytes", "sha256"), sprintf("%s artifact manifest", stage))
  bind_rows(lapply(seq_len(nrow(manifest)), function(ii) {
    p <- file.path(dir, manifest$relative_path[[ii]])
    exists <- file.exists(p)
    actual_sha <- if (exists) app_sha256_file(p) else NA_character_
    actual_size <- if (exists) as.numeric(file.info(p)$size) else NA_real_
    data.frame(
      stage = stage,
      label = manifest$label[[ii]],
      relative_path = manifest$relative_path[[ii]],
      path = normalizePath(p, winslash = "/", mustWork = FALSE),
      exists = exists,
      declared_sha256 = manifest$sha256[[ii]],
      actual_sha256 = actual_sha,
      declared_size_bytes = as.numeric(manifest$size_bytes[[ii]]),
      actual_size_bytes = actual_size,
      status = if (exists && identical(tolower(actual_sha), tolower(manifest$sha256[[ii]]))) "pass" else "fail",
      stringsAsFactors = FALSE
    )
  }))
}

stop_if_any <- function(condition, message) {
  if (isTRUE(condition)) stop(message, call. = FALSE)
}

model_ids_main <- function(include_independent_exal) {
  ids <- c("joint_qdesn_rhs_vb", "qdesn_rhs_independent_vb", "joint_exqdesn_rhs_vb")
  if (isTRUE(include_independent_exal)) ids <- c(ids, "exqdesn_rhs_independent_vb")
  ids
}

make_model_summary <- function(model_metric, fit_assessment, forecast_assessment, include_independent_exal) {
  ids <- model_ids_main(include_independent_exal)
  fit_m <- model_metric[model_metric$stage == "fit" & model_metric$model_id %in% ids, , drop = FALSE]
  forecast_m <- model_metric[model_metric$stage == "forecast" & model_metric$model_id %in% ids, , drop = FALSE]
  by_model <- c("model_id", "display_label", "likelihood", "fit_structure")
  fit_sel <- fit_m[, c(by_model, "truth_mae", "truth_rmse", "check_loss_mean"), drop = FALSE]
  names(fit_sel)[names(fit_sel) %in% c("truth_mae", "truth_rmse", "check_loss_mean")] <- c("fit_truth_mae", "fit_truth_rmse", "fit_check_loss")
  fc_sel <- forecast_m[, c(by_model, "truth_mae", "truth_rmse", "check_loss_mean", "crps_grid_mean", "abs_hit_rate_error", "abs_coverage_error"), drop = FALSE]
  names(fc_sel)[names(fc_sel) %in% c("truth_mae", "truth_rmse", "check_loss_mean")] <- c("forecast_truth_mae", "forecast_truth_rmse", "forecast_check_loss")
  fta <- fit_assessment[fit_assessment$model_id %in% ids, , drop = FALSE]
  fca <- forecast_assessment[forecast_assessment$model_id %in% ids, , drop = FALSE]
  fit_a <- aggregate(cbind(raw_crossing_pairs, contract_crossing_pairs, reached_max_iter, elapsed_seconds) ~ model_id, fta, sum, na.rm = TRUE)
  names(fit_a)[-1L] <- paste0("fit_", names(fit_a)[-1L])
  forecast_a <- aggregate(cbind(raw_crossing_pairs, contract_crossing_pairs, reached_max_iter, elapsed_seconds) ~ model_id, fca, sum, na.rm = TRUE)
  names(forecast_a)[-1L] <- paste0("forecast_", names(forecast_a)[-1L])
  max_adj <- aggregate(max_abs_adjustment ~ model_id, fca, max, na.rm = TRUE)
  names(max_adj)[2L] <- "forecast_max_abs_adjustment"
  out <- merge(fit_sel, fc_sel, by = by_model, all = TRUE)
  out <- Reduce(function(a, b) merge(a, b, by = "model_id", all = TRUE), list(out, fit_a, forecast_a, max_adj))
  out$article_label <- article_model_label(out$display_label)
  out$article_role <- ifelse(out$model_id == "joint_qdesn_rhs_vb", "primary joint model",
    ifelse(out$model_id == "qdesn_rhs_independent_vb", "independent AL comparator",
      ifelse(out$model_id == "joint_exqdesn_rhs_vb", "joint exAL comparator", "diagnostic only")))
  out$main_table_included <- out$model_id %in% ids & out$model_id != "exqdesn_rhs_independent_vb"
  out[match(ids, out$model_id), , drop = FALSE]
}

make_model_table <- function(summary) {
  data.frame(
    Model = summary$article_label,
    Role = summary$article_role,
    `Fit MAE` = vapply(summary$fit_truth_mae, fmt_num, character(1L), digits = 3),
    `Forecast MAE` = vapply(summary$forecast_truth_mae, fmt_num, character(1L), digits = 3),
    `Forecast RMSE` = vapply(summary$forecast_truth_rmse, fmt_num, character(1L), digits = 3),
    `Check loss` = vapply(summary$forecast_check_loss, fmt_num, character(1L), digits = 3),
    `CRPS-grid` = vapply(summary$crps_grid_mean, fmt_num, character(1L), digits = 3),
    `Hit error` = vapply(summary$abs_hit_rate_error, fmt_num, character(1L), digits = 3),
    `Raw crossings` = vapply(summary$forecast_raw_crossing_pairs, fmt_int, character(1L)),
    `Runtime min.` = vapply(summary$forecast_elapsed_seconds / 60, fmt_num, character(1L), digits = 1),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

make_scenario_summary <- function(scenario_metric, scenario_summary, include_independent_exal) {
  ids <- model_ids_main(include_independent_exal)
  stable_ids <- setdiff(ids, "exqdesn_rhs_independent_vb")
  fc <- scenario_metric[scenario_metric$stage == "forecast" & scenario_metric$model_id %in% stable_ids, , drop = FALSE]
  scenarios <- scenario_summary$scenario_id
  rows <- lapply(scenarios, function(sc) {
    block <- fc[fc$scenario_id == sc, , drop = FALSE]
    vals <- setNames(rep("--", length(stable_ids)), stable_ids)
    for (id in stable_ids) {
      row <- block[block$model_id == id, , drop = FALSE]
      if (nrow(row)) vals[[id]] <- fmt_pair(row$truth_mae[[1L]], row$truth_rmse[[1L]])
    }
    best <- block$model_id[which.min(block$truth_mae)]
    data.frame(
      Scenario = scenario_label(sc),
      Family = family_label(scenario_summary$distribution_family[match(sc, scenario_summary$scenario_id)]),
      `Joint QDESN` = vals[["joint_qdesn_rhs_vb"]],
      `Independent QDESN` = vals[["qdesn_rhs_independent_vb"]],
      `Joint exQDESN` = vals[["joint_exqdesn_rhs_vb"]],
      `Best stable row` = article_model_label(block$display_label[block$model_id == best][[1L]]),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  bind_rows(rows)
}

make_convergence_adjustment_table <- function(model_summary, conv_gate, fit_assessment, forecast_assessment) {
  ids <- model_summary$model_id
  rows <- lapply(ids, function(id) {
    fta <- fit_assessment[fit_assessment$model_id == id, , drop = FALSE]
    fca <- forecast_assessment[forecast_assessment$model_id == id, , drop = FALSE]
    cg <- conv_gate[conv_gate$model_id == id, , drop = FALSE]
    gate <- if (!nrow(cg)) "not audited" else if (any(cg$gate_recommendation == "review")) "review" else "pass with note"
    data.frame(
      Model = article_model_label(fta$display_label[[1L]]),
      `Fit max-iter rows` = fmt_int(sum(fta$reached_max_iter, na.rm = TRUE)),
      `Forecast max-iter rows` = fmt_int(sum(fca$reached_max_iter, na.rm = TRUE)),
      `Forecast raw crossings` = fmt_int(sum(fca$raw_crossing_pairs, na.rm = TRUE)),
      `Contract crossings` = fmt_int(sum(fca$contract_crossing_pairs, na.rm = TRUE)),
      `Max adjustment` = fmt_num(max(fca$max_abs_adjustment, na.rm = TRUE), 3),
      `Convergence audit` = gate,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  bind_rows(rows)
}

make_exal_diagnostic_table <- function(tail_dir) {
  assess <- app_read_csv(file.path(tail_dir, "exal_failure_assessment.csv"))
  raw <- app_read_csv(file.path(tail_dir, "raw_contract_quantile_summary.csv"))
  ags <- app_read_csv(file.path(tail_dir, "alpha_gamma_sigma_path_summary.csv"))
  tau075 <- raw[raw$likelihood == "exal" & abs(raw$tau - 0.75) < 1.0e-12, , drop = FALSE]
  ags075 <- ags[ags$likelihood == "exal" & abs(ags$tau - 0.75) < 1.0e-12 & ags$diagnostic_scope == "current_grid_reproduction", , drop = FALSE]
  data.frame(
    Diagnostic = "Independent exQDESN RHS held out",
    Scenario = scenario_label(assess$scenario_id[[1L]]),
    Tau = fmt_num(assess$primary_tau[[1L]], 2),
    Status = gsub("_", " ", assess$status[[1L]], fixed = TRUE),
    `Raw MAE` = if (nrow(tau075)) fmt_num(tau075$raw_truth_mae[[1L]], 1) else "--",
    `Contract MAE` = if (nrow(tau075)) fmt_num(tau075$contract_truth_mae[[1L]], 1) else "--",
    `alpha mean` = if (nrow(ags075)) fmt_num(ags075$alpha_mean[[1L]], 1) else "--",
    `sigma mean` = if (nrow(ags075)) fmt_num(ags075$sigma_mean[[1L]], 4) else "--",
    Treatment = "excluded from main table",
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

make_protocol_table <- function(fixture_dir, fit_dir, forecast_dir, model_summary) {
  scenario <- app_read_csv(file.path(fixture_dir, "scenario_summary.csv"))
  split <- app_read_csv(file.path(fixture_dir, "split_metadata.csv"))
  origins <- app_read_csv(file.path(fixture_dir, "forecast_origin_plan.csv"))
  fit_cfg <- app_read_csv(file.path(fit_dir, "run_config.csv"))
  fc_cfg <- app_read_csv(file.path(forecast_dir, "run_config.csv"))
  classes <- paste(sprintf("%s (%d)", names(table(scenario$scenario_class)), as.integer(table(scenario$scenario_class))), collapse = "; ")
  data.frame(
    Item = c(
      "Synthetic scenarios",
      "Scenario classes",
      "Tau grid",
      "Source geometry",
      "Analysis split",
      "Forecast protocol",
      "VB controls",
      "Reported model rows",
      "Held-out diagnostic row",
      "Scoring and diagnostics"
    ),
    Value = c(
      sprintf("%d bridge and stress DGPs", nrow(scenario)),
      classes,
      gsub(",", ", ", scenario$tau_grid[[1L]], fixed = TRUE),
      sprintf("%d simulated rows; %d DGP warmup rows; %d effective rows", split$simulated_length[[1L]], split$dgp_warmup_length[[1L]], split$effective_length[[1L]]),
      sprintf("%d DESN washout, %d fit, %d validation rows", split$desn_washout_length[[1L]], split$fit_length[[1L]], split$validation_length[[1L]]),
      sprintf("%d no-refit origin blocks, leads %d--%d, stride %d", nrow(origins), min(origins$lead_start), max(origins$lead_end), origins$origin_stride[[1L]]),
      sprintf("VB max iter %s with adaptive grid %s; RHS tau0 = %s", fit_cfg$vb_max_iter[[1L]], fit_cfg$adaptive_vb_max_iter_grid[[1L]], fit_cfg$tau0[[1L]]),
      paste(model_summary$article_label[model_summary$main_table_included], collapse = "; "),
      "Independent exQDESN RHS, due to localized K=1 exAL instability",
      "Truth MAE/RMSE, check loss, CRPS-grid, hit-rate error, interval diagnostics, raw and contract crossing diagnostics"
    ),
    stringsAsFactors = FALSE
  )
}

pdf_plot <- function(path, width = 7.2, height = 4.8, expr) {
  app_ensure_dir(dirname(path))
  grDevices::pdf(path, width = width, height = height, useDingbats = FALSE)
  on.exit(grDevices::dev.off(), add = TRUE)
  force(expr)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

make_heatmap <- function(path, data, value_col, title, legend_label) {
  dat <- data
  scen <- unique(dat$Scenario)
  mods <- unique(dat$Model)
  mat <- matrix(NA_real_, nrow = length(scen), ncol = length(mods), dimnames = list(scen, mods))
  for (ii in seq_len(nrow(dat))) mat[dat$Scenario[[ii]], dat$Model[[ii]]] <- dat[[value_col]][[ii]]
  pdf_plot(path, width = 7.8, height = 6.3, {
    graphics::par(mar = c(8.4, 9.2, 3.2, 4.6))
    z <- mat[nrow(mat):1, , drop = FALSE]
    pal <- grDevices::hcl.colors(80, "Blues 3", rev = FALSE)
    graphics::image(seq_len(ncol(z)), seq_len(nrow(z)), t(z), col = pal, axes = FALSE, xlab = "", ylab = "", main = title)
    graphics::axis(1, at = seq_len(ncol(z)), labels = colnames(z), las = 2, cex.axis = 0.76)
    graphics::axis(2, at = seq_len(nrow(z)), labels = rownames(z), las = 1, cex.axis = 0.80)
    for (i in seq_len(nrow(z))) {
      for (j in seq_len(ncol(z))) {
        graphics::text(j, i, fmt_num(z[i, j], 3), cex = 0.78, col = ifelse(z[i, j] > stats::quantile(z, 0.78, na.rm = TRUE), "white", "black"))
      }
    }
    graphics::box()
    graphics::mtext(legend_label, side = 4, line = 3.2, cex = 0.85)
  })
}

plot_truth_by_tau <- function(path, truth_distance, stable_ids) {
  dat <- truth_distance[truth_distance$model_id %in% stable_ids, , drop = FALSE]
  agg <- aggregate(truth_mae ~ tau + display_label, dat, mean, na.rm = TRUE)
  agg$Model <- article_model_label(agg$display_label)
  mods <- unique(agg$Model)
  cols <- c("#0072B2", "#009E73", "#D55E00", "#CC79A7")[seq_along(mods)]
  pdf_plot(path, width = 6.9, height = 4.7, {
    graphics::par(mar = c(4.7, 4.7, 2.8, 1.1))
    yr <- range(agg$truth_mae, finite = TRUE)
    graphics::plot(range(agg$tau), yr * c(0.90, 1.10), type = "n", xlab = "Target quantile level", ylab = "Forecast MAE to true quantile", main = "Forecast truth error by quantile")
    graphics::grid(col = "grey88")
    for (kk in seq_along(mods)) {
      block <- agg[agg$Model == mods[[kk]], , drop = FALSE]
      block <- block[order(block$tau), , drop = FALSE]
      graphics::lines(block$tau, block$truth_mae, type = "b", pch = 15 + kk, lwd = 2, col = cols[[kk]])
    }
    graphics::legend("topleft", legend = mods, col = cols, pch = 16 + seq_along(mods), lwd = 2, bty = "n", cex = 0.82)
  })
}

plot_raw_adjustment <- function(path, forecast_assessment) {
  rows <- forecast_assessment
  rows$Model <- article_model_label(rows$display_label)
  raw <- aggregate(raw_crossing_pairs ~ Model, rows, sum, na.rm = TRUE)
  adj <- aggregate(max_abs_adjustment ~ Model, rows, max, na.rm = TRUE)
  dat <- merge(raw, adj, by = "Model", all = TRUE)
  dat <- dat[order(dat$raw_crossing_pairs), , drop = FALSE]
  pdf_plot(path, width = 7.2, height = 4.8, {
    graphics::par(mfrow = c(1, 2), mar = c(8.3, 4.5, 2.9, 0.9))
    graphics::barplot(dat$raw_crossing_pairs, names.arg = dat$Model, las = 2, col = "#56B4E9", border = NA, ylab = "Raw crossing pairs", main = "Raw crossings")
    graphics::grid(nx = NA, ny = NULL, col = "grey88")
    graphics::barplot(log10(1 + dat$max_abs_adjustment), names.arg = dat$Model, las = 2, col = "#E69F00", border = NA, ylab = "log10(1 + max adjustment)", main = "Monotone adjustment")
    graphics::grid(nx = NA, ny = NULL, col = "grey88")
  })
}

plot_overlay <- function(path, forecast_truth, scenario_id) {
  dat <- forecast_truth[forecast_truth$scenario_id == scenario_id & forecast_truth$model_id == "joint_qdesn_rhs_vb", , drop = FALSE]
  keep_tau <- c(0.05, 0.50, 0.95)
  dat <- dat[dat$tau %in% keep_tau, , drop = FALSE]
  agg <- aggregate(cbind(y, true_quantile, qhat) ~ effective_index + tau, dat, mean, na.rm = TRUE)
  obs <- aggregate(y ~ effective_index, agg, mean, na.rm = TRUE)
  taus <- sort(unique(agg$tau))
  cols <- c("#0072B2", "#000000", "#D55E00")[seq_along(taus)]
  pdf_plot(path, width = 7.4, height = 4.8, {
    graphics::par(mar = c(4.5, 4.8, 3.0, 1.0))
    yr <- range(c(obs$y, agg$true_quantile, agg$qhat), finite = TRUE)
    graphics::plot(obs$effective_index, obs$y, pch = 16, cex = 0.35, col = grDevices::adjustcolor("grey35", 0.45),
      ylim = yr, xlab = "Effective time index", ylab = "Observed value and quantile", main = scenario_label(scenario_id))
    graphics::grid(col = "grey88")
    for (kk in seq_along(taus)) {
      block <- agg[abs(agg$tau - taus[[kk]]) < 1e-12, , drop = FALSE]
      block <- block[order(block$effective_index), , drop = FALSE]
      graphics::lines(block$effective_index, block$true_quantile, col = cols[[kk]], lwd = 2.1, lty = 2)
      graphics::lines(block$effective_index, block$qhat, col = cols[[kk]], lwd = 1.7)
    }
    graphics::legend("topleft",
      legend = c("observed y", paste0("true tau=", taus), paste0("fitted tau=", taus)),
      col = c("grey35", cols, cols), pch = c(16, rep(NA, 2 * length(taus))),
      lty = c(NA, rep(2, length(taus)), rep(1, length(taus))),
      lwd = c(NA, rep(2.1, length(taus)), rep(1.7, length(taus))),
      bty = "n", cex = 0.72
    )
  })
}

fixture_dir <- resolve_repo_path(arg_value("fixture_dir"), must_work = TRUE)
fit_dir <- resolve_repo_path(arg_value("fit_dir"), must_work = TRUE)
forecast_dir <- resolve_repo_path(arg_value("forecast_dir"), must_work = TRUE)
post_vb_audit_dir <- resolve_repo_path(arg_value("post_vb_audit_dir"), must_work = TRUE)
tail_diagnostic_dir <- resolve_repo_path(arg_value("tail_diagnostic_dir"), must_work = TRUE)
convergence_audit_dir <- resolve_repo_path(arg_value("convergence_audit_dir"), must_work = TRUE)
tables_dir <- resolve_repo_path(arg_value("tables_dir"), must_work = TRUE)
figures_dir <- resolve_repo_path(arg_value("figures_dir"), must_work = FALSE)
out_dir <- resolve_repo_path(arg_value("output_dir"), must_work = FALSE)
include_independent_exal <- app_as_bool(arg_value("include_independent_exal_main"))

app_ensure_dir(figures_dir)
app_ensure_dir(out_dir)

source_manifest_verification <- bind_rows(list(
  verify_manifest(fixture_dir, "fixture"),
  verify_manifest(fit_dir, "fit_validation"),
  verify_manifest(forecast_dir, "forecast_validation"),
  verify_manifest(post_vb_audit_dir, "post_vb_audit"),
  verify_manifest(tail_diagnostic_dir, "tail_diagnostic"),
  verify_manifest(convergence_audit_dir, "convergence_audit")
))
stop_if_any(any(source_manifest_verification$status != "pass"), "At least one source manifest hash check failed.")

fixture_validation <- app_read_csv(file.path(fixture_dir, "fixture_validation.csv"))
stop_if_any(!nrow(fixture_validation) || any(fixture_validation$status != "pass"), "Fixture validation is missing or contains non-pass rows.")

fit_assessment <- app_read_csv(file.path(fit_dir, "fit_validation_assessment.csv"))
forecast_assessment <- app_read_csv(file.path(forecast_dir, "forecast_validation_assessment.csv"))
for (tbl in list(fit_assessment, forecast_assessment)) {
  stop_if_any(any(tbl$gate_status == "fail"), "Source assessment contains fail rows.")
  stop_if_any(any(!tbl$finite_quantiles | !tbl$finite_scores), "Source assessment contains nonfinite quantiles or scores.")
  stop_if_any(sum(tbl$contract_crossing_pairs, na.rm = TRUE) != 0, "Source assessment contains contract quantile crossings.")
}

scenario_summary <- app_read_csv(file.path(fixture_dir, "scenario_summary.csv"))
model_metric <- app_read_csv(file.path(post_vb_audit_dir, "model_metric_summary.csv"))
scenario_metric <- app_read_csv(file.path(post_vb_audit_dir, "scenario_metric_summary.csv"))
conv_gate <- app_read_csv(file.path(convergence_audit_dir, "convergence_gate_recommendation.csv"))
truth_distance <- app_read_csv(file.path(forecast_dir, "truth_distance_summary.csv"))
forecast_truth <- app_read_csv(file.path(forecast_dir, "forecast_truth_comparison.csv"))

model_summary <- make_model_summary(model_metric, fit_assessment, forecast_assessment, include_independent_exal)
main_model_summary <- model_summary[model_summary$main_table_included, , drop = FALSE]
stop_if_any(any(main_model_summary$model_id == "exqdesn_rhs_independent_vb"), "Independent exQDESN RHS entered the main table unexpectedly.")

protocol_table <- make_protocol_table(fixture_dir, fit_dir, forecast_dir, model_summary)
model_table <- make_model_table(main_model_summary)
scenario_table <- make_scenario_summary(scenario_metric, scenario_summary, include_independent_exal)
convergence_adjustment_table <- make_convergence_adjustment_table(main_model_summary, conv_gate, fit_assessment, forecast_assessment)
exal_diagnostic_table <- make_exal_diagnostic_table(tail_diagnostic_dir)

stable_ids <- main_model_summary$model_id
forecast_scenario_plot <- scenario_metric[scenario_metric$stage == "forecast" & scenario_metric$model_id %in% stable_ids, , drop = FALSE]
forecast_scenario_plot$Scenario <- figure_scenario_label(forecast_scenario_plot$scenario_id)
forecast_scenario_plot$Model <- figure_model_label(forecast_scenario_plot$display_label)

table_paths <- c(
  protocol_csv = write_csv(protocol_table, file.path(tables_dir, "joint_qdesn_simulation_vb_protocol.csv")),
  protocol_tex = write_latex_table(protocol_table, file.path(tables_dir, "joint_qdesn_simulation_vb_protocol.tex"),
    "Protocol for the joint multi-quantile QDESN synthetic validation. All reported rows use the same frozen DGP fixtures, oracle quantiles, fit window, validation origins, and scoring rules.",
    "tab:joint-qdesn-vb-protocol",
    align = "@{}>{\\raggedright\\arraybackslash}p{0.28\\textwidth}>{\\raggedright\\arraybackslash}p{0.62\\textwidth}@{}"
  ),
  model_summary_csv = write_csv(main_model_summary, file.path(tables_dir, "joint_qdesn_simulation_vb_model_summary.csv")),
  model_summary_tex = write_latex_table(model_table, file.path(tables_dir, "joint_qdesn_simulation_vb_model_summary.tex"),
    "Fit and held-out forecast summaries for the reported joint multi-quantile QDESN validation rows. Independent exQDESN RHS is excluded from this main comparison because a targeted diagnostic found a localized single-quantile exAL instability.",
    "tab:joint-qdesn-vb-model-summary",
    align = "@{}>{\\raggedright\\arraybackslash}p{0.18\\textwidth}>{\\raggedright\\arraybackslash}p{0.18\\textwidth}rrrrrrrr@{}",
    size = "\\scriptsize",
    resize = TRUE
  ),
  scenario_summary_csv = write_csv(scenario_table, file.path(tables_dir, "joint_qdesn_simulation_vb_scenario_summary.csv")),
  scenario_summary_tex = write_latex_table(scenario_table, file.path(tables_dir, "joint_qdesn_simulation_vb_scenario_summary.tex"),
    "Forecast distance to true conditional quantiles by synthetic scenario. Entries report MAE with RMSE in parentheses.",
    "tab:joint-qdesn-vb-scenario-summary",
    align = "@{}>{\\raggedright\\arraybackslash}p{0.24\\textwidth}>{\\raggedright\\arraybackslash}p{0.14\\textwidth}rrrr@{}",
    size = "\\scriptsize",
    resize = TRUE
  ),
  convergence_adjustment_csv = write_csv(convergence_adjustment_table, file.path(tables_dir, "joint_qdesn_simulation_vb_convergence_adjustment_summary.csv")),
  convergence_adjustment_tex = write_latex_table(convergence_adjustment_table, file.path(tables_dir, "joint_qdesn_simulation_vb_convergence_adjustment_summary.tex"),
    "Convergence and raw monotonicity diagnostics for the reported rows. Scored quantiles satisfy the monotone output contract; raw crossings remain visible as diagnostics.",
    "tab:joint-qdesn-vb-convergence-adjustment",
    align = "@{}>{\\raggedright\\arraybackslash}p{0.22\\textwidth}rrrrrr@{}",
    size = "\\scriptsize",
    resize = TRUE
  ),
  exal_diagnostic_csv = write_csv(exal_diagnostic_table, file.path(tables_dir, "joint_qdesn_simulation_vb_exal_diagnostic_summary.csv")),
  exal_diagnostic_tex = write_latex_table(exal_diagnostic_table, file.path(tables_dir, "joint_qdesn_simulation_vb_exal_diagnostic_summary.tex"),
    "Diagnostic reason for holding independent exQDESN RHS out of the main article table.",
    "tab:joint-qdesn-vb-exal-diagnostic",
    align = "@{}>{\\raggedright\\arraybackslash}p{0.21\\textwidth}>{\\raggedright\\arraybackslash}p{0.16\\textwidth}rrrrrr>{\\raggedright\\arraybackslash}p{0.18\\textwidth}@{}",
    size = "\\scriptsize",
    resize = TRUE
  )
)
table_paths[["article_wrapper"]] <- write_wrapper(
  table_paths[c("protocol_tex", "model_summary_tex", "scenario_summary_tex", "convergence_adjustment_tex", "exal_diagnostic_tex")],
  file.path(tables_dir, "joint_qdesn_simulation_vb_article_tables.tex")
)

figure_paths <- c(
  forecast_truth_mae_heatmap = make_heatmap(file.path(figures_dir, "joint_qdesn_simulation_forecast_truth_mae_heatmap.pdf"),
    forecast_scenario_plot, "truth_mae", "Forecast truth MAE by scenario and model", "Mean absolute error"),
  check_loss_heatmap = make_heatmap(file.path(figures_dir, "joint_qdesn_simulation_check_loss_heatmap.pdf"),
    forecast_scenario_plot, "check_loss_mean", "Forecast check loss by scenario and model", "Check loss"),
  truth_by_tau = plot_truth_by_tau(file.path(figures_dir, "joint_qdesn_simulation_truth_by_tau.pdf"), truth_distance, stable_ids),
  raw_adjustment_diagnostics = plot_raw_adjustment(file.path(figures_dir, "joint_qdesn_simulation_raw_adjustment_diagnostics.pdf"), forecast_assessment),
  overlay_normal_bridge = plot_overlay(file.path(figures_dir, "joint_qdesn_simulation_overlay_normal_bridge.pdf"), forecast_truth, "normal_bridge"),
  overlay_asymmetric_laplace_tail = plot_overlay(file.path(figures_dir, "joint_qdesn_simulation_overlay_asymmetric_laplace_tail.pdf"), forecast_truth, "asymmetric_laplace_tail"),
  overlay_regime_shift = plot_overlay(file.path(figures_dir, "joint_qdesn_simulation_overlay_regime_shift.pdf"), forecast_truth, "regime_shift")
)

asset_paths <- c(table_paths, figure_paths)
asset_manifest <- data.frame(
  label = names(asset_paths),
  artifact_type = ifelse(grepl("\\.pdf$", asset_paths), "figure", ifelse(grepl("\\.tex$", asset_paths), "latex_table", "csv_table")),
  path = vapply(asset_paths, app_prefer_repo_relative_path, character(1L)),
  size_bytes = as.numeric(file.info(asset_paths)$size),
  sha256 = vapply(asset_paths, app_sha256_file, character(1L)),
  source_fit_dir = app_prefer_repo_relative_path(fit_dir),
  source_forecast_dir = app_prefer_repo_relative_path(forecast_dir),
  stringsAsFactors = FALSE
)
asset_manifest_path <- write_csv(asset_manifest, file.path(tables_dir, "joint_qdesn_simulation_vb_asset_manifest.csv"))
asset_paths[["asset_manifest"]] <- asset_manifest_path

source_health <- data.frame(
  check = c("source_manifest_hashes", "fixture_validation", "assessment_fail_rows", "contract_crossings", "main_model_policy"),
  status = c(
    "pass",
    "pass",
    "pass",
    "pass",
    ifelse(any(main_model_summary$model_id == "exqdesn_rhs_independent_vb"), "fail", "pass")
  ),
  detail = c(
    sprintf("%d source files verified across %d source manifests", nrow(source_manifest_verification), length(unique(source_manifest_verification$stage))),
    sprintf("%d fixture validation rows pass", nrow(fixture_validation)),
    "fit and forecast assessments contain no fail rows",
    "fit and forecast contract crossing counts are zero",
    "independent exQDESN RHS is excluded from the main table by default"
  ),
  stringsAsFactors = FALSE
)

run_config <- data.frame(
  run_id = "joint_qdesn_article_evidence_pack_phase105",
  fixture_dir = fixture_dir,
  fit_dir = fit_dir,
  forecast_dir = forecast_dir,
  post_vb_audit_dir = post_vb_audit_dir,
  tail_diagnostic_dir = tail_diagnostic_dir,
  convergence_audit_dir = convergence_audit_dir,
  tables_dir = tables_dir,
  figures_dir = figures_dir,
  output_dir = out_dir,
  include_independent_exal_main = include_independent_exal,
  n_article_assets = length(asset_paths),
  stringsAsFactors = FALSE
)

readme_path <- file.path(out_dir, "README.md")
writeLines(c(
  "# Joint QDESN Article Evidence Pack",
  "",
  "This directory records verification artifacts for the generated manuscript tables and figures.",
  "",
  "Main policy:",
  "",
  "- Main rows: Joint QDESN RHS, Independent QDESN RHS, Joint exQDESN RHS.",
  "- Independent exQDESN RHS is excluded from the main table by default because the targeted diagnostic confirmed a localized asymmetric-tail failure.",
  "- No model fitting or fixture regeneration is performed by this stage.",
  "",
  "Generated article assets are listed in `tables/joint_qdesn_simulation_vb_asset_manifest.csv`."
), readme_path, useBytes = TRUE)

cache_paths <- c(
  run_config = write_csv(run_config, file.path(out_dir, "run_config.csv")),
  source_manifest_verification = write_csv(source_manifest_verification, file.path(out_dir, "source_manifest_verification.csv")),
  source_health = write_csv(source_health, file.path(out_dir, "source_health.csv")),
  article_asset_manifest = write_csv(asset_manifest, file.path(out_dir, "article_asset_manifest.csv")),
  provenance = write_csv(app_joint_qvp_provenance_rows(), file.path(out_dir, "provenance.csv")),
  readme = normalizePath(readme_path, winslash = "/", mustWork = TRUE)
)
artifact_manifest <- data.frame(
  label = names(cache_paths),
  relative_path = basename(cache_paths),
  size_bytes = as.numeric(file.info(cache_paths)$size),
  sha256 = vapply(cache_paths, app_sha256_file, character(1L)),
  stringsAsFactors = FALSE
)
artifact_manifest_path <- write_csv(artifact_manifest, file.path(out_dir, "artifact_manifest.csv"))

cat(sprintf("Joint QDESN article evidence pack assets written under %s and %s\n", tables_dir, figures_dir))
cat(sprintf("Cache verification directory: %s\n", out_dir))
cat(sprintf("Article asset manifest: %s\n", asset_manifest_path))
cat("Main article rows:\n")
print(model_table[, c("Model", "Role", "Forecast MAE", "Check loss", "CRPS-grid")], row.names = FALSE)
