#!/usr/bin/env Rscript
# Purpose: prepare reproducible per-quantile GloFAS Q-DESN launch configs.
# This script does not launch fits. It writes ignored runtime configs,
# manifests, and a tmux launcher for explicit human-confirmed execution.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/model_contract.R"))

args <- app_parse_args(list(
  base_config = "tables/glofas_application_run_config__glofas_optconfirm_engine73c_memrefine16_11_d1n300_m360_a92_r95_w018_bt1em01_at3em02_skip_maxiter200_20260602.yaml",
  quantile_targets = "application/config/glofas_quantile_targets_dec25_synthesis_20260603.csv",
  out_dir = "local_trackers/runtime_configs/glofas_multiquantile_dec25_20260603",
  batch_id = "glofas_multiquantile_dec25_20260603",
  first_core = 48
))

repo_rel <- function(path) {
  app_prefer_repo_relative_path(path)
}

copy_without_runtime_fields <- function(cfg) {
  cfg$.__config_path__ <- NULL
  cfg
}

as_scalar_bool <- function(x) {
  if (is.logical(x)) return(x[[1L]])
  tolower(as.character(x)[[1L]]) %in% c("true", "t", "yes", "y", "1")
}

q_label <- function(qid) {
  gsub("[^A-Za-z0-9]+", "", as.character(qid))
}

fit_suffix <- "d1n300_m360_a92_r95_w018_bt1em01_at3em02_skip_engine73c_multiquantile"
raw_model_id <- paste0("raw_glofas_latent_path_", fit_suffix)
qdesn_model_id <- paste0("qdesn_latent_path_rhs_al_vb_", fit_suffix)

base_config_path <- app_path(args$base_config)
target_path <- app_path(args$quantile_targets)
out_dir <- app_path(args$out_dir)
app_ensure_dir(out_dir)

base_cfg <- app_read_config(base_config_path)
base_cfg <- copy_without_runtime_fields(base_cfg)
targets <- app_validate_quantile_grid(target_path)
base_grid <- app_validate_model_grid(app_config_path(base_cfg, "model_grid"), app_config_path(base_cfg, "schema"))
raw_base <- base_grid[base_grid$model_family == "raw_glofas", , drop = FALSE][1L, , drop = FALSE]
qdesn_base <- base_grid[base_grid$model_family == "qdesn_glofas_discrepancy", , drop = FALSE][1L, , drop = FALSE]
if (!nrow(raw_base) || !nrow(qdesn_base)) {
  stop("Base model grid must contain one raw_glofas row and one qdesn_glofas_discrepancy row.", call. = FALSE)
}

intervals <- list(
  list(lower = 0.05, upper = 0.95, nominal = 0.90),
  list(lower = 0.15, upper = 0.80, nominal = 0.65),
  list(lower = 0.35, upper = 0.65, nominal = 0.30)
)

manifest_rows <- vector("list", nrow(targets))
all_qgrid <- targets
all_model_rows <- vector("list", nrow(targets))
shell_lines <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "export NUMEXPR_NUM_THREADS=1",
  "",
  "# This file is generated by application/scripts/10_prepare_glofas_multiquantile_launch.R.",
  "# It launches one single-quantile run per tmux session. Review launch_manifest.csv first.",
  ""
)

for (i in seq_len(nrow(targets))) {
  qid <- q_label(targets$quantile_id[[i]])
  qlev <- as.numeric(targets$quantile_level[[i]])
  role <- as.character(targets$role[[i]])
  run_id <- sprintf("%s_%s", args$batch_id, qid)
  qgrid_path <- file.path(out_dir, sprintf("quantile_grid_%s.csv", qid))
  model_grid_path <- file.path(out_dir, sprintf("model_grid_%s.csv", qid))
  config_path <- file.path(out_dir, sprintf("config_%s.yaml", qid))
  core <- as.integer(args$first_core) + i - 1L

  qgrid <- targets[i, , drop = FALSE]
  app_write_csv(qgrid, qgrid_path)

  raw_row <- raw_base
  qdesn_row <- qdesn_base
  raw_row$fit_id <- sprintf("raw_glofas_latent_path_%s_%s", fit_suffix, qid)
  raw_row$model_id <- raw_model_id
  raw_row$quantile_level <- qlev
  raw_row$config_hash <- "TO_BE_COMPUTED"
  raw_row$notes <- sprintf(
    "Raw GloFAS quantile baseline for the multi-quantile synthesis launch; quantile=%s (%s).",
    format(qlev, trim = TRUE),
    role
  )
  qdesn_row$fit_id <- sprintf("qdesn_latent_path_rhs_al_vb_%s_%s", fit_suffix, qid)
  qdesn_row$model_id <- qdesn_model_id
  qdesn_row$quantile_level <- qlev
  qdesn_row$reservoir_seed <- app_config_reservoir_seed(base_cfg)
  qdesn_row$config_hash <- "TO_BE_COMPUTED"
  qdesn_row$notes <- sprintf(
    "Q-DESN discrepancy fit for the multi-quantile synthesis launch; quantile=%s (%s), shared model_id across quantile-specific fits for post-hoc synthesis.",
    format(qlev, trim = TRUE),
    role
  )
  model_grid <- rbind(raw_row, qdesn_row)
  app_write_csv(model_grid, model_grid_path)
  all_model_rows[[i]] <- model_grid

  cfg <- base_cfg
  cfg$application_name <- run_id
  cfg$description <- paste(
    "Single-quantile component of the GloFAS multi-quantile Q-DESN synthesis launch.",
    sprintf("Quantile %s (%s). Scientific reservoir/prior specification matches the promoted optimized winner.", format(qlev, trim = TRUE), role)
  )
  cfg$paths$quantile_grid <- repo_rel(qgrid_path)
  cfg$paths$model_grid <- repo_rel(model_grid_path)
  cfg$paths$cache <- file.path("application/cache", run_id)
  cfg$scoring$intervals <- intervals
  cfg$inference$vb_ld$max_iter <- 150L
  cfg$inference$vb_ld$max_iter_hard_cap <- 150L
  cfg$inference$vb_ld$diagnostics$profile_substeps <- FALSE
  cfg$execution$final_launch$enabled <- TRUE
  cfg$execution$final_launch$note <- paste(
    "Single-quantile component of the user-approved multi-quantile synthesis plan.",
    "Do not promote this run alone as the article-facing distributional result;",
    "combine all target quantiles with application/scripts/10_synthesize_glofas_quantile_runs.R after all component fits complete."
  )
  cfg$post_analysis$run_after_outputs <- FALSE
  app_write_yaml(cfg, config_path)

  manifest_rows[[i]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    core = core,
    raw_fit_id = raw_row$fit_id,
    qdesn_fit_id = qdesn_row$fit_id,
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    launch_status = "prepared_not_launched",
    stringsAsFactors = FALSE
  )

  session <- sprintf("%s_%s", args$batch_id, qid)
  log_path <- file.path("application/logs", sprintf("%s.log", run_id))
  shell_lines <- c(
    shell_lines,
    sprintf("tmux new-session -d -s %s %s",
      shQuote(session),
      shQuote(sprintf(
        "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
        core,
        repo_rel(config_path),
        run_id,
        log_path
      ))
    )
  )
}

launch_manifest <- do.call(rbind, manifest_rows)
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
source_manifest <- launch_manifest[, c(
  "batch_id", "run_index", "quantile_id", "quantile_level", "role", "run_id",
  "config_path", "raw_fit_id", "qdesn_fit_id", "raw_model_id", "qdesn_model_id"
), drop = FALSE]
source_manifest$run_dir <- file.path("application/runs", source_manifest$run_id)
source_manifest$required <- TRUE
source_manifest$enabled <- TRUE
app_write_csv(source_manifest, file.path(out_dir, "synthesis_source_manifest.csv"))
app_write_csv(all_qgrid, file.path(out_dir, "quantile_grid_all.csv"))
app_write_csv(do.call(rbind, all_model_rows), file.path(out_dir, "model_grid_all.csv"))

synthesis_cfg <- base_cfg
synthesis_cfg$application_name <- paste0(args$batch_id, "_synthesis")
synthesis_cfg$description <- "Post-hoc synthesis and scoring config for the GloFAS multi-quantile Q-DESN launch."
synthesis_cfg$paths$quantile_grid <- repo_rel(file.path(out_dir, "quantile_grid_all.csv"))
synthesis_cfg$paths$model_grid <- repo_rel(file.path(out_dir, "model_grid_all.csv"))
synthesis_cfg$paths$cache <- file.path("application/cache", paste0(args$batch_id, "_synthesis"))
synthesis_cfg$scoring$intervals <- intervals
synthesis_cfg$execution$final_launch$enabled <- FALSE
synthesis_cfg$execution$final_launch$note <- "Synthesis-only config; it consumes completed per-quantile runs and does not fit models."
synthesis_cfg$post_analysis$run_after_outputs <- FALSE
app_write_yaml(synthesis_cfg, file.path(out_dir, "synthesis_config.yaml"))

shell_path <- file.path(out_dir, sprintf("launch_all_%s.sh", args$batch_id))
writeLines(shell_lines, shell_path)
Sys.chmod(shell_path, "0755")

readme_lines <- c(
  sprintf("# GloFAS Multi-Quantile Synthesis Launch: %s", args$batch_id),
  "",
  "Prepared but not launched by `application/scripts/10_prepare_glofas_multiquantile_launch.R`.",
  "",
  "Target quantiles: 0.05, 0.15, 0.35, 0.50, 0.65, 0.80, 0.95.",
  "",
  "Prepared files:",
  sprintf("- Launch manifest: `%s`", repo_rel(file.path(out_dir, "launch_manifest.csv"))),
  sprintf("- Synthesis source manifest: `%s`", repo_rel(file.path(out_dir, "synthesis_source_manifest.csv"))),
  sprintf("- Synthesis config: `%s`", repo_rel(file.path(out_dir, "synthesis_config.yaml"))),
  sprintf("- Launcher: `%s`", repo_rel(shell_path)),
  "",
  "Launch requires explicit human confirmation. The generated launcher starts one tmux session per quantile fit.",
  "",
  "After all runs complete, synthesize with:",
  sprintf("`Rscript application/scripts/10_synthesize_glofas_quantile_runs.R --config %s --source_manifest %s`",
    repo_rel(file.path(out_dir, "synthesis_config.yaml")),
    repo_rel(file.path(out_dir, "synthesis_source_manifest.csv"))
  )
)
writeLines(readme_lines, file.path(out_dir, "README.md"))

cat(file.path(out_dir, "launch_manifest.csv"), "\n")
