#!/usr/bin/env Rscript
# Purpose: prepare no-launch GloFAS readout-refinement gate configs.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/model_contract.R"))

args <- app_parse_args(list(
  base_config = "local_trackers/runtime_configs/glofas_multiquantile_dec25_20260603/config_p50.yaml",
  quantile_targets = "application/config/glofas_quantile_targets_dec25_synthesis_20260603.csv",
  out_dir = "local_trackers/runtime_configs/glofas_readout_refinement_gate_20260606",
  batch_id = "glofas_readout_refinement_gate_20260606",
  first_core = 43
))

repo_rel <- function(path) app_prefer_repo_relative_path(path)
as_range <- function(lo, hi) list(range = c(as.integer(lo), as.integer(hi)))
q_label <- function(qid) gsub("[^A-Za-z0-9]+", "", as.character(qid))

copy_without_runtime_fields <- function(cfg) {
  cfg$.__config_path__ <- NULL
  cfg
}

set_lag_policy <- function(cfg, output_lag_hi, covariate_lag_hi, include_input_block = TRUE) {
  cfg$feature_contract$readout$include_input_block <- include_input_block
  cfg$feature_contract$readout$input_block$output_lags <- as_range(1L, output_lag_hi)
  cfg$feature_contract$readout$input_block$covariates$ppt <- as_range(0L, covariate_lag_hi)
  cfg$feature_contract$readout$input_block$covariates$soil <- as_range(0L, covariate_lag_hi)
  cfg
}

candidate_grid <- data.frame(
  candidate_id = c(
    "current_m360_direct360",
    "reservoir_only_m360",
    "direct030_m360",
    "direct090_m360",
    "direct180_m360",
    "direct030_m180",
    "direct090_m180"
  ),
  m = c(360L, 360L, 360L, 360L, 360L, 180L, 180L),
  include_input_block = c(TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE),
  output_lag_hi = c(360L, 30L, 30L, 90L, 180L, 30L, 90L),
  covariate_lag_hi = c(360L, 30L, 30L, 90L, 180L, 30L, 90L),
  gate_role = c(
    "current_reference",
    "pure_reservoir_readout",
    "short_direct_lag_regularization",
    "moderate_direct_lag_regularization",
    "longer_direct_lag_compromise",
    "short_memory_short_direct_lags",
    "short_memory_moderate_direct_lags"
  ),
  stringsAsFactors = FALSE
)

base_cfg <- copy_without_runtime_fields(app_read_config(app_path(args$base_config)))
targets_all <- app_validate_quantile_grid(app_path(args$quantile_targets))
targets <- targets_all[targets_all$quantile_level %in% c(0.05, 0.50, 0.95), , drop = FALSE]
targets <- targets[order(targets$quantile_level), , drop = FALSE]
out_dir <- app_path(args$out_dir)
app_ensure_dir(out_dir)
app_write_csv(candidate_grid, file.path(out_dir, "candidate_grid.csv"))

intervals <- list(list(lower = 0.05, upper = 0.95, nominal = 0.90))
manifest_rows <- list()
source_rows <- list()
launcher <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "",
  "# Generated by application/scripts/17_prepare_glofas_readout_refinement_gate.R.",
  "# Review candidate_grid.csv and launch_manifest.csv before running.",
  ""
)

launch_index <- 1L
for (cidx in seq_len(nrow(candidate_grid))) {
  cand <- candidate_grid[cidx, , drop = FALSE]
  cand_dir <- file.path(out_dir, cand$candidate_id)
  app_ensure_dir(cand_dir)
  cand_model_rows <- list()
  cand_q_rows <- list()
  for (qidx in seq_len(nrow(targets))) {
    target <- targets[qidx, , drop = FALSE]
    qid <- q_label(target$quantile_id)
    qlev <- as.numeric(target$quantile_level)
    run_id <- sprintf("%s_%s_%s", args$batch_id, cand$candidate_id, qid)
    qgrid_path <- file.path(cand_dir, sprintf("quantile_grid_%s.csv", qid))
    model_grid_path <- file.path(cand_dir, sprintf("model_grid_%s.csv", qid))
    config_path <- file.path(cand_dir, sprintf("config_%s.yaml", qid))
    app_write_csv(target, qgrid_path)
    cand_q_rows[[qidx]] <- target

    base_grid <- app_validate_model_grid(app_config_path(base_cfg, "model_grid"), app_config_path(base_cfg, "schema"))
    raw_row <- base_grid[base_grid$model_family == "raw_glofas", , drop = FALSE][1L, , drop = FALSE]
    qdesn_row <- base_grid[base_grid$model_family == "qdesn_glofas_discrepancy", , drop = FALSE][1L, , drop = FALSE]
    suffix <- paste0(cand$candidate_id, "_", qid)
    shared_suffix <- paste0(cand$candidate_id, "_gate")
    raw_row$fit_id <- paste0("raw_glofas_", suffix)
    raw_row$model_id <- paste0("raw_glofas_", shared_suffix)
    raw_row$quantile_level <- qlev
    raw_row$config_hash <- "TO_BE_COMPUTED"
    raw_row$notes <- sprintf("Raw GloFAS gate component for %s; quantile=%s.", cand$candidate_id, qlev)
    qdesn_row$fit_id <- paste0("qdesn_latent_path_rhs_al_vb_", suffix)
    qdesn_row$model_id <- paste0("qdesn_latent_path_rhs_al_vb_", shared_suffix)
    qdesn_row$quantile_level <- qlev
    qdesn_row$reservoir_seed <- app_config_reservoir_seed(base_cfg)
    qdesn_row$config_hash <- "TO_BE_COMPUTED"
    qdesn_row$notes <- sprintf("Q-DESN readout-refinement gate component for %s; quantile=%s.", cand$candidate_id, qlev)
    model_grid <- rbind(raw_row, qdesn_row)
    app_write_csv(model_grid, model_grid_path)
    cand_model_rows[[qidx]] <- model_grid

    cfg <- base_cfg
    cfg$application_name <- run_id
    cfg$description <- sprintf("Readout-refinement gate: %s, quantile %s. Prepared for explicit launch only.", cand$candidate_id, qlev)
    cfg$paths$quantile_grid <- repo_rel(qgrid_path)
    cfg$paths$model_grid <- repo_rel(model_grid_path)
    cfg$paths$cache <- file.path("application/cache", run_id)
    cfg$reservoir$m <- as.integer(cand$m)
    cfg$feature_contract$reservoir_input$output_lags <- as_range(1L, as.integer(cand$m))
    cfg$feature_contract$reservoir_input$covariates$ppt <- as_range(0L, as.integer(cand$m))
    cfg$feature_contract$reservoir_input$covariates$soil <- as_range(0L, as.integer(cand$m))
    cfg <- set_lag_policy(
      cfg,
      output_lag_hi = as.integer(cand$output_lag_hi),
      covariate_lag_hi = as.integer(cand$covariate_lag_hi),
      include_input_block = as.logical(cand$include_input_block)
    )
    cfg$scoring$intervals <- intervals
    cfg$execution$final_launch$enabled <- TRUE
    cfg$execution$final_launch$note <- "Readout-refinement gate config. Launch only after explicit human confirmation."
    cfg$post_analysis$run_after_outputs <- FALSE
    app_write_yaml(cfg, config_path)

    core <- as.integer(args$first_core) + launch_index - 1L
    manifest_rows[[launch_index]] <- data.frame(
      batch_id = args$batch_id,
      candidate_id = cand$candidate_id,
      gate_role = cand$gate_role,
      run_index = launch_index,
      quantile_id = qid,
      quantile_level = qlev,
      run_id = run_id,
      config_path = repo_rel(config_path),
      model_grid_path = repo_rel(model_grid_path),
      quantile_grid_path = repo_rel(qgrid_path),
      core = core,
      launch_status = "prepared_not_launched",
      stringsAsFactors = FALSE
    )
    source_rows[[launch_index]] <- data.frame(
      batch_id = args$batch_id,
      candidate_id = cand$candidate_id,
      run_index = qidx,
      quantile_id = qid,
      quantile_level = qlev,
      role = as.character(target$role),
      run_id = run_id,
      config_path = repo_rel(config_path),
      raw_fit_id = raw_row$fit_id,
      qdesn_fit_id = qdesn_row$fit_id,
      raw_model_id = raw_row$model_id,
      qdesn_model_id = qdesn_row$model_id,
      run_dir = file.path("application/runs", run_id),
      required = TRUE,
      enabled = TRUE,
      stringsAsFactors = FALSE
    )
    launcher <- c(
      launcher,
      sprintf("# %s %s", cand$candidate_id, qid),
      sprintf(
        "tmux new-session -d -s %s %s",
        shQuote(sprintf("%s_%s_%s", args$batch_id, cand$candidate_id, qid)),
        shQuote(sprintf(
          "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
          core,
          repo_rel(config_path),
          run_id,
          file.path("application/logs", paste0(run_id, ".log"))
        ))
      ),
      ""
    )
    launch_index <- launch_index + 1L
  }
  app_write_csv(do.call(rbind, cand_q_rows), file.path(cand_dir, "quantile_grid_gate.csv"))
  app_write_csv(do.call(rbind, cand_model_rows), file.path(cand_dir, "model_grid_gate.csv"))
}

launch_manifest <- do.call(rbind, manifest_rows)
source_manifest <- do.call(rbind, source_rows)
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
app_write_csv(source_manifest, file.path(out_dir, "synthesis_source_manifest_gate.csv"))

launcher_path <- file.path(out_dir, paste0("launch_all_", args$batch_id, ".sh"))
writeLines(launcher, launcher_path)
Sys.chmod(launcher_path, "0755")

readme <- c(
  sprintf("# GloFAS Readout Refinement Gate: %s", args$batch_id),
  "",
  "This directory is generated locally and ignored by git.",
  "",
  "Purpose: prepare a controlled p05/p50/p95 gate for candidate readout-memory policies after the no-refit synthesis/readout audit.",
  "",
  "Nothing is launched by this preparation script.",
  "",
  "Prepared artifacts:",
  "- `candidate_grid.csv`: candidate readout/reservoir-memory policies.",
  "- `launch_manifest.csv`: one p05/p50/p95 run per candidate.",
  "- `synthesis_source_manifest_gate.csv`: per-candidate synthesis source rows.",
  sprintf("- `%s`: generated tmux launcher; run only after explicit confirmation.", basename(launcher_path)),
  "",
  "Gate rule: each candidate should be synthesized and compared on p05/p50/p95 before any full seven-quantile relaunch."
)
writeLines(readme, file.path(out_dir, "README.md"))
message("Prepared readout-refinement gate configs in: ", repo_rel(out_dir))
message("Launcher prepared but not executed: ", repo_rel(launcher_path))
