#!/usr/bin/env Rscript
# Purpose: prepare the full seven-quantile GloFAS launch for the selected
# reservoir-only m=360 readout specification. This script does not launch fits.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/model_contract.R"))

args <- app_parse_args(list(
  base_config = "local_trackers/runtime_configs/glofas_readout_refinement_gate_20260606/reservoir_only_m360/config_p50.yaml",
  quantile_targets = "application/config/glofas_quantile_targets_dec25_synthesis_20260603.csv",
  out_dir = "local_trackers/runtime_configs/glofas_reservoir_only_m360_full7_20260607",
  batch_id = "glofas_reservoir_only_m360_full7_20260607",
  first_core = 43
))

repo_rel <- function(path) app_prefer_repo_relative_path(path)
as_range <- function(lo, hi) list(range = c(as.integer(lo), as.integer(hi)))
q_label <- function(qid) gsub("[^A-Za-z0-9]+", "", as.character(qid))

copy_without_runtime_fields <- function(cfg) {
  cfg$.__config_path__ <- NULL
  cfg
}

set_reservoir_only_m360_contract <- function(cfg) {
  cfg$reservoir$D <- 1L
  cfg$reservoir$n <- 300L
  cfg$reservoir$n_tilde <- list()
  cfg$reservoir$m <- 360L
  cfg$reservoir$washout <- 500L
  cfg$reservoir$alpha <- 0.92
  cfg$reservoir$rho <- 0.95
  cfg$reservoir$pi_w <- 0.03
  cfg$reservoir$pi_in <- 1.0
  cfg$reservoir$win_scale_global <- 0.18
  cfg$reservoir$win_scale_bias <- 0.18
  cfg$reservoir$act_f <- "tanh"
  cfg$reservoir$act_k <- "identity"
  cfg$reservoir$seed <- 20260512L

  cfg$feature_contract$reservoir_input$output_lags <- as_range(1L, 360L)
  cfg$feature_contract$reservoir_input$covariates$ppt <- as_range(0L, 360L)
  cfg$feature_contract$reservoir_input$covariates$soil <- as_range(0L, 360L)
  cfg$feature_contract$readout$add_intercept <- TRUE
  cfg$feature_contract$readout$include_reservoir_state <- TRUE
  cfg$feature_contract$readout$include_input_block <- FALSE
  cfg$feature_contract$readout$input_block$output_lags <- as_range(1L, 30L)
  cfg$feature_contract$readout$input_block$covariates$ppt <- as_range(0L, 30L)
  cfg$feature_contract$readout$input_block$covariates$soil <- as_range(0L, 30L)
  cfg
}

target_levels <- c(0.05, 0.15, 0.35, 0.50, 0.65, 0.80, 0.95)
intervals <- list(
  list(lower = 0.05, upper = 0.95, nominal = 0.90),
  list(lower = 0.15, upper = 0.80, nominal = 0.65),
  list(lower = 0.35, upper = 0.65, nominal = 0.30)
)

base_config_path <- app_path(args$base_config)
target_path <- app_path(args$quantile_targets)
out_dir <- app_path(args$out_dir)
app_ensure_dir(out_dir)

base_cfg <- copy_without_runtime_fields(app_read_config(base_config_path))
targets_all <- app_validate_quantile_grid(target_path)
targets <- targets_all[as.numeric(targets_all$quantile_level) %in% target_levels, , drop = FALSE]
targets <- targets[order(as.numeric(targets$quantile_level)), , drop = FALSE]
if (!identical(round(as.numeric(targets$quantile_level), 8), target_levels)) {
  stop("Quantile target file does not contain exactly the required enabled full-seven grid.", call. = FALSE)
}

base_grid <- app_validate_model_grid(app_config_path(base_cfg, "model_grid"), app_config_path(base_cfg, "schema"))
raw_base <- base_grid[base_grid$model_family == "raw_glofas", , drop = FALSE][1L, , drop = FALSE]
qdesn_base <- base_grid[base_grid$model_family == "qdesn_glofas_discrepancy", , drop = FALSE][1L, , drop = FALSE]
if (!nrow(raw_base) || !nrow(qdesn_base)) {
  stop("Base model grid must contain one raw_glofas row and one qdesn_glofas_discrepancy row.", call. = FALSE)
}

fit_suffix <- "reservoir_only_m360_full7"
raw_model_id <- paste0("raw_glofas_", fit_suffix)
qdesn_model_id <- paste0("qdesn_latent_path_rhs_al_vb_", fit_suffix)

manifest_rows <- vector("list", nrow(targets))
all_model_rows <- vector("list", nrow(targets))
shell_lines <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "export NUMEXPR_NUM_THREADS=1",
  "",
  "# Generated by application/scripts/19_prepare_glofas_reservoir_only_full7_launch.R.",
  "# Review launch_manifest.csv before running. Each quantile uses one tmux session.",
  ""
)

for (i in seq_len(nrow(targets))) {
  qid <- q_label(targets$quantile_id[[i]])
  qlev <- as.numeric(targets$quantile_level[[i]])
  role <- as.character(targets$role[[i]])
  run_id <- sprintf("%s_%s", args$batch_id, qid)
  qgrid_path <- file.path(out_dir, sprintf("quantile_grid_%s.csv", qid))
  model_grid_path <- file.path(out_dir, sprintf("model_grid_%s.csv", qid))
  config_path <- file.path(out_dir, sprintf("config_%s.yaml", qid))
  core <- as.integer(args$first_core) + i - 1L

  qgrid <- targets[i, , drop = FALSE]
  app_write_csv(qgrid, qgrid_path)

  raw_row <- raw_base
  qdesn_row <- qdesn_base
  raw_row$fit_id <- sprintf("raw_glofas_%s_%s", fit_suffix, qid)
  raw_row$model_id <- raw_model_id
  raw_row$quantile_level <- qlev
  raw_row$config_hash <- "TO_BE_COMPUTED"
  raw_row$notes <- sprintf(
    "Raw GloFAS baseline for reservoir-only full-seven launch; quantile=%s (%s).",
    format(qlev, trim = TRUE),
    role
  )
  qdesn_row$fit_id <- sprintf("qdesn_latent_path_rhs_al_vb_%s_%s", fit_suffix, qid)
  qdesn_row$model_id <- qdesn_model_id
  qdesn_row$quantile_level <- qlev
  qdesn_row$reservoir_seed <- 20260512L
  qdesn_row$config_hash <- "TO_BE_COMPUTED"
  qdesn_row$notes <- sprintf(
    "Q-DESN reservoir-only m=360 discrepancy fit for full-seven post-hoc synthesis; quantile=%s (%s).",
    format(qlev, trim = TRUE),
    role
  )
  model_grid <- rbind(raw_row, qdesn_row)
  app_write_csv(model_grid, model_grid_path)
  all_model_rows[[i]] <- model_grid

  cfg <- set_reservoir_only_m360_contract(base_cfg)
  cfg$application_name <- run_id
  cfg$description <- paste(
    "Single-quantile component of the selected GloFAS reservoir-only m=360 full-seven Q-DESN launch.",
    sprintf("Quantile %s (%s). The direct readout input block is disabled; the readout uses intercept plus reservoir state.", format(qlev, trim = TRUE), role)
  )
  cfg$paths$quantile_grid <- repo_rel(qgrid_path)
  cfg$paths$model_grid <- repo_rel(model_grid_path)
  cfg$paths$cache <- file.path("application/cache", run_id)
  cfg$scoring$intervals <- intervals
  cfg$inference$vb_ld$max_iter <- 150L
  cfg$inference$vb_ld$max_iter_hard_cap <- 150L
  cfg$inference$vb_ld$n_draws <- 2000L
  cfg$inference$vb_ld$diagnostics$profile_substeps <- FALSE
  cfg$execution$final_launch$enabled <- TRUE
  cfg$execution$final_launch$note <- paste(
    "User-approved full-seven quantile component for the selected reservoir-only m=360 specification.",
    "Do not promote a single quantile alone; combine all completed quantiles with application/scripts/10_synthesize_glofas_quantile_runs.R."
  )
  cfg$post_analysis$run_after_outputs <- FALSE
  app_write_yaml(cfg, config_path)

  manifest_rows[[i]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    core = core,
    raw_fit_id = raw_row$fit_id,
    qdesn_fit_id = qdesn_row$fit_id,
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    launch_status = "prepared_not_launched",
    stringsAsFactors = FALSE
  )

  session <- sprintf("%s_%s", args$batch_id, qid)
  log_path <- file.path("application/logs", sprintf("%s.log", run_id))
  shell_lines <- c(
    shell_lines,
    sprintf("# %s (%s)", qid, format(qlev, trim = TRUE)),
    sprintf(
      "tmux new-session -d -s %s %s",
      shQuote(session),
      shQuote(sprintf(
        "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
        core,
        repo_rel(config_path),
        run_id,
        log_path
      ))
    ),
    ""
  )
}

launch_manifest <- do.call(rbind, manifest_rows)
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
source_manifest <- launch_manifest[, c(
  "batch_id", "run_index", "quantile_id", "quantile_level", "role", "run_id",
  "config_path", "raw_fit_id", "qdesn_fit_id", "raw_model_id", "qdesn_model_id"
), drop = FALSE]
source_manifest$run_dir <- file.path("application/runs", source_manifest$run_id)
source_manifest$required <- TRUE
source_manifest$enabled <- TRUE
app_write_csv(source_manifest, file.path(out_dir, "synthesis_source_manifest.csv"))
app_write_csv(targets, file.path(out_dir, "quantile_grid_all.csv"))
app_write_csv(do.call(rbind, all_model_rows), file.path(out_dir, "model_grid_all.csv"))

synthesis_cfg <- set_reservoir_only_m360_contract(base_cfg)
synthesis_cfg$application_name <- paste0(args$batch_id, "_synthesis")
synthesis_cfg$description <- "Post-hoc synthesis and scoring config for the selected GloFAS reservoir-only m=360 full-seven Q-DESN launch."
synthesis_cfg$paths$quantile_grid <- repo_rel(file.path(out_dir, "quantile_grid_all.csv"))
synthesis_cfg$paths$model_grid <- repo_rel(file.path(out_dir, "model_grid_all.csv"))
synthesis_cfg$paths$cache <- file.path("application/cache", paste0(args$batch_id, "_synthesis"))
synthesis_cfg$scoring$intervals <- intervals
synthesis_cfg$execution$final_launch$enabled <- FALSE
synthesis_cfg$execution$final_launch$note <- "Synthesis-only config; it consumes completed per-quantile runs and does not fit models."
synthesis_cfg$post_analysis$run_after_outputs <- FALSE
app_write_yaml(synthesis_cfg, file.path(out_dir, "synthesis_config.yaml"))

shell_path <- file.path(out_dir, sprintf("launch_all_%s.sh", args$batch_id))
writeLines(shell_lines, shell_path)
Sys.chmod(shell_path, "0755")

synth_path <- file.path(out_dir, "synthesize_when_complete.sh")
synth_lines <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "Rscript application/scripts/10_synthesize_glofas_quantile_runs.R \\",
  sprintf("  --config %s \\", shQuote(repo_rel(file.path(out_dir, "synthesis_config.yaml")))),
  sprintf("  --source_manifest %s \\", shQuote(repo_rel(file.path(out_dir, "synthesis_source_manifest.csv")))),
  sprintf("  --run_id %s", shQuote(paste0(args$batch_id, "_synthesis_final")))
)
writeLines(synth_lines, synth_path)
Sys.chmod(synth_path, "0755")

readme_lines <- c(
  sprintf("# GloFAS Reservoir-Only Full-Seven Launch: %s", args$batch_id),
  "",
  "This directory is generated locally and ignored by git.",
  "",
  "Purpose: launch the selected `reservoir_only_m360` specification at seven quantile levels, then consume the completed component runs through post-hoc monotone synthesis.",
  "",
  "Scientific contract:",
  "- DESN: `D=1`, `n=300`, `m=360`, `alpha=0.92`, `rho=0.95`, `pi_w=0.03`, `pi_in=1.0`.",
  "- Input scale: `win_scale_global=0.18`, `win_scale_bias=0.18`, seed `20260512`.",
  "- Reservoir input: response lags `1:360` and `ppt`/`soil` lags `0:360`.",
  "- Readout: intercept plus reservoir state; direct input block disabled.",
  "- Inference: AL/VB, `max_iter=150`, `n_draws=2000`.",
  "",
  "Prepared files:",
  sprintf("- Launch manifest: `%s`", repo_rel(file.path(out_dir, "launch_manifest.csv"))),
  sprintf("- Synthesis source manifest: `%s`", repo_rel(file.path(out_dir, "synthesis_source_manifest.csv"))),
  sprintf("- Synthesis config: `%s`", repo_rel(file.path(out_dir, "synthesis_config.yaml"))),
  sprintf("- Launcher: `%s`", repo_rel(shell_path)),
  sprintf("- Synthesis command: `%s`", repo_rel(synth_path)),
  "",
  "Launch requires explicit confirmation. The launcher starts one tmux session per quantile fit.",
  "",
  "After every component run has `fit_status.csv` rows marked `completed`, run:",
  sprintf("`%s`", repo_rel(synth_path))
)
writeLines(readme_lines, file.path(out_dir, "README.md"))

message("Prepared reservoir-only full-seven configs in: ", repo_rel(out_dir))
message("Launcher prepared but not executed: ", repo_rel(shell_path))
cat(file.path(out_dir, "launch_manifest.csv"), "\n")
