#!/usr/bin/env Rscript
# Purpose: prepare a corrected true reservoir-seed p50 gate for the top
# direct-skip GloFAS median candidates. This script writes ignored runtime
# configs and a launcher; it does not fit models by itself.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/engine_contract.R"))
source(app_path("application/R/model_contract.R"))

args <- app_parse_args(list(
  source_manifest = "local_trackers/runtime_configs/glofas_directskip_median_grid_20260608/launch_manifest.csv",
  source_audit = "local_trackers/runtime_configs/glofas_directskip_median_grid_20260608/final_or_live_median_grid_audit.csv",
  candidate_ids = "D14,D16,D01",
  repeat_seed = "20260610",
  out_dir = "local_trackers/runtime_configs/glofas_directskip_true_seed_gate_20260610",
  batch_id = "glofas_directskip_true_seed_gate_20260610",
  first_core = "30"
))

repo_rel <- function(path) app_prefer_repo_relative_path(path)
slugify <- function(x) gsub("[^A-Za-z0-9_.-]+", "_", as.character(x))
candidate_ids <- trimws(strsplit(as.character(args$candidate_ids), ",", fixed = TRUE)[[1L]])
repeat_seed <- as.integer(args$repeat_seed)
first_core <- as.integer(args$first_core)
if (!length(candidate_ids) || any(!nzchar(candidate_ids))) stop("--candidate_ids must not be empty.", call. = FALSE)
if (!is.finite(repeat_seed)) stop("--repeat_seed must be an integer.", call. = FALSE)
if (!is.finite(first_core)) stop("--first_core must be an integer.", call. = FALSE)

source_manifest <- app_read_csv(app_path(args$source_manifest))
source_audit <- app_read_csv(app_path(args$source_audit))
source_manifest <- source_manifest[source_manifest$candidate_id %in% candidate_ids, , drop = FALSE]
source_manifest$candidate_id <- factor(source_manifest$candidate_id, levels = candidate_ids)
source_manifest <- source_manifest[order(source_manifest$candidate_id), , drop = FALSE]
source_manifest$candidate_id <- as.character(source_manifest$candidate_id)
missing_ids <- setdiff(candidate_ids, source_manifest$candidate_id)
if (length(missing_ids)) {
  stop(sprintf("Source manifest is missing candidate ids: %s", paste(missing_ids, collapse = ", ")), call. = FALSE)
}

out_dir <- app_path(args$out_dir)
app_ensure_dir(out_dir)
app_write_csv(source_manifest, file.path(out_dir, "source_manifest_subset.csv"))

launcher <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "export NUMEXPR_NUM_THREADS=1",
  "",
  "# Generated by application/scripts/24_prepare_glofas_directskip_true_seed_gate_20260610.R.",
  "# Corrected p50 true reservoir-seed gate. One tmux session per candidate.",
  ""
)

manifest_rows <- vector("list", nrow(source_manifest))
seed_contract_rows <- list()
for (i in seq_len(nrow(source_manifest))) {
  src <- source_manifest[i, , drop = FALSE]
  source_cfg <- app_read_config(app_path(src$config_path[[1L]]))
  source_cfg$.__config_path__ <- NULL
  source_grid <- app_validate_model_grid(app_path(src$model_grid_path[[1L]]), app_config_path(source_cfg, "schema"))
  qrows <- source_grid[source_grid$model_family == "qdesn_glofas_discrepancy", , drop = FALSE]
  if (nrow(qrows) != 1L) {
    stop(sprintf("Expected exactly one Q-DESN row for candidate %s.", src$candidate_id[[1L]]), call. = FALSE)
  }

  role <- as.character(src$search_role[[1L]])
  seed_tag <- paste0("seed", repeat_seed)
  candidate_slug <- slugify(tolower(sprintf(
    "%s_%s_%s_d%sn%s_m%s_dir%s_a%s_r%s_w%s_bt%s_at%s",
    src$candidate_id[[1L]],
    role,
    seed_tag,
    src$D[[1L]],
    src$n[[1L]],
    src$reservoir_m[[1L]],
    src$direct_lag[[1L]],
    gsub("[.]", "p", sprintf("%.2f", as.numeric(src$alpha[[1L]]))),
    gsub("[.]", "p", sprintf("%.2f", as.numeric(src$rho[[1L]]))),
    gsub("[.]", "p", sprintf("%.2f", as.numeric(src$win_scale_global[[1L]]))),
    gsub("[.]", "p", format(as.numeric(src$beta_tau0[[1L]]), scientific = FALSE, trim = TRUE)),
    gsub("[.]", "p", format(as.numeric(src$alpha_tau0[[1L]]), scientific = FALSE, trim = TRUE))
  )))
  cand_dir <- file.path(out_dir, candidate_slug)
  app_ensure_dir(cand_dir)

  run_id <- sprintf("%s_%s_p50", args$batch_id, candidate_slug)
  config_path <- file.path(cand_dir, "config_p50.yaml")
  model_grid_path <- file.path(cand_dir, "model_grid_p50.csv")
  quantile_grid_path <- file.path(cand_dir, "quantile_grid_p50.csv")
  file.copy(app_path(src$quantile_grid_path[[1L]]), quantile_grid_path, overwrite = TRUE)

  model_grid <- source_grid
  q_idx <- model_grid$model_family == "qdesn_glofas_discrepancy"
  raw_idx <- model_grid$model_family == "raw_glofas"
  for (col in intersect(c("fit_id", "model_id"), names(model_grid))) {
    model_grid[[col]][q_idx] <- paste0(model_grid[[col]][q_idx], "_", seed_tag, "_true_seed")
    model_grid[[col]][raw_idx] <- paste0(model_grid[[col]][raw_idx], "_", seed_tag, "_true_seed")
  }
  model_grid$reservoir_seed[q_idx] <- repeat_seed
  if ("notes" %in% names(model_grid)) {
    model_grid$notes[q_idx] <- paste(
      model_grid$notes[q_idx],
      sprintf("Corrected true-seed gate: config reservoir seed and model-grid reservoir_seed are both %d.", repeat_seed)
    )
    model_grid$notes[raw_idx] <- paste(
      model_grid$notes[raw_idx],
      sprintf("Raw GloFAS row retained for corrected true-seed gate %s.", args$batch_id)
    )
  }
  app_write_csv(model_grid, model_grid_path)

  cfg <- source_cfg
  cfg$application_name <- run_id
  cfg$description <- paste(
    sprintf("Corrected true reservoir-seed p50 gate for %s (%s).", src$candidate_id[[1L]], role),
    sprintf("Both config reservoir seed and model-grid reservoir_seed are set to %d.", repeat_seed)
  )
  cfg$paths$quantile_grid <- repo_rel(quantile_grid_path)
  cfg$paths$model_grid <- repo_rel(model_grid_path)
  cfg$paths$cache <- file.path("application/cache", run_id)
  cfg$reservoir$seed <- repeat_seed
  cfg$execution$seed_contract <- cfg$execution$seed_contract %||% list()
  cfg$execution$seed_contract$require_config_model_grid_match <- TRUE
  cfg$execution$final_launch$enabled <- TRUE
  cfg$execution$final_launch$note <- paste(
    "User-approved corrected p50 true-seed gate.",
    "Do not launch full-seven quantiles until this gate is scored and visually reviewed."
  )
  cfg$post_analysis$run_after_outputs <- FALSE
  app_write_yaml(cfg, config_path)

  validated_grid <- app_validate_model_grid(model_grid_path, app_config_path(cfg, "schema"))
  seed_contract <- app_qdesn_seed_contract_report(cfg, validated_grid)
  app_validate_qdesn_seed_contract(cfg, validated_grid)
  seed_contract$candidate_id <- src$candidate_id[[1L]]
  seed_contract$search_role <- role
  seed_contract$run_id <- run_id
  seed_contract_rows[[i]] <- seed_contract
  app_write_csv(seed_contract, file.path(cand_dir, "seed_contract_prelaunch.csv"))

  original <- source_audit[source_audit$candidate_id == src$candidate_id[[1L]], , drop = FALSE][1L, ]
  core <- first_core + i - 1L
  session <- sprintf("%s_%s", args$batch_id, src$candidate_id[[1L]])
  log_path <- file.path("application/logs", paste0(run_id, ".log"))
  manifest_rows[[i]] <- data.frame(
    batch_id = args$batch_id,
    candidate_id = src$candidate_id,
    search_role = role,
    run_index = i,
    repeat_seed = repeat_seed,
    original_seed = src$seed,
    original_q_check = suppressWarnings(as.numeric(original$q_check[[1L]])),
    original_run_id = src$run_id,
    run_id = run_id,
    config_path = repo_rel(config_path),
    model_grid_path = repo_rel(model_grid_path),
    quantile_grid_path = repo_rel(quantile_grid_path),
    core = core,
    session = session,
    log_path = log_path,
    qdesn_fit_id = model_grid$fit_id[q_idx][[1L]],
    qdesn_model_id = model_grid$model_id[q_idx][[1L]],
    launch_status = "prepared_not_launched",
    stringsAsFactors = FALSE
  )

  command <- sprintf(
    "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
    core,
    repo_rel(config_path),
    run_id,
    log_path
  )
  launcher <- c(
    launcher,
    sprintf("# %s: %s", src$candidate_id[[1L]], role),
    sprintf("if tmux has-session -t %s 2>/dev/null; then echo 'Session exists: %s' >&2; exit 1; fi", shQuote(session), session),
    sprintf("tmux new-session -d -s %s %s", shQuote(session), shQuote(command)),
    ""
  )
}

launch_manifest <- app_bind_rows_fill(manifest_rows)
seed_contract_all <- app_bind_rows_fill(seed_contract_rows)
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
app_write_csv(seed_contract_all, file.path(out_dir, "seed_contract_prelaunch_all.csv"))

launcher_path <- file.path(out_dir, sprintf("launch_all_%s.sh", args$batch_id))
writeLines(launcher, launcher_path)
Sys.chmod(launcher_path, "0755")

readme <- c(
  sprintf("# GloFAS Corrected True-Seed Gate: %s", args$batch_id),
  "",
  "This directory is generated locally and ignored by git.",
  "",
  sprintf("Repeat seed: `%d`.", repeat_seed),
  "",
  "Purpose: rerun the top p50 direct-skip candidates with a genuinely changed reservoir seed.",
  "",
  "Critical guard:",
  "- `config$reservoir$seed` and the enabled Q-DESN `model_grid$reservoir_seed` must match.",
  "- `seed_contract_prelaunch_all.csv` records the effective, reference, and discrepancy reservoir seeds.",
  "",
  "Candidates:",
  paste(sprintf("- `%s`", launch_manifest$candidate_id), collapse = "\n"),
  "",
  "Launch:",
  sprintf("`bash %s`", repo_rel(launcher_path)),
  "",
  "After completion, summarize with:",
  sprintf("`Rscript application/scripts/24_summarize_glofas_directskip_true_seed_gate.R --runtime_dir %s`", repo_rel(out_dir))
)
writeLines(readme, file.path(out_dir, "README.md"))

cat(repo_rel(file.path(out_dir, "launch_manifest.csv")), "\n")
