#!/usr/bin/env Rscript
# Purpose: prepare an oracle-realized precipitation/soil full-seven launch for
# the current D14 GloFAS Q-DESN specification.
#
# The generated runtime configs are ignored by git. This script does not launch
# fits; use the generated launch_all_*.sh after validating the manifest.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/model_contract.R"))
source(app_path("application/R/engine_contract.R"))
source(app_path("application/R/covariate_design.R"))

args <- app_parse_args(list(
  source_runtime_dir = "local_trackers/runtime_configs/glofas_d14_true_seed_full7_20260611",
  out_dir = "local_trackers/runtime_configs/glofas_d14_oracle_full7_20260613",
  batch_id = "glofas_d14_oracle_full7_20260613",
  first_core = "36"
))

repo_rel <- function(path) app_prefer_repo_relative_path(path)
q_label <- function(qid) gsub("[^A-Za-z0-9]+", "", as.character(qid))

n_cores <- parallel::detectCores(logical = TRUE)
source_dir <- app_path(args$source_runtime_dir)
out_dir <- app_path(args$out_dir)
manifest_path <- file.path(source_dir, "launch_manifest.csv")
if (!file.exists(manifest_path)) stop(sprintf("Missing source launch manifest: %s", manifest_path), call. = FALSE)
source_manifest <- app_read_csv(manifest_path)
source_manifest <- source_manifest[order(source_manifest$run_index), , drop = FALSE]
requested_cores <- as.integer(args$first_core) + seq_len(nrow(source_manifest)) - 1L
if (any(requested_cores < 0L | requested_cores >= n_cores)) {
  stop(sprintf("Requested core range is invalid for %d detected cores: %s", n_cores, paste(requested_cores, collapse = ", ")), call. = FALSE)
}

app_ensure_dir(out_dir)
fit_suffix <- "d14_oracle_d1n300_m360_dir360_a098_r095_w018_bt1em01_at3em02_full7"
raw_model_id <- paste0("raw_glofas_", fit_suffix)
qdesn_model_id <- paste0("qdesn_latent_path_rhs_al_vb_", fit_suffix)

intervals <- list(
  list(lower = 0.05, upper = 0.95, nominal = 0.90),
  list(lower = 0.15, upper = 0.80, nominal = 0.65),
  list(lower = 0.35, upper = 0.65, nominal = 0.30)
)

set_oracle_covariates <- function(cfg) {
  cfg$covariates$source_policy <- NULL
  cfg$covariates$future_policy <- "oracle_realized"
  cfg$covariates$allow_realized_future <- TRUE
  cfg$covariates$allow_realized_future_blend <- NULL
  cfg$covariates$forecast$provider <- "realized_future_oracle"
  cfg$covariates$forecast$handoff_root <- NULL
  for (v in c("ppt", "soil")) {
    cfg$covariates[[v]]$noisy_blend <- NULL
    cfg$covariates[[v]]$observed_blend <- NULL
    cfg$covariates[[v]]$forecast_noise <- list(enabled = FALSE)
    cfg$covariates[[v]]$realized_future_correction <- list(enabled = TRUE, observed_weight = 1)
  }
  cfg
}

manifest_rows <- vector("list", nrow(source_manifest))
model_rows_all <- vector("list", nrow(source_manifest))
shell_lines <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "export NUMEXPR_NUM_THREADS=1",
  "",
  sprintf("# Generated by %s.", "application/scripts/27_prepare_glofas_d14_oracle_full7_20260613.R"),
  "# Oracle-realized precipitation/soil full-seven launch. One tmux session per quantile.",
  ""
)

for (i in seq_len(nrow(source_manifest))) {
  src <- source_manifest[i, , drop = FALSE]
  qid <- q_label(src$quantile_id[[1L]])
  qlev <- as.numeric(src$quantile_level[[1L]])
  role <- as.character(src$role[[1L]])
  run_id <- sprintf("%s_%s", args$batch_id, qid)
  core <- requested_cores[[i]]

  src_config <- app_read_config(app_path(src$config_path[[1L]]))
  src_qgrid <- app_read_csv(app_path(src$quantile_grid_path[[1L]]))
  src_model_grid <- app_validate_model_grid(app_path(src$model_grid_path[[1L]]), app_config_path(src_config, "schema"))

  qgrid_path <- file.path(out_dir, sprintf("quantile_grid_%s.csv", qid))
  model_grid_path <- file.path(out_dir, sprintf("model_grid_%s.csv", qid))
  config_path <- file.path(out_dir, sprintf("config_%s.yaml", qid))
  app_write_csv(src_qgrid, qgrid_path)

  model_grid <- src_model_grid
  model_grid$quantile_level <- qlev
  model_grid$config_hash <- "TO_BE_COMPUTED"
  raw_idx <- which(model_grid$model_family == "raw_glofas")
  qdesn_idx <- which(model_grid$model_family == "qdesn_glofas_discrepancy")
  if (length(raw_idx) != 1L || length(qdesn_idx) != 1L) {
    stop(sprintf("Expected exactly one raw and one qdesn model row for %s.", src$config_path[[1L]]), call. = FALSE)
  }
  model_grid$fit_id[[raw_idx]] <- sprintf("raw_glofas_%s_%s", fit_suffix, qid)
  model_grid$model_id[[raw_idx]] <- raw_model_id
  model_grid$notes[[raw_idx]] <- sprintf("Raw GloFAS quantile baseline for D14 oracle full-seven launch; quantile=%s (%s).", qlev, role)
  model_grid$fit_id[[qdesn_idx]] <- sprintf("qdesn_latent_path_rhs_al_vb_%s_%s", fit_suffix, qid)
  model_grid$model_id[[qdesn_idx]] <- qdesn_model_id
  model_grid$notes[[qdesn_idx]] <- sprintf("Q-DESN D14 oracle-realized future-covariate component; quantile=%s (%s).", qlev, role)
  app_write_csv(model_grid, model_grid_path)
  app_validate_qdesn_seed_contract(src_config, app_validate_model_grid(model_grid_path, app_config_path(src_config, "schema")))

  cfg <- src_config
  cfg$.__config_path__ <- NULL
  cfg$application_name <- run_id
  cfg$description <- paste(
    "D14 oracle-realized precipitation/soil full-seven GloFAS Q-DESN component.",
    sprintf("Quantile %s (%s).", qlev, role),
    "This is an oracle diagnostic, not a deployable forecast-covariate contract."
  )
  cfg$paths$quantile_grid <- repo_rel(qgrid_path)
  cfg$paths$model_grid <- repo_rel(model_grid_path)
  cfg$paths$cache <- file.path("application/cache", run_id)
  cfg$scoring$intervals <- intervals
  cfg$inference$vb_ld$max_iter <- 150L
  cfg$inference$vb_ld$max_iter_hard_cap <- 150L
  cfg$execution$final_launch$enabled <- TRUE
  cfg$execution$final_launch$note <- "User-approved oracle-realized covariate diagnostic full-seven launch."
  cfg$post_analysis$run_after_outputs <- FALSE
  cfg <- set_oracle_covariates(cfg)
  app_write_yaml(cfg, config_path)

  policy_audit <- app_validate_covariate_source_policy(cfg, cutoff_row = data.frame(origin_date = as.Date("2022-12-25")), stop_on_failure = FALSE)
  if (!identical(policy_audit$status[[1L]], "PASS")) stop(policy_audit$message[[1L]], call. = FALSE)
  if (!isTRUE(policy_audit$uses_realized_future[[1L]])) stop("Oracle runtime config did not report realized-future use.", call. = FALSE)

  session <- sprintf("%s_%s", args$batch_id, qid)
  log_path <- file.path("application/logs", sprintf("%s.log", run_id))
  command <- sprintf(
    "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
    core,
    repo_rel(config_path),
    run_id,
    log_path
  )
  shell_lines <- c(
    shell_lines,
    sprintf("# %s: %s", qid, role),
    sprintf("if tmux has-session -t %s 2>/dev/null; then echo 'Session exists: %s' >&2; exit 1; fi", shQuote(session), session),
    sprintf("tmux new-session -d -s %s %s", shQuote(session), shQuote(command)),
    ""
  )

  manifest_rows[[i]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    core = core,
    raw_fit_id = model_grid$fit_id[[raw_idx]],
    qdesn_fit_id = model_grid$fit_id[[qdesn_idx]],
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    future_policy = "oracle_realized",
    source_provider = "realized_future_oracle",
    launch_status = "prepared_not_launched",
    stringsAsFactors = FALSE
  )
  model_rows_all[[i]] <- model_grid
}

launch_manifest <- do.call(rbind, manifest_rows)
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
app_write_csv(do.call(rbind, model_rows_all), file.path(out_dir, "model_grid_all.csv"))
app_write_csv(do.call(rbind, lapply(seq_len(nrow(source_manifest)), function(i) {
  app_read_csv(app_path(source_manifest$quantile_grid_path[[i]]))
})), file.path(out_dir, "quantile_grid_all.csv"))

synthesis_source <- launch_manifest[, c(
  "batch_id", "run_index", "quantile_id", "quantile_level", "role", "run_id",
  "config_path", "raw_fit_id", "qdesn_fit_id", "raw_model_id", "qdesn_model_id"
), drop = FALSE]
synthesis_source$run_dir <- file.path("application/runs", synthesis_source$run_id)
synthesis_source$required <- TRUE
synthesis_source$enabled <- TRUE
app_write_csv(synthesis_source, file.path(out_dir, "synthesis_source_manifest.csv"))

synthesis_cfg <- set_oracle_covariates(app_read_config(app_path(source_manifest$config_path[[1L]])))
synthesis_cfg$.__config_path__ <- NULL
synthesis_cfg$application_name <- paste0(args$batch_id, "_synthesis")
synthesis_cfg$description <- "Post-hoc synthesis and scoring config for the D14 oracle-realized full-seven GloFAS Q-DESN launch."
synthesis_cfg$paths$quantile_grid <- repo_rel(file.path(out_dir, "quantile_grid_all.csv"))
synthesis_cfg$paths$model_grid <- repo_rel(file.path(out_dir, "model_grid_all.csv"))
synthesis_cfg$paths$cache <- file.path("application/cache", paste0(args$batch_id, "_synthesis"))
synthesis_cfg$scoring$intervals <- intervals
synthesis_cfg$execution$final_launch$enabled <- FALSE
synthesis_cfg$execution$final_launch$note <- "Synthesis-only config; consumes completed D14 oracle full-seven component runs."
synthesis_cfg$post_analysis$run_after_outputs <- FALSE
app_write_yaml(synthesis_cfg, file.path(out_dir, "synthesis_config.yaml"))

shell_path <- file.path(out_dir, sprintf("launch_all_%s.sh", args$batch_id))
writeLines(shell_lines, shell_path)
Sys.chmod(shell_path, "0755")

synth_path <- file.path(out_dir, sprintf("synthesize_%s.sh", args$batch_id))
writeLines(c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  sprintf(
    "Rscript application/scripts/10_synthesize_glofas_quantile_runs.R --config %s --source_manifest %s --run_id %s_synthesis_final",
    repo_rel(file.path(out_dir, "synthesis_config.yaml")),
    repo_rel(file.path(out_dir, "synthesis_source_manifest.csv")),
    args$batch_id
  )
), synth_path)
Sys.chmod(synth_path, "0755")

writeLines(c(
  sprintf("# GloFAS D14 Oracle Full-Seven Launch: %s", args$batch_id),
  "",
  "Prepared locally and ignored by git.",
  "",
  "Purpose:",
  "- Reuse the current D14 specification.",
  "- Replace blended GEFS future precipitation/soil with realized future oracle covariates.",
  "- Quantify whether future-covariate quality is a binding source of forecast-window error.",
  "",
  "Launch:",
  sprintf("`bash %s`", repo_rel(shell_path)),
  "",
  "Synthesize after all component runs complete:",
  sprintf("`bash %s`", repo_rel(synth_path))
), file.path(out_dir, "README.md"))

cat(file.path(args$out_dir, "launch_manifest.csv"), "\n")
