#!/usr/bin/env Rscript

script_file <- normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1L]), mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(script_file), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/validation_interface_contract.R"))

args <- app_parse_args(list(
  config = app_default_tt500_provisional_progress_config(),
  out_tex = app_path("tables/qdesn_validation_tt500_provisional_progress.tex"),
  out_csv = app_path("tables/qdesn_validation_tt500_provisional_progress.csv"),
  out_manifest = app_path("tables/qdesn_validation_tt500_provisional_progress_manifest.txt"),
  require_hashes = TRUE
))

count_state <- function(x, field, state) {
  sum(as.character(x[[field]]) == state, na.rm = TRUE)
}

latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

result <- app_validate_tt500_provisional_progress(
  config_path = args$config,
  require_hashes = app_as_bool(args$require_hashes)
)

atomic <- result$atomic
root <- result$root
config <- result$config
manifest <- result$manifest

status_table <- data.frame(
  scope = c("Atomic likelihood--family specs", "Q--DESN root specs"),
  total = c(nrow(atomic), nrow(root)),
  complete = c(
    count_state(atomic, "completion_state", "complete"),
    count_state(root, "root_completion_state", "complete")
  ),
  running = c(
    count_state(atomic, "completion_state", "running"),
    count_state(root, "root_completion_state", "running")
  ),
  pending = c(
    count_state(atomic, "completion_state", "pending"),
    count_state(root, "root_completion_state", "pending")
  ),
  role = c("Status only", "Status only"),
  stringsAsFactors = FALSE
)

app_write_csv(status_table, args$out_csv)

tex_lines <- c(
  "% Generated by application/scripts/30_build_shared_validation_tt500_provisional_table.R.",
  "% Operational status only; not a final validation result table.",
  "\\begin{tabular}{@{}lrrrrl@{}}",
  "\\toprule",
  "Validation object & Total & Complete & Running & Pending & Role \\\\",
  "\\midrule"
)

for (i in seq_len(nrow(status_table))) {
  tex_lines <- c(
    tex_lines,
    sprintf(
      "%s & %d & %d & %d & %d & %s \\\\",
      latex_escape(status_table$scope[[i]]),
      status_table$total[[i]],
      status_table$complete[[i]],
      status_table$running[[i]],
      status_table$pending[[i]],
      latex_escape(status_table$role[[i]])
    )
  )
}

tex_lines <- c(
  tex_lines,
  "\\bottomrule",
  "\\end{tabular}"
)

app_ensure_dir(dirname(args$out_tex))
writeLines(tex_lines, args$out_tex, useBytes = TRUE)

manifest_lines <- c(
  "Q-DESN TT500 provisional progress table manifest",
  sprintf("Generated at: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
  sprintf("Builder: application/scripts/30_build_shared_validation_tt500_provisional_table.R"),
  sprintf("Config: %s", normalizePath(args$config, winslash = "/", mustWork = TRUE)),
  sprintf("Output TeX: %s", normalizePath(args$out_tex, winslash = "/", mustWork = TRUE)),
  sprintf("Output CSV: %s", normalizePath(args$out_csv, winslash = "/", mustWork = TRUE)),
  sprintf("Run tag: %s", config$run_tag),
  sprintf("Campaign id: %s", config$campaign_id),
  sprintf("Validation worktree: %s", config$validation_worktree),
  sprintf("Validation branch: %s", config$validation_branch),
  sprintf("Validation commit at export: %s", config$validation_commit_at_export),
  sprintf("Package version: %s", config$package_version),
  sprintf("Source registry root: %s", config$source_registry_root),
  sprintf("Source registry hash name: %s", config$source_registry_hash_name),
  sprintf("Source registry hash value: %s", config$source_registry_hash_value),
  sprintf("Atomic progress SHA-256: %s", config$atomic_progress_sha256),
  sprintf("Root progress SHA-256: %s", config$root_progress_sha256),
  sprintf("Manifest SHA-256: %s", config$manifest_sha256),
  sprintf("Atomic specs: total=%d complete=%d running=%d pending=%d",
          status_table$total[[1]], status_table$complete[[1]],
          status_table$running[[1]], status_table$pending[[1]]),
  sprintf("Root specs: total=%d complete=%d running=%d pending=%d",
          status_table$total[[2]], status_table$complete[[2]],
          status_table$running[[2]], status_table$pending[[2]]),
  sprintf("Manifest article_consumable: %s", manifest$article_consumable),
  sprintf("Manifest is_final: %s", manifest$is_final),
  "Article policy: operational status display only; not a scientific result table."
)

writeLines(manifest_lines, args$out_manifest, useBytes = TRUE)

cat("TT500 provisional manuscript status table: PASS\n")
cat(sprintf("tex: %s\n", normalizePath(args$out_tex, winslash = "/", mustWork = TRUE)))
cat(sprintf("csv: %s\n", normalizePath(args$out_csv, winslash = "/", mustWork = TRUE)))
cat(sprintf("manifest: %s\n", normalizePath(args$out_manifest, winslash = "/", mustWork = TRUE)))
cat(sprintf("atomic_complete: %d/%d\n", status_table$complete[[1]], status_table$total[[1]]))
cat(sprintf("root_complete: %d/%d\n", status_table$complete[[2]], status_table$total[[2]]))
