#!/usr/bin/env Rscript
# Purpose: prepare the minimal full-seven completion for the GloFAS m420
# reservoir-only candidate. The p05/p50/p95 component runs are reused from the
# completed next-candidate gate; only p15/p35/p65/p80 are launched.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/model_contract.R"))
source(app_path("application/R/engine_contract.R"))

args <- app_parse_args(list(
  gate_dir = "local_trackers/runtime_configs/glofas_next_candidate_gate_20260614",
  gate_candidate_dir = "local_trackers/runtime_configs/glofas_next_candidate_gate_20260614/c08_reservoir_only_m420",
  quantile_targets = "application/config/glofas_quantile_targets_dec25_synthesis_20260603.csv",
  out_dir = "local_trackers/runtime_configs/glofas_m420_full7_completion_20260615",
  batch_id = "glofas_m420_full7_completion_20260615",
  first_core = "43"
))

repo_rel <- function(path) app_prefer_repo_relative_path(path)
q_label <- function(qid) gsub("[^A-Za-z0-9]+", "", as.character(qid))

intervals <- list(
  list(lower = 0.05, upper = 0.95, nominal = 0.90),
  list(lower = 0.15, upper = 0.80, nominal = 0.65),
  list(lower = 0.35, upper = 0.65, nominal = 0.30)
)

target_levels <- c(0.05, 0.15, 0.35, 0.50, 0.65, 0.80, 0.95)
reuse_levels <- c(0.05, 0.50, 0.95)
launch_levels <- setdiff(target_levels, reuse_levels)

targets <- app_validate_quantile_grid(app_path(args$quantile_targets))
targets <- targets[round(as.numeric(targets$quantile_level), 8) %in% target_levels, , drop = FALSE]
targets <- targets[order(as.numeric(targets$quantile_level)), , drop = FALSE]
if (!identical(round(as.numeric(targets$quantile_level), 8), target_levels)) {
  stop("Quantile target file must contain p05, p15, p35, p50, p65, p80, and p95.", call. = FALSE)
}

out_dir <- app_path(args$out_dir)
app_ensure_dir(out_dir)

gate_cand_dir <- app_path(args$gate_candidate_dir)
base_cfg <- app_read_config(file.path(gate_cand_dir, "config_p50.yaml"))
base_cfg$.__config_path__ <- NULL
base_grid <- app_validate_model_grid(file.path(gate_cand_dir, "model_grid_p50.csv"), app_config_path(base_cfg, "schema"))
raw_base <- base_grid[base_grid$model_family == "raw_glofas", , drop = FALSE][1L, , drop = FALSE]
qdesn_base <- base_grid[base_grid$model_family == "qdesn_glofas_discrepancy", , drop = FALSE][1L, , drop = FALSE]
if (!nrow(raw_base) || !nrow(qdesn_base)) {
  stop("The m420 gate model grid must contain one raw_glofas row and one qdesn_glofas_discrepancy row.", call. = FALSE)
}

raw_model_id <- raw_base$model_id[[1L]]
qdesn_model_id <- qdesn_base$model_id[[1L]]

health_path <- file.path(app_path(args$gate_dir), "health_check_latest.csv")
if (!file.exists(health_path)) {
  stop(sprintf("Missing completed gate health file: %s", health_path), call. = FALSE)
}
gate_health <- app_read_csv(health_path)
gate_health <- gate_health[gate_health$candidate_id == "c08", , drop = FALSE]
if (nrow(gate_health) != 3L || !all(gate_health$status == "complete_scored")) {
  stop("Expected exactly three completed c08 gate rows for p05, p50, and p95.", call. = FALSE)
}

requested_cores <- as.integer(args$first_core) + seq_along(launch_levels) - 1L
n_cores <- parallel::detectCores(logical = TRUE)
if (any(requested_cores < 0L | requested_cores >= n_cores)) {
  stop(sprintf("Requested core range is invalid for %d detected cores: %s", n_cores, paste(requested_cores, collapse = ", ")), call. = FALSE)
}

component_rows <- vector("list", nrow(targets))
launch_manifest_rows <- list()
model_rows_all <- list()
qgrid_rows_all <- list()

launch_lines <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "export NUMEXPR_NUM_THREADS=1",
  "",
  "# Generated by application/scripts/33_prepare_glofas_m420_full7_completion_20260615.R.",
  "# Minimal m420 full-seven completion: p05/p50/p95 are reused from the completed gate;",
  "# p15/p35/p65/p80 are launched here.",
  ""
)

for (i in seq_len(nrow(targets))) {
  qid <- q_label(targets$quantile_id[[i]])
  qlev <- as.numeric(targets$quantile_level[[i]])
  role <- as.character(targets$role[[i]])
  is_reused <- any(abs(qlev - reuse_levels) < 1e-12)

  if (is_reused) {
    gate_row <- gate_health[abs(as.numeric(gate_health$quantile_level) - qlev) < 1e-12, , drop = FALSE]
    if (nrow(gate_row) != 1L) stop(sprintf("Missing reusable c08 gate row for quantile %s.", qlev), call. = FALSE)
    src_config <- file.path(gate_cand_dir, sprintf("config_%s.yaml", qid))
    src_qgrid <- file.path(gate_cand_dir, sprintf("quantile_grid_%s.csv", qid))
    src_model_grid <- file.path(gate_cand_dir, sprintf("model_grid_%s.csv", qid))
    raw_fit_id <- sprintf("raw_glofas_glofas_next_candidate_gate_20260614_c08_reservoir_only_m420_%s", qid)
    qdesn_fit_id <- sprintf("qdesn_latent_path_rhs_al_vb_glofas_next_candidate_gate_20260614_c08_reservoir_only_m420_%s", qid)
    component_rows[[i]] <- data.frame(
      batch_id = args$batch_id,
      run_index = i,
      quantile_id = qid,
      quantile_level = qlev,
      role = role,
      run_id = gate_row$run_id[[1L]],
      config_path = repo_rel(src_config),
      quantile_grid_path = repo_rel(src_qgrid),
      model_grid_path = repo_rel(src_model_grid),
      run_dir = file.path("application/runs", gate_row$run_id[[1L]]),
      raw_fit_id = raw_fit_id,
      qdesn_fit_id = qdesn_fit_id,
      raw_model_id = raw_model_id,
      qdesn_model_id = qdesn_model_id,
      source_kind = "reused_completed_gate_c08",
      required = TRUE,
      enabled = TRUE,
      stringsAsFactors = FALSE
    )
    model_rows_all[[length(model_rows_all) + 1L]] <- app_validate_model_grid(src_model_grid, app_config_path(base_cfg, "schema"))
    qgrid_rows_all[[length(qgrid_rows_all) + 1L]] <- app_read_csv(src_qgrid)
    next
  }

  run_id <- sprintf("%s_%s", args$batch_id, qid)
  qgrid_path <- file.path(out_dir, sprintf("quantile_grid_%s.csv", qid))
  model_grid_path <- file.path(out_dir, sprintf("model_grid_%s.csv", qid))
  config_path <- file.path(out_dir, sprintf("config_%s.yaml", qid))
  app_write_csv(targets[i, , drop = FALSE], qgrid_path)

  raw_row <- raw_base
  qdesn_row <- qdesn_base
  raw_row$fit_id <- sprintf("raw_glofas_glofas_next_candidate_gate_20260614_c08_reservoir_only_m420_%s", qid)
  raw_row$model_id <- raw_model_id
  raw_row$quantile_level <- qlev
  raw_row$config_hash <- "TO_BE_COMPUTED"
  raw_row$notes <- sprintf("Raw GloFAS baseline for m420 full-seven completion; quantile=%s (%s).", qlev, role)
  qdesn_row$fit_id <- sprintf("qdesn_latent_path_rhs_al_vb_glofas_next_candidate_gate_20260614_c08_reservoir_only_m420_%s", qid)
  qdesn_row$model_id <- qdesn_model_id
  qdesn_row$quantile_level <- qlev
  qdesn_row$reservoir_seed <- app_config_reservoir_seed(base_cfg)
  qdesn_row$config_hash <- "TO_BE_COMPUTED"
  qdesn_row$notes <- sprintf("Q-DESN m420 full-seven completion component; quantile=%s (%s).", qlev, role)
  model_grid <- rbind(raw_row, qdesn_row)
  app_write_csv(model_grid, model_grid_path)
  app_validate_qdesn_seed_contract(base_cfg, app_validate_model_grid(model_grid_path, app_config_path(base_cfg, "schema")))

  cfg <- base_cfg
  cfg$application_name <- run_id
  cfg$description <- paste(
    "Minimal m420 full-seven GloFAS Q-DESN completion component.",
    sprintf("Quantile %s (%s).", qlev, role),
    "p05/p50/p95 are reused from the completed c08 next-candidate gate."
  )
  cfg$paths$quantile_grid <- repo_rel(qgrid_path)
  cfg$paths$model_grid <- repo_rel(model_grid_path)
  cfg$paths$cache <- file.path("application/cache", run_id)
  cfg$scoring$intervals <- intervals
  cfg$execution$final_launch$enabled <- TRUE
  cfg$execution$final_launch$note <- "User-approved m420 full-seven completion component; synthesize after missing quantiles complete."
  cfg$post_analysis$run_after_outputs <- FALSE
  app_write_yaml(cfg, config_path)

  core <- requested_cores[[match(qlev, launch_levels)]]
  session <- sprintf("%s_%s", args$batch_id, qid)
  log_path <- file.path("application/logs", sprintf("%s.log", run_id))
  command <- sprintf(
    "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
    core,
    repo_rel(config_path),
    run_id,
    log_path
  )
  launch_lines <- c(
    launch_lines,
    sprintf("# %s: %s", qid, role),
    sprintf("if tmux has-session -t %s 2>/dev/null; then echo 'Session exists: %s' >&2; exit 1; fi", shQuote(session), session),
    sprintf("tmux new-session -d -s %s %s", shQuote(session), shQuote(command)),
    ""
  )

  launch_manifest_rows[[length(launch_manifest_rows) + 1L]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    core = core,
    raw_fit_id = raw_row$fit_id,
    qdesn_fit_id = qdesn_row$fit_id,
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    log_path = log_path,
    launch_status = "prepared_not_launched",
    stringsAsFactors = FALSE
  )
  component_rows[[i]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    run_dir = file.path("application/runs", run_id),
    raw_fit_id = raw_row$fit_id,
    qdesn_fit_id = qdesn_row$fit_id,
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    source_kind = "new_completion_run",
    required = TRUE,
    enabled = TRUE,
    stringsAsFactors = FALSE
  )
  model_rows_all[[length(model_rows_all) + 1L]] <- model_grid
  qgrid_rows_all[[length(qgrid_rows_all) + 1L]] <- targets[i, , drop = FALSE]
}

source_manifest <- do.call(rbind, component_rows)
source_manifest <- source_manifest[order(source_manifest$run_index), , drop = FALSE]
launch_manifest <- if (length(launch_manifest_rows)) do.call(rbind, launch_manifest_rows) else data.frame()
app_write_csv(source_manifest, file.path(out_dir, "synthesis_source_manifest.csv"))
app_write_csv(source_manifest, file.path(out_dir, "component_manifest.csv"))
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
app_write_csv(do.call(rbind, qgrid_rows_all)[order(do.call(rbind, qgrid_rows_all)$quantile_level), , drop = FALSE], file.path(out_dir, "quantile_grid_all.csv"))
app_write_csv(do.call(rbind, model_rows_all), file.path(out_dir, "model_grid_all.csv"))

synthesis_cfg <- base_cfg
synthesis_cfg$application_name <- paste0(args$batch_id, "_synthesis")
synthesis_cfg$description <- "Post-hoc synthesis and scoring config for the m420 full-seven GloFAS Q-DESN completion."
synthesis_cfg$paths$quantile_grid <- repo_rel(file.path(out_dir, "quantile_grid_all.csv"))
synthesis_cfg$paths$model_grid <- repo_rel(file.path(out_dir, "model_grid_all.csv"))
synthesis_cfg$paths$cache <- file.path("application/cache", paste0(args$batch_id, "_synthesis"))
synthesis_cfg$scoring$intervals <- intervals
synthesis_cfg$execution$final_launch$enabled <- FALSE
synthesis_cfg$execution$final_launch$note <- "Synthesis-only config; consumes reused c08 gate runs plus completed m420 missing-quantile runs."
synthesis_cfg$post_analysis$run_after_outputs <- FALSE
app_write_yaml(synthesis_cfg, file.path(out_dir, "synthesis_config.yaml"))

launch_path <- file.path(out_dir, sprintf("launch_missing_%s.sh", args$batch_id))
writeLines(launch_lines, launch_path)
Sys.chmod(launch_path, "0755")

synth_path <- file.path(out_dir, sprintf("synthesize_%s.sh", args$batch_id))
writeLines(c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  sprintf(
    "Rscript application/scripts/10_synthesize_glofas_quantile_runs.R --config %s --source_manifest %s --run_id %s_synthesis_final",
    repo_rel(file.path(out_dir, "synthesis_config.yaml")),
    repo_rel(file.path(out_dir, "synthesis_source_manifest.csv")),
    args$batch_id
  )
), synth_path)
Sys.chmod(synth_path, "0755")

watch_path <- file.path(out_dir, sprintf("watch_and_synthesize_%s.sh", args$batch_id))
writeLines(c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  sprintf("manifest=%s", shQuote(repo_rel(file.path(out_dir, "synthesis_source_manifest.csv")))),
  sprintf("synth=%s", shQuote(repo_rel(synth_path))),
  sprintf("log=%s", shQuote(file.path("application/logs", sprintf("%s_synthesis_watch.log", args$batch_id)))),
  "echo \"watch_started=$(date -Is)\" >> \"$log\"",
  "while true; do",
  "  missing=$(Rscript - \"$manifest\" <<'RS'",
  "args <- commandArgs(trailingOnly = TRUE)",
  "m <- read.csv(args[[1]], stringsAsFactors = FALSE)",
  "missing <- character()",
  "for (i in seq_len(nrow(m))) {",
  "  status_path <- file.path(m$run_dir[[i]], 'tables', 'fit_status.csv')",
  "  pred_path <- file.path(m$run_dir[[i]], 'tables', 'prediction_quantiles.csv')",
  "  if (!file.exists(status_path) || !file.exists(pred_path)) {",
  "    missing <- c(missing, m$run_id[[i]])",
  "    next",
  "  }",
  "  s <- read.csv(status_path, stringsAsFactors = FALSE)",
  "  ids <- c(m$raw_fit_id[[i]], m$qdesn_fit_id[[i]])",
  "  rows <- s[s$fit_id %in% ids, , drop = FALSE]",
  "  if (nrow(rows) != length(ids) || any(rows$status != 'completed')) missing <- c(missing, m$run_id[[i]])",
  "}",
  "cat(paste(missing, collapse = ','))",
  "RS",
  "  )",
  "  if [ -z \"$missing\" ]; then",
  "    echo \"all_sources_ready=$(date -Is)\" >> \"$log\"",
  "    bash \"$synth\" >> \"$log\" 2>&1",
  "    echo \"synthesis_finished=$(date -Is)\" >> \"$log\"",
  "    exit 0",
  "  fi",
  "  echo \"waiting=$(date -Is) missing=$missing\" >> \"$log\"",
  "  sleep 600",
  "done"
), watch_path)
Sys.chmod(watch_path, "0755")

prelaunch <- data.frame(
  check = c(
    "reused_gate_quantiles_complete",
    "missing_quantile_configs_prepared",
    "all_source_model_ids_consistent",
    "launch_core_range_valid",
    "synthesis_manifest_rows"
  ),
  passed = c(
    all(source_manifest$source_kind[source_manifest$quantile_level %in% reuse_levels] == "reused_completed_gate_c08"),
    all(launch_levels %in% launch_manifest$quantile_level),
    length(unique(source_manifest$qdesn_model_id)) == 1L && length(unique(source_manifest$raw_model_id)) == 1L,
    all(requested_cores >= 0L & requested_cores < n_cores),
    nrow(source_manifest) == length(target_levels)
  ),
  detail = c(
    paste(source_manifest$quantile_id[source_manifest$source_kind == "reused_completed_gate_c08"], collapse = ", "),
    paste(launch_manifest$quantile_id, collapse = ", "),
    paste(unique(source_manifest$qdesn_model_id), collapse = ", "),
    paste(requested_cores, collapse = ", "),
    as.character(nrow(source_manifest))
  ),
  stringsAsFactors = FALSE
)
app_write_csv(prelaunch, file.path(out_dir, "prelaunch_validation.csv"))
if (!all(prelaunch$passed)) {
  stop("Prelaunch validation failed; see prelaunch_validation.csv.", call. = FALSE)
}

writeLines(c(
  sprintf("# GloFAS m420 Full-Seven Completion: %s", args$batch_id),
  "",
  "Prepared locally and ignored by git.",
  "",
  "Purpose:",
  "- Test whether the p05/p50/p95 m420 gate winner beats the current m360 full-seven baseline after full-seven synthesis.",
  "- Reuse completed c08 p05, p50, and p95 gate runs.",
  "- Launch only p15, p35, p65, and p80.",
  "",
  "Current authoritative baseline:",
  "`application/runs/glofas_reservoir_only_m360_full7_20260607_synthesis_final`",
  "",
  "Launch missing quantiles:",
  sprintf("`bash %s`", repo_rel(launch_path)),
  "",
  "Watch and synthesize when ready:",
  sprintf("`tmux new-session -d -s %s_synthesis_watch %s`", args$batch_id, shQuote(sprintf("bash %s", repo_rel(watch_path)))),
  "",
  "Manual synthesis:",
  sprintf("`bash %s`", repo_rel(synth_path)),
  "",
  "Decision rule:",
  "- Promote m420 only if the full-seven synthesis beats the m360 baseline on CRPS and mean check loss without unacceptable crossing or low-tail degradation."
), file.path(out_dir, "README.md"))

cat(repo_rel(file.path(out_dir, "launch_manifest.csv")), "\n")
cat(sprintf("prepared_missing_quantiles=%d reused_quantiles=%d\n", nrow(launch_manifest), sum(source_manifest$source_kind == "reused_completed_gate_c08")))
