#!/usr/bin/env Rscript
# Purpose: prepare a full-seven GloFAS completion package for a completed
# p05/p50/p95 discrepancy-smoothing gate candidate. The completed gate rows are
# reused; only p15/p35/p65/p80 are launched.

repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), "..", ".."), mustWork = TRUE)
source(file.path(repo_root, "application/R/00_packages.R"))
app_set_repo_root(repo_root)
source(app_path("application/R/input_contract.R"))
source(app_path("application/R/model_contract.R"))
source(app_path("application/R/engine_contract.R"))

args <- app_parse_args(list(
  gate_dir = "local_trackers/runtime_configs/glofas_discrepancy_smoothing_gate_20260616",
  gate_candidate_dir = "local_trackers/runtime_configs/glofas_discrepancy_smoothing_gate_20260616/c03_m420_alpha010_tau_current",
  candidate_id = "c03",
  quantile_targets = "application/config/glofas_quantile_targets_dec25_synthesis_20260603.csv",
  out_dir = "local_trackers/runtime_configs/glofas_c03_alpha010_full7_completion_20260616",
  batch_id = "glofas_c03_alpha010_full7_completion_20260616",
  first_core = "43"
))

repo_rel <- function(path) app_prefer_repo_relative_path(path)
q_label <- function(qid) gsub("[^A-Za-z0-9]+", "", as.character(qid))

intervals <- list(
  list(lower = 0.05, upper = 0.95, nominal = 0.90),
  list(lower = 0.15, upper = 0.80, nominal = 0.65),
  list(lower = 0.35, upper = 0.65, nominal = 0.30)
)
target_levels <- c(0.05, 0.15, 0.35, 0.50, 0.65, 0.80, 0.95)
reuse_levels <- c(0.05, 0.50, 0.95)
launch_levels <- setdiff(target_levels, reuse_levels)

targets <- app_validate_quantile_grid(app_path(args$quantile_targets))
targets <- targets[round(as.numeric(targets$quantile_level), 8) %in% target_levels, , drop = FALSE]
targets <- targets[order(as.numeric(targets$quantile_level)), , drop = FALSE]
if (!identical(round(as.numeric(targets$quantile_level), 8), target_levels)) {
  stop("Quantile target file must contain p05, p15, p35, p50, p65, p80, and p95.", call. = FALSE)
}

out_dir <- app_path(args$out_dir)
app_ensure_dir(out_dir)
gate_dir <- app_path(args$gate_dir)
gate_cand_dir <- app_path(args$gate_candidate_dir)
base_cfg_path <- file.path(gate_cand_dir, "config_p50.yaml")
base_grid_path <- file.path(gate_cand_dir, "model_grid_p50.csv")
base_cfg <- app_read_config(base_cfg_path)
base_cfg$.__config_path__ <- NULL
base_grid <- app_validate_model_grid(base_grid_path, app_config_path(base_cfg, "schema"))
raw_base <- base_grid[base_grid$model_family == "raw_glofas", , drop = FALSE][1L, , drop = FALSE]
qdesn_base <- base_grid[base_grid$model_family == "qdesn_glofas_discrepancy", , drop = FALSE][1L, , drop = FALSE]
if (!nrow(raw_base) || !nrow(qdesn_base)) {
  stop("Gate model grid must contain one raw_glofas row and one qdesn_glofas_discrepancy row.", call. = FALSE)
}

raw_model_id <- raw_base$model_id[[1L]]
qdesn_model_id <- qdesn_base$model_id[[1L]]
health_path <- file.path(gate_dir, "health_check_latest.csv")
if (!file.exists(health_path)) stop(sprintf("Missing gate health file: %s", health_path), call. = FALSE)
gate_health <- app_read_csv(health_path)
gate_health <- gate_health[gate_health$candidate_id == args$candidate_id, , drop = FALSE]
gate_health$quantile_level <- as.numeric(gate_health$quantile_level)
if (nrow(gate_health) != 3L || !all(gate_health$status == "complete_scored")) {
  stop(sprintf("Expected exactly three completed gate rows for candidate %s.", args$candidate_id), call. = FALSE)
}

requested_cores <- as.integer(args$first_core) + seq_along(launch_levels) - 1L
n_cores <- parallel::detectCores(logical = TRUE)
if (any(requested_cores < 0L | requested_cores >= n_cores)) {
  stop(sprintf("Requested core range is invalid for %d detected cores: %s", n_cores, paste(requested_cores, collapse = ", ")), call. = FALSE)
}

component_rows <- vector("list", nrow(targets))
launch_manifest_rows <- list()
model_rows_all <- list()
qgrid_rows_all <- list()

launch_lines <- c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  "export OMP_NUM_THREADS=1",
  "export OPENBLAS_NUM_THREADS=1",
  "export MKL_NUM_THREADS=1",
  "export VECLIB_MAXIMUM_THREADS=1",
  "export NUMEXPR_NUM_THREADS=1",
  "",
  "# Generated by application/scripts/38_prepare_glofas_gate_candidate_full7_completion_20260616.R.",
  "# p05/p50/p95 are reused from a completed discrepancy-smoothing gate;",
  "# p15/p35/p65/p80 are launched here.",
  ""
)

for (i in seq_len(nrow(targets))) {
  qid <- q_label(targets$quantile_id[[i]])
  qlev <- as.numeric(targets$quantile_level[[i]])
  role <- as.character(targets$role[[i]])
  is_reused <- any(abs(qlev - reuse_levels) < 1e-12)

  if (is_reused) {
    gate_row <- gate_health[abs(gate_health$quantile_level - qlev) < 1e-12, , drop = FALSE]
    if (nrow(gate_row) != 1L) stop(sprintf("Missing reusable gate row for quantile %s.", qlev), call. = FALSE)
    src_qgrid <- file.path(gate_cand_dir, sprintf("quantile_grid_%s.csv", qid))
    src_model_grid <- file.path(gate_cand_dir, sprintf("model_grid_%s.csv", qid))
    src_grid <- app_validate_model_grid(src_model_grid, app_config_path(base_cfg, "schema"))
    raw_fit_id <- src_grid$fit_id[src_grid$model_family == "raw_glofas"][[1L]]
    qdesn_fit_id <- src_grid$fit_id[src_grid$model_family == "qdesn_glofas_discrepancy"][[1L]]
    component_rows[[i]] <- data.frame(
      batch_id = args$batch_id,
      run_index = i,
      quantile_id = qid,
      quantile_level = qlev,
      role = role,
      run_id = gate_row$run_id[[1L]],
      config_path = repo_rel(file.path(gate_cand_dir, sprintf("config_%s.yaml", qid))),
      quantile_grid_path = repo_rel(src_qgrid),
      model_grid_path = repo_rel(src_model_grid),
      run_dir = file.path("application/runs", gate_row$run_id[[1L]]),
      raw_fit_id = raw_fit_id,
      qdesn_fit_id = qdesn_fit_id,
      raw_model_id = raw_model_id,
      qdesn_model_id = qdesn_model_id,
      source_kind = paste0("reused_completed_gate_", args$candidate_id),
      required = TRUE,
      enabled = TRUE,
      stringsAsFactors = FALSE
    )
    model_rows_all[[length(model_rows_all) + 1L]] <- src_grid
    qgrid_rows_all[[length(qgrid_rows_all) + 1L]] <- app_read_csv(src_qgrid)
    next
  }

  run_id <- sprintf("%s_%s", args$batch_id, qid)
  qgrid_path <- file.path(out_dir, sprintf("quantile_grid_%s.csv", qid))
  model_grid_path <- file.path(out_dir, sprintf("model_grid_%s.csv", qid))
  config_path <- file.path(out_dir, sprintf("config_%s.yaml", qid))
  app_write_csv(targets[i, , drop = FALSE], qgrid_path)

  raw_row <- raw_base
  qdesn_row <- qdesn_base
  raw_row$fit_id <- sprintf("%s_%s", raw_model_id, qid)
  raw_row$quantile_level <- qlev
  raw_row$config_hash <- "TO_BE_COMPUTED"
  raw_row$notes <- sprintf("Raw GloFAS baseline for %s; quantile=%s (%s).", args$batch_id, qlev, role)
  qdesn_row$fit_id <- sprintf("%s_%s", qdesn_model_id, qid)
  qdesn_row$quantile_level <- qlev
  qdesn_row$reservoir_seed <- app_config_reservoir_seed(base_cfg)
  qdesn_row$config_hash <- "TO_BE_COMPUTED"
  qdesn_row$notes <- sprintf("Q-DESN full-seven completion component for %s; quantile=%s (%s).", args$batch_id, qlev, role)
  model_grid <- rbind(raw_row, qdesn_row)
  app_write_csv(model_grid, model_grid_path)
  app_validate_qdesn_seed_contract(base_cfg, app_validate_model_grid(model_grid_path, app_config_path(base_cfg, "schema")))

  cfg <- base_cfg
  cfg$application_name <- run_id
  cfg$description <- paste(
    sprintf("Full-seven GloFAS completion component for gate candidate %s.", args$candidate_id),
    sprintf("Quantile %s (%s).", qlev, role),
    "p05/p50/p95 are reused from the completed discrepancy-smoothing gate."
  )
  cfg$paths$quantile_grid <- repo_rel(qgrid_path)
  cfg$paths$model_grid <- repo_rel(model_grid_path)
  cfg$paths$cache <- file.path("application/cache", run_id)
  cfg$scoring$intervals <- intervals
  cfg$execution$final_launch$enabled <- TRUE
  cfg$execution$final_launch$note <- sprintf("User-approved full-seven completion component for gate candidate %s.", args$candidate_id)
  cfg$post_analysis$run_after_outputs <- FALSE
  app_write_yaml(cfg, config_path)

  core <- requested_cores[[match(qlev, launch_levels)]]
  session <- sprintf("%s_%s", args$batch_id, qid)
  log_path <- file.path("application/logs", sprintf("%s.log", run_id))
  command <- sprintf(
    "taskset -c %d Rscript application/scripts/run_all.R --config %s --run_id %s --preflight true --confirm_final_launch true > %s 2>&1",
    core,
    repo_rel(config_path),
    run_id,
    log_path
  )
  launch_lines <- c(
    launch_lines,
    sprintf("# %s: %s", qid, role),
    sprintf("if tmux has-session -t %s 2>/dev/null; then echo 'Session exists: %s' >&2; exit 1; fi", shQuote(session), session),
    sprintf("if [ -e %s ]; then echo 'Run dir exists: application/runs/%s' >&2; exit 1; fi", shQuote(file.path("application/runs", run_id)), run_id),
    sprintf("tmux new-session -d -s %s %s", shQuote(session), shQuote(command)),
    ""
  )

  launch_manifest_rows[[length(launch_manifest_rows) + 1L]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    core = core,
    raw_fit_id = raw_row$fit_id,
    qdesn_fit_id = qdesn_row$fit_id,
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    log_path = log_path,
    launch_status = "prepared_not_launched",
    stringsAsFactors = FALSE
  )
  component_rows[[i]] <- data.frame(
    batch_id = args$batch_id,
    run_index = i,
    quantile_id = qid,
    quantile_level = qlev,
    role = role,
    run_id = run_id,
    config_path = repo_rel(config_path),
    quantile_grid_path = repo_rel(qgrid_path),
    model_grid_path = repo_rel(model_grid_path),
    run_dir = file.path("application/runs", run_id),
    raw_fit_id = raw_row$fit_id,
    qdesn_fit_id = qdesn_row$fit_id,
    raw_model_id = raw_model_id,
    qdesn_model_id = qdesn_model_id,
    source_kind = "new_completion_run",
    required = TRUE,
    enabled = TRUE,
    stringsAsFactors = FALSE
  )
  model_rows_all[[length(model_rows_all) + 1L]] <- model_grid
  qgrid_rows_all[[length(qgrid_rows_all) + 1L]] <- targets[i, , drop = FALSE]
}

source_manifest <- do.call(rbind, component_rows)
source_manifest <- source_manifest[order(source_manifest$run_index), , drop = FALSE]
launch_manifest <- if (length(launch_manifest_rows)) do.call(rbind, launch_manifest_rows) else data.frame()
qgrid_all <- do.call(rbind, qgrid_rows_all)
qgrid_all <- qgrid_all[order(as.numeric(qgrid_all$quantile_level)), , drop = FALSE]
app_write_csv(source_manifest, file.path(out_dir, "synthesis_source_manifest.csv"))
app_write_csv(source_manifest, file.path(out_dir, "component_manifest.csv"))
app_write_csv(launch_manifest, file.path(out_dir, "launch_manifest.csv"))
app_write_csv(qgrid_all, file.path(out_dir, "quantile_grid_all.csv"))
app_write_csv(do.call(rbind, model_rows_all), file.path(out_dir, "model_grid_all.csv"))

synthesis_cfg <- base_cfg
synthesis_cfg$application_name <- paste0(args$batch_id, "_synthesis")
synthesis_cfg$description <- sprintf("Post-hoc synthesis and scoring config for full-seven candidate %s.", args$candidate_id)
synthesis_cfg$paths$quantile_grid <- repo_rel(file.path(out_dir, "quantile_grid_all.csv"))
synthesis_cfg$paths$model_grid <- repo_rel(file.path(out_dir, "model_grid_all.csv"))
synthesis_cfg$paths$cache <- file.path("application/cache", paste0(args$batch_id, "_synthesis"))
synthesis_cfg$scoring$intervals <- intervals
synthesis_cfg$execution$final_launch$enabled <- FALSE
synthesis_cfg$execution$final_launch$note <- sprintf("Synthesis-only config; consumes reused %s gate runs plus missing-quantile completion runs.", args$candidate_id)
synthesis_cfg$post_analysis$run_after_outputs <- FALSE
app_write_yaml(synthesis_cfg, file.path(out_dir, "synthesis_config.yaml"))

launch_path <- file.path(out_dir, sprintf("launch_missing_%s.sh", args$batch_id))
writeLines(launch_lines, launch_path)
Sys.chmod(launch_path, "0755")

synth_path <- file.path(out_dir, sprintf("synthesize_%s.sh", args$batch_id))
writeLines(c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  sprintf(
    "Rscript application/scripts/10_synthesize_glofas_quantile_runs.R --config %s --source_manifest %s --run_id %s_synthesis_final",
    repo_rel(file.path(out_dir, "synthesis_config.yaml")),
    repo_rel(file.path(out_dir, "synthesis_source_manifest.csv")),
    args$batch_id
  )
), synth_path)
Sys.chmod(synth_path, "0755")

watch_path <- file.path(out_dir, sprintf("watch_and_synthesize_%s.sh", args$batch_id))
writeLines(c(
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  sprintf("cd %s", shQuote(app_repo_root())),
  sprintf("manifest=%s", shQuote(repo_rel(file.path(out_dir, "synthesis_source_manifest.csv")))),
  sprintf("synth=%s", shQuote(repo_rel(synth_path))),
  sprintf("log=%s", shQuote(file.path("application/logs", sprintf("%s_synthesis_watch.log", args$batch_id)))),
  "echo \"watch_started=$(date -Is)\" >> \"$log\"",
  "while true; do",
  "  missing=$(Rscript - \"$manifest\" <<'RS'",
  "args <- commandArgs(trailingOnly = TRUE)",
  "m <- read.csv(args[[1]], stringsAsFactors = FALSE)",
  "missing <- character()",
  "for (i in seq_len(nrow(m))) {",
  "  status_path <- file.path(m$run_dir[[i]], 'tables', 'fit_status.csv')",
  "  pred_path <- file.path(m$run_dir[[i]], 'tables', 'prediction_quantiles.csv')",
  "  if (!file.exists(status_path) || !file.exists(pred_path)) {",
  "    missing <- c(missing, m$run_id[[i]])",
  "    next",
  "  }",
  "  s <- read.csv(status_path, stringsAsFactors = FALSE)",
  "  ids <- c(m$raw_fit_id[[i]], m$qdesn_fit_id[[i]])",
  "  rows <- s[s$fit_id %in% ids, , drop = FALSE]",
  "  if (nrow(rows) != length(ids) || any(rows$status != 'completed')) missing <- c(missing, m$run_id[[i]])",
  "}",
  "cat(paste(missing, collapse = ','))",
  "RS",
  "  )",
  "  if [ -z \"$missing\" ]; then",
  "    echo \"all_sources_ready=$(date -Is)\" >> \"$log\"",
  "    bash \"$synth\" >> \"$log\" 2>&1",
  "    echo \"synthesis_finished=$(date -Is)\" >> \"$log\"",
  "    exit 0",
  "  fi",
  "  echo \"waiting=$(date -Is) missing=$missing\" >> \"$log\"",
  "  sleep 600",
  "done"
), watch_path)
Sys.chmod(watch_path, "0755")

prelaunch <- data.frame(
  check = c(
    "reused_gate_quantiles_complete",
    "missing_quantile_configs_prepared",
    "all_source_model_ids_consistent",
    "launch_core_range_valid",
    "synthesis_manifest_rows",
    "new_run_dirs_absent"
  ),
  passed = c(
    all(source_manifest$source_kind[source_manifest$quantile_level %in% reuse_levels] == paste0("reused_completed_gate_", args$candidate_id)),
    all(launch_levels %in% launch_manifest$quantile_level),
    length(unique(source_manifest$qdesn_model_id)) == 1L && length(unique(source_manifest$raw_model_id)) == 1L,
    all(requested_cores >= 0L & requested_cores < n_cores),
    nrow(source_manifest) == length(target_levels),
    !any(dir.exists(file.path(app_path("application/runs"), launch_manifest$run_id)))
  ),
  detail = c(
    paste(source_manifest$quantile_id[source_manifest$source_kind == paste0("reused_completed_gate_", args$candidate_id)], collapse = ", "),
    paste(launch_manifest$quantile_id, collapse = ", "),
    paste(unique(source_manifest$qdesn_model_id), collapse = ", "),
    paste(requested_cores, collapse = ", "),
    as.character(nrow(source_manifest)),
    paste(launch_manifest$run_id, collapse = ", ")
  ),
  stringsAsFactors = FALSE
)
app_write_csv(prelaunch, file.path(out_dir, "prelaunch_validation.csv"))
if (!all(prelaunch$passed)) stop("Prelaunch validation failed; see prelaunch_validation.csv.", call. = FALSE)

writeLines(c(
  sprintf("# GloFAS Full-Seven Completion: %s", args$batch_id),
  "",
  "Prepared locally and ignored by git.",
  "",
  "Purpose:",
  sprintf("- Expand completed gate candidate `%s` to seven quantiles.", args$candidate_id),
  "- Reuse p05, p50, and p95 from the completed discrepancy-smoothing gate.",
  "- Launch only p15, p35, p65, and p80.",
  "",
  "Launch missing quantiles:",
  sprintf("`bash %s`", repo_rel(launch_path)),
  "",
  "Watch and synthesize when ready:",
  sprintf("`tmux new-session -d -s %s_synthesis_watch %s`", args$batch_id, shQuote(sprintf("bash %s", repo_rel(watch_path)))),
  "",
  "Manual synthesis:",
  sprintf("`bash %s`", repo_rel(synth_path)),
  "",
  "Health:",
  sprintf("`Rscript application/scripts/34_summarize_glofas_m420_full7_completion_20260615.R --runtime_dir %s --batch_id %s --baseline_run_id glofas_m420_full7_completion_20260615_synthesis_final`", repo_rel(out_dir), args$batch_id),
  "",
  "Decision rule:",
  "- Promote only if the full-seven synthesis improves over the current m420 full-seven candidate on CRPS and mean check loss without unacceptable synthesis correction."
), file.path(out_dir, "README.md"))

cat(repo_rel(file.path(out_dir, "launch_manifest.csv")), "\n")
cat(sprintf("prepared_missing_quantiles=%d reused_quantiles=%d\n", nrow(launch_manifest), sum(source_manifest$source_kind == paste0("reused_completed_gate_", args$candidate_id))))
