# Article-facing assets for the joint QDESN simulation study.

app_joint_qdesn_article_default_out_dir <- function() {
  app_path("application/cache/joint_qdesn_article_validation_assets_phase110_20260707")
}

app_joint_qdesn_article_default_figures_dir <- function() {
  app_path("figures/joint_qdesn_simulation")
}

app_joint_qdesn_article_default_tables_dir <- function() {
  app_path("tables")
}

app_joint_qdesn_article_label <- function(x) {
  x <- as.character(x)
  out <- ifelse(x == "JOINT QDESN RHS", "Joint QDESN RHS", x)
  out <- ifelse(out == "QDESN RHS", "Independent QDESN RHS", out)
  out <- ifelse(out == "JOINT exQDESN RHS", "Joint exQDESN RHS", out)
  out <- ifelse(out == "exQDESN RHS", "Independent exQDESN RHS", out)
  out <- ifelse(out == "JOINT QDESN RHS MCMC", "Joint QDESN RHS MCMC", out)
  out
}

app_joint_qdesn_article_scenario_label <- function(x) {
  out <- tools::toTitleCase(gsub("_", " ", as.character(x), fixed = TRUE))
  out <- ifelse(out == "Student T Location Scale", "Student-t Location-Scale", out)
  out <- ifelse(out == "Student t Location Scale", "Student-t Location-Scale", out)
  out <- ifelse(out == "Gaussian Mixture Bridge", "Gaussian-Mixture Bridge", out)
  out
}

app_joint_qdesn_article_family_label <- function(x) {
  out <- tools::toTitleCase(gsub("_", " ", as.character(x), fixed = TRUE))
  out <- ifelse(out %in% c("Student T", "Student t"), "Student-t", out)
  out <- ifelse(out == "Gaussian Mixture", "Gaussian mixture", out)
  out
}

app_joint_qdesn_article_fmt_num <- function(x, digits = 3) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  if (abs(x[[1L]]) >= 1000) return(formatC(x[[1L]], format = "f", digits = 1, big.mark = ","))
  formatC(x[[1L]], format = "f", digits = digits)
}

app_joint_qdesn_article_fmt_int <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  formatC(round(x[[1L]]), format = "d", big.mark = ",")
}

app_joint_qdesn_article_fmt_pair <- function(mae, rmse) {
  sprintf(
    "%s (%s)",
    app_joint_qdesn_article_fmt_num(mae, 3),
    app_joint_qdesn_article_fmt_num(rmse, 3)
  )
}

app_joint_qdesn_article_readout_label <- function(x) {
  x <- as.character(x)
  out <- ifelse(x == "joint", "joint", x)
  out <- ifelse(out == "independent_single_tau", "independent", out)
  out
}

app_joint_qdesn_article_likelihood_label <- function(x) {
  x <- tolower(as.character(x))
  out <- ifelse(x == "al", "AL", x)
  out <- ifelse(out == "exal", "exAL", out)
  out
}

app_joint_qdesn_article_diag_note <- function(x) {
  x <- as.character(x)
  x <- ifelse(x == "all readiness gates passed", "all diagnostics finite", x)
  x <- gsub("VB reached max iterations", "VB initializer reached the iteration budget", x, fixed = TRUE)
  x <- gsub("raw quantiles crossed before contract step", "pre-rearrangement quantiles crossed", x, fixed = TRUE)
  x <- gsub("large monotone adjustment", "monotone adjustment flagged", x, fixed = TRUE)
  x
}

app_joint_qdesn_article_latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

app_joint_qdesn_article_write_csv <- function(x, path) {
  app_ensure_dir(dirname(path))
  utils::write.csv(x, path, row.names = FALSE, na = "")
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_article_write_latex_table <- function(
  x,
  path,
  caption,
  label,
  align = NULL,
  size = "\\small",
  resize = FALSE,
  raw_latex_cols = character()
) {
  app_ensure_dir(dirname(path))
  if (is.null(align)) {
    align <- paste0("@{}", paste(rep("l", ncol(x)), collapse = ""), "@{}")
  }
  body <- lapply(seq_len(nrow(x)), function(ii) {
    cells <- unlist(x[ii, , drop = FALSE], use.names = FALSE)
    is_raw <- names(x) %in% raw_latex_cols
    cells[!is_raw] <- app_joint_qdesn_article_latex_escape(cells[!is_raw])
    paste(cells, collapse = " & ")
  })
  lines <- c(
    "% Generated by application/scripts/110_build_joint_qdesn_article_validation_assets.R.",
    "\\begin{table}[!htbp]",
    "\\centering",
    size
  )
  if (isTRUE(resize)) lines <- c(lines, "\\resizebox{\\textwidth}{!}{%")
  lines <- c(
    lines,
    sprintf("\\begin{tabular}{%s}", align),
    "\\toprule",
    paste(app_joint_qdesn_article_latex_escape(names(x)), collapse = " & "),
    "\\\\",
    "\\midrule",
    paste0(body, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}"
  )
  if (isTRUE(resize)) lines <- c(lines, "}%")
  lines <- c(
    lines,
    sprintf("\\caption{%s}", caption),
    sprintf("\\label{%s}", label),
    "\\end{table}"
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_article_write_wrapper <- function(paths, path) {
  app_ensure_dir(dirname(path))
  rel <- vapply(paths, app_prefer_repo_relative_path, character(1L))
  writeLines(c(
    "% Generated by application/scripts/110_build_joint_qdesn_article_validation_assets.R.",
    "% Joint QDESN article validation tables.",
    sprintf("\\input{%s}", rel)
  ), path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_article_pdf_plot <- function(path, width = 7.2, height = 4.8, expr) {
  app_ensure_dir(dirname(path))
  grDevices::pdf(path, width = width, height = height, useDingbats = FALSE)
  on.exit(grDevices::dev.off(), add = TRUE)
  force(expr)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_article_read_required <- function(dir, file) {
  app_read_csv(file.path(dir, file))
}

app_joint_qdesn_article_source_verification <- function(phase107_dir, phase109_dir) {
  phase107_top <- app_joint_qdesn_phase108_manifest_verify(phase107_dir, "selected_vb_source")
  phase109 <- app_joint_qdesn_phase108_manifest_verify(phase109_dir, "mcmc_reference_source")
  nested_path <- file.path(phase107_dir, "candidate_manifest_verification.csv")
  phase107_nested <- if (file.exists(nested_path)) {
    nested <- app_read_csv(nested_path)
    nested$artifact_label <- "selected_vb_nested"
    nested
  } else {
    data.frame(
      artifact_label = "selected_vb_nested",
      label = "candidate_manifest_verification",
      relative_path = "candidate_manifest_verification.csv",
      status = "fail",
      stringsAsFactors = FALSE
    )
  }
  app_bind_rows_fill(list(phase107_top, phase107_nested, phase109))
}

app_joint_qdesn_article_selected_row <- function(selected) {
  app_check_required_columns(selected, c("candidate_id"), "selected VB recommendation")
  if ("selected" %in% names(selected)) {
    out <- selected[isTRUE(as.logical(selected$selected)), , drop = FALSE]
    if (nrow(out)) return(out[1L, , drop = FALSE])
  }
  selected[1L, , drop = FALSE]
}

app_joint_qdesn_article_filter_selected_candidate <- function(x, candidate_id, table_name) {
  if (!"candidate_id" %in% names(x)) return(x)
  out <- x[x$candidate_id == candidate_id, , drop = FALSE]
  if (!nrow(out)) {
    stop(sprintf("%s has no rows for selected candidate '%s'.", table_name, candidate_id), call. = FALSE)
  }
  out
}

app_joint_qdesn_article_stop_if_bad_sources <- function(source_verification) {
  bad <- source_verification[!source_verification$status %in% "pass", , drop = FALSE]
  if (nrow(bad)) {
    stop(sprintf("Source manifest verification failed for %d rows.", nrow(bad)), call. = FALSE)
  }
  invisible(TRUE)
}

app_joint_qdesn_article_load_sources <- function(phase107_dir, phase109_dir) {
  phase107_dir <- normalizePath(phase107_dir, mustWork = TRUE)
  phase109_dir <- normalizePath(phase109_dir, mustWork = TRUE)
  source_verification <- app_joint_qdesn_article_source_verification(phase107_dir, phase109_dir)
  app_joint_qdesn_article_stop_if_bad_sources(source_verification)
  selected <- app_joint_qdesn_article_read_required(phase107_dir, "selected_spec_recommendation.csv")
  selected <- app_joint_qdesn_article_selected_row(selected)
  selected_candidate_id <- selected$candidate_id[[1L]]
  health <- app_joint_qdesn_article_filter_selected_candidate(
    app_joint_qdesn_article_read_required(phase107_dir, "screening_health_summary.csv"),
    selected_candidate_id,
    "selected VB health summary"
  )
  candidate_registry <- app_joint_qdesn_article_filter_selected_candidate(
    app_joint_qdesn_article_read_required(phase107_dir, "candidate_registry.csv"),
    selected_candidate_id,
    "selected VB candidate registry"
  )
  fit_model <- app_joint_qdesn_article_filter_selected_candidate(
    app_joint_qdesn_article_read_required(phase107_dir, "fit_model_metric_summary.csv"),
    selected_candidate_id,
    "selected VB fit model summary"
  )
  forecast_model <- app_joint_qdesn_article_filter_selected_candidate(
    app_joint_qdesn_article_read_required(phase107_dir, "forecast_model_metric_summary.csv"),
    selected_candidate_id,
    "selected VB forecast model summary"
  )
  fit_scenario <- app_joint_qdesn_article_filter_selected_candidate(
    app_joint_qdesn_article_read_required(phase107_dir, "fit_scenario_metric_summary.csv"),
    selected_candidate_id,
    "selected VB fit scenario summary"
  )
  forecast_scenario <- app_joint_qdesn_article_filter_selected_candidate(
    app_joint_qdesn_article_read_required(phase107_dir, "forecast_scenario_metric_summary.csv"),
    selected_candidate_id,
    "selected VB forecast scenario summary"
  )
  forecast_tau <- app_read_csv(file.path(phase107_dir, "forecast_tau_metric_summary.csv"), required = FALSE)
  if (!is.null(forecast_tau)) {
    forecast_tau <- app_joint_qdesn_article_filter_selected_candidate(
      forecast_tau,
      selected_candidate_id,
      "selected VB forecast tau summary"
    )
  }
  list(
    phase107_dir = phase107_dir,
    phase109_dir = phase109_dir,
    source_verification = source_verification,
    phase107 = list(
      selected = selected,
      health = health,
      candidate_registry = candidate_registry,
      fit_model = fit_model,
      forecast_model = forecast_model,
      fit_scenario = fit_scenario,
      forecast_scenario = forecast_scenario,
      forecast_tau = forecast_tau
    ),
    phase109 = list(
      run_config = app_joint_qdesn_article_read_required(phase109_dir, "run_config.csv"),
      assessment = app_joint_qdesn_article_read_required(phase109_dir, "mcmc_readiness_assessment.csv"),
      summary = app_joint_qdesn_article_read_required(phase109_dir, "mcmc_readiness_summary.csv"),
      truth = app_joint_qdesn_article_read_required(phase109_dir, "truth_distance_summary.csv"),
      check = app_joint_qdesn_article_read_required(phase109_dir, "check_loss_summary.csv"),
      crps = app_joint_qdesn_article_read_required(phase109_dir, "crps_grid_summary.csv"),
      hit = app_joint_qdesn_article_read_required(phase109_dir, "hit_rate_summary.csv"),
      interval = app_joint_qdesn_article_read_required(phase109_dir, "interval_summary.csv"),
      vb_mcmc_distance = app_joint_qdesn_article_read_required(phase109_dir, "vb_mcmc_distance_summary.csv"),
      chain_distance = app_joint_qdesn_article_read_required(phase109_dir, "chain_to_pooled_distance_summary.csv"),
      failures = app_joint_qdesn_article_read_required(phase109_dir, "scenario_worker_failures.csv"),
      fit_truth = app_joint_qdesn_article_read_required(phase109_dir, "fit_truth_comparison.csv")
    )
  )
}

app_joint_qdesn_article_gate <- function(status) {
  status <- as.character(status)
  if (any(status == "fail")) return("fail")
  if (any(status == "review")) return("review")
  "pass"
}

app_joint_qdesn_article_make_vb_model_summary <- function(src) {
  fit <- src$phase107$fit_model
  forecast <- src$phase107$forecast_model
  by <- c("model_id", "display_label", "likelihood", "fit_structure")
  fit_sel <- fit[, c(by, "truth_mae", "truth_rmse", "check_loss_mean", "raw_crossing_pairs", "contract_crossing_pairs", "reached_max_iter", "gate_status"), drop = FALSE]
  names(fit_sel)[names(fit_sel) %in% c("truth_mae", "truth_rmse", "check_loss_mean", "raw_crossing_pairs", "contract_crossing_pairs", "reached_max_iter", "gate_status")] <-
    c("fit_truth_mae", "fit_truth_rmse", "fit_check_loss", "fit_raw_crossings", "fit_contract_crossings", "fit_max_iter_rows", "fit_gate_status")
  fc_sel <- forecast[, c(by, "truth_mae", "truth_rmse", "check_loss_mean", "crps_grid_mean", "abs_hit_rate_error", "abs_coverage_error", "raw_crossing_pairs", "contract_crossing_pairs", "reached_max_iter", "max_abs_adjustment", "gate_status"), drop = FALSE]
  names(fc_sel)[names(fc_sel) %in% c("truth_mae", "truth_rmse", "check_loss_mean", "raw_crossing_pairs", "contract_crossing_pairs", "reached_max_iter", "max_abs_adjustment", "gate_status")] <-
    c("forecast_truth_mae", "forecast_truth_rmse", "forecast_check_loss", "forecast_raw_crossings", "forecast_contract_crossings", "forecast_max_iter_rows", "forecast_max_adjustment", "forecast_gate_status")
  out <- merge(fit_sel, fc_sel, by = by, all = TRUE)
  out$model_label <- app_joint_qdesn_article_label(out$display_label)
  out$model_role <- ifelse(out$fit_structure == "joint" & out$likelihood == "al", "primary joint AL readout",
    ifelse(out$fit_structure == "joint" & out$likelihood == "exal", "joint exAL comparator",
      ifelse(out$fit_structure == "independent_single_tau" & out$likelihood == "al", "independent AL comparator", "independent exAL comparator")))
  out$article_gate <- mapply(function(a, b) {
    vals <- unique(unlist(strsplit(paste(a, b, sep = ";"), ";", fixed = TRUE)))
    app_joint_qdesn_article_gate(trimws(vals[nzchar(vals)]))
  }, out$fit_gate_status, out$forecast_gate_status)
  ord <- match(out$model_id, c(
    "joint_qdesn_rhs_vb", "qdesn_rhs_independent_vb",
    "joint_exqdesn_rhs_vb", "exqdesn_rhs_independent_vb"
  ))
  out[order(ord), , drop = FALSE]
}

app_joint_qdesn_article_make_vb_model_table <- function(summary, scope = c("main", "provenance")) {
  scope <- match.arg(scope)
  out <- data.frame(
    Model = summary$model_label,
    Readout = app_joint_qdesn_article_readout_label(summary$fit_structure),
    `Fit MAE` = vapply(summary$fit_truth_mae, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Forecast MAE` = vapply(summary$forecast_truth_mae, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Forecast RMSE` = vapply(summary$forecast_truth_rmse, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Check loss` = vapply(summary$forecast_check_loss, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Grid CRPS` = vapply(summary$crps_grid_mean, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Hit-rate error` = vapply(summary$abs_hit_rate_error, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Pre-rearrangement crossings` = vapply(summary$forecast_raw_crossings, app_joint_qdesn_article_fmt_int, character(1L)),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  if (identical(scope, "main")) {
    out <- out[, c(
      "Model", "Fit MAE", "Forecast MAE", "Check loss", "Grid CRPS",
      "Hit-rate error", "Pre-rearrangement crossings"
    ), drop = FALSE]
    names(out)[names(out) == "Pre-rearrangement crossings"] <- "Raw crossings"
  }
  if (identical(scope, "provenance")) {
    out <- data.frame(
      Model = out$Model,
      Likelihood = app_joint_qdesn_article_likelihood_label(summary$likelihood),
      out[, setdiff(names(out), "Model"), drop = FALSE],
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    out$`Reported-grid crossings` <- vapply(summary$forecast_contract_crossings, app_joint_qdesn_article_fmt_int, character(1L))
    out$`Diagnostic status` <- summary$article_gate
  }
  out
}

app_joint_qdesn_article_make_vb_scenario_table <- function(src, bold_winners = FALSE) {
  fc <- src$phase107$forecast_scenario
  scenario_ids <- unique(fc$scenario_id)
  ids <- c("joint_qdesn_rhs_vb", "qdesn_rhs_independent_vb", "joint_exqdesn_rhs_vb", "exqdesn_rhs_independent_vb")
  rows <- lapply(scenario_ids, function(sc) {
    block <- fc[fc$scenario_id == sc & fc$model_id %in% ids, , drop = FALSE]
    vals <- setNames(rep("--", length(ids)), ids)
    min_mae_display <- app_joint_qdesn_article_fmt_num(min(block$truth_mae, na.rm = TRUE), digits = 3)
    for (id in ids) {
      row <- block[block$model_id == id, , drop = FALSE]
      if (nrow(row)) {
        val <- app_joint_qdesn_article_fmt_pair(row$truth_mae[[1L]], row$truth_rmse[[1L]])
        if (isTRUE(bold_winners) && identical(app_joint_qdesn_article_fmt_num(row$truth_mae[[1L]], digits = 3), min_mae_display)) {
          val <- sprintf("\\textbf{%s}", val)
        }
        vals[[id]] <- val
      }
    }
    data.frame(
      Scenario = app_joint_qdesn_article_scenario_label(sc),
      `Joint QDESN` = vals[["joint_qdesn_rhs_vb"]],
      `Independent QDESN` = vals[["qdesn_rhs_independent_vb"]],
      `Joint exQDESN` = vals[["joint_exqdesn_rhs_vb"]],
      `Independent exQDESN` = vals[["exqdesn_rhs_independent_vb"]],
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  app_bind_rows_fill(rows)
}

app_joint_qdesn_article_make_mcmc_scenario_summary <- function(src) {
  s <- src$phase109$summary
  a <- src$phase109$assessment[, c("scenario_id", "gate_status", "status_reason"), drop = FALSE]
  out <- merge(s, a, by = "scenario_id", all.x = TRUE)
  out$scenario_label <- app_joint_qdesn_article_scenario_label(out$scenario_id)
  out$family_label <- app_joint_qdesn_article_family_label(out$distribution_family)
  out
}

app_joint_qdesn_article_make_mcmc_scenario_table <- function(summary) {
  data.frame(
    Scenario = summary$scenario_label,
    Class = summary$scenario_class,
    Family = summary$family_label,
    `VB MAE` = vapply(summary$vb_truth_mae, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `MCMC MAE` = vapply(summary$mcmc_truth_mae, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `MCMC check loss` = vapply(summary$mcmc_check_loss_mean, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `VB-MCMC path distance` = vapply(summary$vb_mcmc_max_normalized_distance, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Chain-pooled path distance` = vapply(summary$max_chain_to_pooled_normalized_distance, app_joint_qdesn_article_fmt_num, character(1L), digits = 3),
    `Pre-rearrangement crossings` = vapply(summary$mcmc_raw_crossing_pairs, app_joint_qdesn_article_fmt_int, character(1L)),
    `Runtime min.` = vapply(summary$total_elapsed_seconds / 60, app_joint_qdesn_article_fmt_num, character(1L), digits = 1),
    `Diagnostic note` = app_joint_qdesn_article_diag_note(summary$status_reason),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

app_joint_qdesn_article_make_protocol_table <- function(src, scope = c("main", "provenance")) {
  scope <- match.arg(scope)
  selected <- src$phase107$selected[isTRUE(src$phase107$selected$selected), , drop = FALSE]
  if (!nrow(selected)) selected <- src$phase107$selected[1L, , drop = FALSE]
  registry <- src$phase107$candidate_registry[src$phase107$candidate_registry$candidate_id == selected$candidate_id[[1L]], , drop = FALSE]
  mcmc_cfg <- src$phase109$run_config[1L, , drop = FALSE]
  mcmc_summary <- src$phase109$summary
  tau_grid <- gsub(",", ", ", unique(mcmc_summary$tau_grid)[[1L]], fixed = TRUE)
  if (identical(scope, "main")) {
    return(data.frame(
      Item = c(
        "Synthetic mechanisms",
        "Quantile grid",
        "Fit window",
        "Held-out block",
        "VB comparison rows",
        "Forecast design",
        "Reported quantiles",
        "MCMC reference"
      ),
      Value = c(
        "Three bridge mechanisms and six stress mechanisms with known conditional quantiles.",
        tau_grid,
        sprintf("%s observations after DESN washout.", unique(mcmc_summary$n_train)[[1L]]),
        "1000 observations reserved for held-out validation.",
        "Joint and independent QDESN and exQDESN readouts, all with the regularized horseshoe (RHS) prior.",
        "No-refit rolling-origin forecasts over a common held-out origin grid.",
        "Scores use the monotone grid obtained after rearrangement; pre-rearrangement crossings are retained as diagnostics.",
        "Fit-window, VB-initialized MCMC reference for the selected joint QDESN RHS row."
      ),
      stringsAsFactors = FALSE
    ))
  }
  data.frame(
    Item = c(
      "Selected VB source",
      "Selected VB specification",
      "VB validation role",
      "MCMC reference source",
      "MCMC reference role",
      "MCMC reference controls",
      "Quantile grid",
      "Diagnostic policy"
    ),
    Value = c(
      app_prefer_repo_relative_path(src$phase107_dir),
      sprintf(
        "%s; tau0=%s, alpha prior sd=%s, VB max iter %s with adaptive grid %s",
        selected$candidate_id[[1L]],
        registry$tau0[[1L]] %||% "--",
        registry$alpha_prior_sd[[1L]] %||% "--",
        registry$vb_max_iter[[1L]] %||% "--",
        registry$adaptive_vb_max_iter_grid[[1L]] %||% "--"
      ),
      "Selected VB fit and no-refit held-out forecast validation used for main forecast comparisons.",
      app_prefer_repo_relative_path(src$phase109_dir),
      "VB-initialized MCMC fit-window reference layer for the primary Joint QDESN RHS row; not a forecast validation rerun.",
      sprintf(
        "%s chains, %s iterations, burn %s, thin %s.",
        mcmc_cfg$mcmc_n_chains[[1L]],
        mcmc_cfg$mcmc_n_iter[[1L]],
        mcmc_cfg$mcmc_burn[[1L]],
        mcmc_cfg$mcmc_thin[[1L]]
      ),
      tau_grid,
      "Implementation defects remain hard failures; pre-rearrangement crossings and iteration-budget events are diagnostic qualifications."
    ),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_article_make_gate_summary <- function(src, vb_summary, mcmc_summary) {
  health <- src$phase107$health
  mcmc_assessment <- src$phase109$assessment
  failures <- src$phase109$failures
  manifest_status <- if (all(src$source_verification$status == "pass")) "pass" else "fail"
  data.frame(
    Evidence = c(
      "Source manifests",
      "Selected VB validation source",
      "MCMC article reference source",
      "MCMC worker failures",
      "MCMC contract crossings",
      "MCMC raw crossings",
      "Article asset extraction"
    ),
    Gate = c(
      manifest_status,
      app_joint_qdesn_article_gate(health$gate_status),
      app_joint_qdesn_article_gate(mcmc_assessment$gate_status),
      ifelse(nrow(failures) == 0L, "pass", "fail"),
      ifelse(sum(mcmc_summary$mcmc_contract_crossing_pairs, na.rm = TRUE) == 0, "pass", "fail"),
      ifelse(sum(mcmc_summary$mcmc_raw_crossing_pairs, na.rm = TRUE) == 0, "pass", "review"),
      "pass"
    ),
    Detail = c(
      sprintf("%d source files verified", nrow(src$source_verification)),
      sprintf(
        "Selected candidate %s; mean forecast MAE %s; raw forecast crossings %s; contract crossings %s",
        src$phase107$selected$candidate_id[[1L]],
        app_joint_qdesn_article_fmt_num(src$phase107$selected$mean_forecast_truth_mae[[1L]], 3),
        app_joint_qdesn_article_fmt_int(src$phase107$selected$forecast_raw_crossings[[1L]]),
        app_joint_qdesn_article_fmt_int(health$contract_crossings[[1L]])
      ),
      sprintf(
        "%d pass, %d review, %d fail scenario rows",
        sum(mcmc_assessment$gate_status == "pass"),
        sum(mcmc_assessment$gate_status == "review"),
        sum(mcmc_assessment$gate_status == "fail")
      ),
      sprintf("%d worker failure rows", nrow(failures)),
      sprintf("%s contract crossing pairs", app_joint_qdesn_article_fmt_int(sum(mcmc_summary$mcmc_contract_crossing_pairs, na.rm = TRUE))),
      sprintf("%s raw crossing pairs", app_joint_qdesn_article_fmt_int(sum(mcmc_summary$mcmc_raw_crossing_pairs, na.rm = TRUE))),
      "No inference rerun; assets generated from hash-verified selected VB and MCMC reference sources."
    ),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_article_plot_vb_model_bars <- function(path, summary) {
  labels <- summary$model_label
  mat <- rbind(
    Fit = summary$fit_truth_mae,
    Forecast = summary$forecast_truth_mae
  )
  app_joint_qdesn_article_pdf_plot(path, width = 7.4, height = 4.9, {
    graphics::par(mar = c(8.6, 4.8, 2.8, 1.0))
    graphics::barplot(
      mat,
      beside = TRUE,
      names.arg = labels,
      las = 2,
      col = c("#0072B2", "#D55E00"),
      border = NA,
      ylab = "Mean absolute error to true quantiles",
      main = "VB fit and forecast truth error"
    )
    graphics::grid(nx = NA, ny = NULL, col = "grey88")
    graphics::legend("topright", legend = rownames(mat), fill = c("#0072B2", "#D55E00"), bty = "n", cex = 0.85)
  })
}

app_joint_qdesn_article_plot_vb_forecast_heatmap <- function(path, scenario_table) {
  model_cols <- c("Joint QDESN", "Independent QDESN", "Joint exQDESN", "Independent exQDESN")
  mat <- do.call(cbind, lapply(model_cols, function(nm) {
    as.numeric(sub(" .*", "", scenario_table[[nm]]))
  }))
  colnames(mat) <- model_cols
  rownames(mat) <- scenario_table$Scenario
  app_joint_qdesn_article_pdf_plot(path, width = 8.4, height = 6.2, {
    graphics::par(mar = c(8.2, 9.5, 3.2, 1.0))
    z <- mat[nrow(mat):1L, , drop = FALSE]
    pal <- grDevices::hcl.colors(80, "Blues 3", rev = FALSE)
    graphics::image(seq_len(ncol(z)), seq_len(nrow(z)), t(z), col = pal, axes = FALSE, xlab = "", ylab = "", main = "Forecast MAE by scenario and VB row")
    graphics::axis(1, at = seq_len(ncol(z)), labels = colnames(z), las = 2, cex.axis = 0.78)
    graphics::axis(2, at = seq_len(nrow(z)), labels = rownames(z), las = 1, cex.axis = 0.76)
    thresh <- stats::quantile(z, 0.78, na.rm = TRUE)
    for (ii in seq_len(nrow(z))) for (jj in seq_len(ncol(z))) {
      graphics::text(jj, ii, app_joint_qdesn_article_fmt_num(z[ii, jj], 3), cex = 0.72, col = ifelse(z[ii, jj] > thresh, "white", "black"))
    }
    graphics::box()
  })
}

app_joint_qdesn_article_plot_mcmc_truth <- function(path, summary) {
  ord <- order(summary$mcmc_truth_mae)
  summary <- summary[ord, , drop = FALSE]
  mat <- rbind(VB = summary$vb_truth_mae, MCMC = summary$mcmc_truth_mae)
  app_joint_qdesn_article_pdf_plot(path, width = 8.2, height = 5.2, {
    graphics::par(mar = c(8.8, 4.8, 2.8, 1.0))
    graphics::barplot(
      mat,
      beside = TRUE,
      names.arg = summary$scenario_label,
      las = 2,
      col = c("#009E73", "#CC79A7"),
      border = NA,
      ylab = "Fit MAE to true quantiles",
      main = "VB-initialized MCMC fit recovery"
    )
    graphics::grid(nx = NA, ny = NULL, col = "grey88")
    graphics::legend("topleft", legend = rownames(mat), fill = c("#009E73", "#CC79A7"), bty = "n", cex = 0.84)
  })
}

app_joint_qdesn_article_plot_mcmc_distance <- function(path, summary) {
  ord <- order(summary$vb_mcmc_max_normalized_distance)
  summary <- summary[ord, , drop = FALSE]
  xlim <- range(c(summary$vb_mcmc_max_normalized_distance, summary$max_chain_to_pooled_normalized_distance), finite = TRUE)
  app_joint_qdesn_article_pdf_plot(path, width = 7.4, height = 5.2, {
    graphics::par(mar = c(4.8, 9.2, 2.8, 1.0))
    yy <- seq_len(nrow(summary))
    graphics::plot(summary$vb_mcmc_max_normalized_distance, yy, xlim = c(0, max(xlim) * 1.15), yaxt = "n",
      pch = 16, col = "#0072B2", xlab = "Maximum normalized distance", ylab = "", main = "VB/MCMC and chain agreement")
    graphics::points(summary$max_chain_to_pooled_normalized_distance, yy, pch = 17, col = "#D55E00")
    graphics::axis(2, at = yy, labels = summary$scenario_label, las = 1, cex.axis = 0.78)
    graphics::grid(col = "grey88")
    graphics::legend("bottomright", legend = c("VB to MCMC", "chain to pooled"), pch = c(16, 17), col = c("#0072B2", "#D55E00"), bty = "n")
  })
}

app_joint_qdesn_article_plot_mcmc_hit <- function(path, hit) {
  agg <- aggregate(hit_rate ~ model_id + display_label + tau, hit, mean, na.rm = TRUE)
  models <- unique(agg$model_id)
  cols <- c("#0072B2", "#D55E00", "#009E73")[seq_along(models)]
  app_joint_qdesn_article_pdf_plot(path, width = 6.7, height = 4.8, {
    graphics::par(mar = c(4.8, 4.8, 2.8, 1.0))
    graphics::plot(range(agg$tau), range(c(agg$hit_rate, agg$tau), finite = TRUE), type = "n",
      xlab = "Target quantile level", ylab = "Empirical hit rate", main = "MCMC fit hit-rate calibration")
    graphics::abline(0, 1, lty = 2, col = "grey45")
    graphics::grid(col = "grey88")
    for (kk in seq_along(models)) {
      block <- agg[agg$model_id == models[[kk]], , drop = FALSE]
      block <- block[order(block$tau), , drop = FALSE]
      graphics::lines(block$tau, block$hit_rate, type = "b", pch = 15 + kk, lwd = 2, col = cols[[kk]])
    }
    graphics::legend("topleft", legend = app_joint_qdesn_article_label(unique(agg$display_label[match(models, agg$model_id)])),
      col = cols, pch = 15 + seq_along(models), lwd = 2, bty = "n", cex = 0.78)
  })
}

app_joint_qdesn_article_plot_overlay <- function(path, fit_truth, scenario_id, model_id = "joint_qdesn_rhs_mcmc") {
  dat <- fit_truth[fit_truth$scenario_id == scenario_id & fit_truth$model_id == model_id, , drop = FALSE]
  if (!nrow(dat)) return(NA_character_)
  keep_tau <- intersect(c(0.05, 0.50, 0.95), sort(unique(dat$tau)))
  dat <- dat[dat$tau %in% keep_tau, , drop = FALSE]
  agg <- aggregate(cbind(y, true_quantile, qhat) ~ effective_index + tau, dat, mean, na.rm = TRUE)
  obs <- aggregate(y ~ effective_index, agg, mean, na.rm = TRUE)
  taus <- sort(unique(agg$tau))
  cols <- c("#0072B2", "#000000", "#D55E00")[seq_along(taus)]
  app_joint_qdesn_article_pdf_plot(path, width = 7.3, height = 4.8, {
    graphics::par(mar = c(4.6, 4.8, 2.9, 1.0))
    yr <- range(c(obs$y, agg$true_quantile, agg$qhat), finite = TRUE)
    graphics::plot(obs$effective_index, obs$y, pch = 16, cex = 0.28,
      col = grDevices::adjustcolor("grey35", 0.45), ylim = yr,
      xlab = "Effective time index", ylab = "Observed value and quantile",
      main = app_joint_qdesn_article_scenario_label(scenario_id))
    graphics::grid(col = "grey88")
    for (kk in seq_along(taus)) {
      block <- agg[abs(agg$tau - taus[[kk]]) < 1e-12, , drop = FALSE]
      block <- block[order(block$effective_index), , drop = FALSE]
      graphics::lines(block$effective_index, block$true_quantile, col = cols[[kk]], lwd = 2.0, lty = 2)
      graphics::lines(block$effective_index, block$qhat, col = cols[[kk]], lwd = 1.6)
    }
    graphics::legend("topleft",
      legend = c("observed y", paste0("true tau=", taus), paste0("MCMC tau=", taus)),
      col = c("grey35", cols, cols),
      pch = c(16, rep(NA, 2L * length(taus))),
      lty = c(NA, rep(2, length(taus)), rep(1, length(taus))),
      lwd = c(NA, rep(2.0, length(taus)), rep(1.6, length(taus))),
      bty = "n", cex = 0.70
    )
  })
}

app_joint_qdesn_run_article_validation_assets <- function(
  phase107_dir = app_joint_qdesn_default_phase107_dir(),
  phase109_dir = app_path("application/cache/joint_qdesn_mcmc_article_phase109_20260707"),
  tables_dir = app_joint_qdesn_article_default_tables_dir(),
  figures_dir = app_joint_qdesn_article_default_figures_dir(),
  out_dir = app_joint_qdesn_article_default_out_dir()
) {
  phase107_dir <- normalizePath(phase107_dir, mustWork = TRUE)
  phase109_dir <- normalizePath(phase109_dir, mustWork = TRUE)
  tables_dir <- normalizePath(tables_dir, mustWork = TRUE)
  figures_dir <- normalizePath(figures_dir, mustWork = FALSE)
  out_dir <- normalizePath(out_dir, mustWork = FALSE)
  app_ensure_dir(figures_dir)
  app_ensure_dir(out_dir)

  src <- app_joint_qdesn_article_load_sources(phase107_dir, phase109_dir)
  vb_summary <- app_joint_qdesn_article_make_vb_model_summary(src)
  vb_table <- app_joint_qdesn_article_make_vb_model_table(vb_summary, scope = "main")
  vb_provenance_table <- app_joint_qdesn_article_make_vb_model_table(vb_summary, scope = "provenance")
  vb_scenario_table <- app_joint_qdesn_article_make_vb_scenario_table(src, bold_winners = FALSE)
  vb_scenario_latex_table <- app_joint_qdesn_article_make_vb_scenario_table(src, bold_winners = TRUE)
  mcmc_summary <- app_joint_qdesn_article_make_mcmc_scenario_summary(src)
  mcmc_table <- app_joint_qdesn_article_make_mcmc_scenario_table(mcmc_summary)
  protocol_table <- app_joint_qdesn_article_make_protocol_table(src, scope = "main")
  protocol_provenance_table <- app_joint_qdesn_article_make_protocol_table(src, scope = "provenance")
  gate_summary <- app_joint_qdesn_article_make_gate_summary(src, vb_summary, mcmc_summary)

  table_paths <- c(
    protocol_csv = app_joint_qdesn_article_write_csv(protocol_table, file.path(tables_dir, "joint_qdesn_article_validation_protocol.csv")),
    protocol_tex = app_joint_qdesn_article_write_latex_table(protocol_table, file.path(tables_dir, "joint_qdesn_article_validation_protocol.tex"),
      "Joint multi-quantile validation protocol. The table reports the statistical design used for the article-facing summaries; source hashes and run-level provenance are recorded in the generated manifest.",
      "tab:joint-qdesn-article-validation-protocol",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.24\\textwidth}>{\\raggedright\\arraybackslash}p{0.66\\textwidth}@{}"
    ),
    protocol_provenance_csv = app_joint_qdesn_article_write_csv(protocol_provenance_table, file.path(tables_dir, "joint_qdesn_article_validation_protocol_provenance.csv")),
    protocol_provenance_tex = app_joint_qdesn_article_write_latex_table(protocol_provenance_table, file.path(tables_dir, "joint_qdesn_article_validation_protocol_provenance.tex"),
      "Run-level provenance for the joint multi-quantile validation assets. This table records source directories, selected computational controls, and diagnostic policy; it is intended for reproducibility records rather than the main statistical comparison.",
      "tab:joint-qdesn-article-validation-protocol-provenance",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.24\\textwidth}>{\\raggedright\\arraybackslash}p{0.66\\textwidth}@{}",
      size = "\\scriptsize"
    ),
    vb_model_csv = app_joint_qdesn_article_write_csv(vb_summary, file.path(tables_dir, "joint_qdesn_article_validation_vb_model_summary.csv")),
    vb_model_tex = app_joint_qdesn_article_write_latex_table(vb_table, file.path(tables_dir, "joint_qdesn_article_validation_vb_model_summary.tex"),
      "Compact joint multi-quantile synthetic validation summary averaged over the nine mechanisms in Table~\\ref{tab:joint-qdesn-article-validation-protocol}; this is not a single empirical data set. Rows labeled QDESN use the AL likelihood, rows labeled exQDESN use the exAL likelihood, and the model name indicates whether the readout is joint or independently fit by quantile. Fit and forecast MAE are computed against known conditional quantiles, check loss scores realized observations, grid CRPS summarizes the reported monotone quantile grid, hit-rate error summarizes marginal calibration, and raw crossings count adjacent quantile crossings before monotone rearrangement.",
      "tab:joint-qdesn-article-validation-vb-model-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.22\\textwidth}rrrrrr@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    vb_model_provenance_tex = app_joint_qdesn_article_write_latex_table(vb_provenance_table, file.path(tables_dir, "joint_qdesn_article_validation_vb_model_summary_provenance.tex"),
      "Diagnostic version of the selected VB summary. The reported-grid crossing column records crossings after monotone rearrangement, and the diagnostic status is retained for reproducibility review.",
      "tab:joint-qdesn-article-validation-vb-model-summary-provenance",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.15\\textwidth}llrrrrrrrll@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    vb_scenario_csv = app_joint_qdesn_article_write_csv(vb_scenario_table, file.path(tables_dir, "joint_qdesn_article_validation_vb_scenario_summary.csv")),
    vb_scenario_tex = app_joint_qdesn_article_write_latex_table(vb_scenario_latex_table, file.path(tables_dir, "joint_qdesn_article_validation_vb_scenario_summary.tex"),
      "Scenario-level held-out forecast distance to true conditional quantiles for the same joint multi-quantile synthetic validation suite. Entries report forecast MAE with RMSE in parentheses for each VB row; lower values indicate closer agreement with the oracle conditional quantile paths, and boldface marks the lowest displayed MAE within each scenario. The lowest row changes across scenarios, so the table should be read as a mechanism-specific diagnostic rather than a uniform ranking.",
      "tab:joint-qdesn-article-validation-vb-scenario-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.26\\textwidth}rrrr@{}",
      size = "\\scriptsize",
      resize = TRUE,
      raw_latex_cols = c("Joint QDESN", "Independent QDESN", "Joint exQDESN", "Independent exQDESN")
    ),
    mcmc_scenario_csv = app_joint_qdesn_article_write_csv(mcmc_summary, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_scenario_summary.csv")),
    mcmc_scenario_tex = app_joint_qdesn_article_write_latex_table(mcmc_table, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_scenario_summary.tex"),
      "VB-initialized MCMC fit-reference diagnostics for the primary Joint QDESN RHS row. The MCMC layer checks fit-window posterior agreement and fit recovery; it does not replace the held-out VB forecast validation. Path distances compare fitted quantile paths after normalization to the scale of the oracle paths.",
      "tab:joint-qdesn-article-validation-mcmc-scenario-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.16\\textwidth}llrrrrrrr>{\\raggedright\\arraybackslash}p{0.18\\textwidth}@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    gate_summary_csv = app_joint_qdesn_article_write_csv(gate_summary, file.path(tables_dir, "joint_qdesn_article_validation_gate_summary.csv")),
    gate_summary_tex = app_joint_qdesn_article_write_latex_table(gate_summary, file.path(tables_dir, "joint_qdesn_article_validation_gate_summary.tex"),
      "Validation readiness gates for the article-facing joint QDESN evidence pack.",
      "tab:joint-qdesn-article-validation-gate-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.25\\textwidth}l>{\\raggedright\\arraybackslash}p{0.55\\textwidth}@{}",
      size = "\\scriptsize"
    )
  )
  table_paths[["article_wrapper"]] <- app_joint_qdesn_article_write_wrapper(
    table_paths[c("protocol_tex", "vb_model_tex", "vb_scenario_tex")],
    file.path(tables_dir, "joint_qdesn_article_validation_tables.tex")
  )
  table_paths[["provenance_wrapper"]] <- app_joint_qdesn_article_write_wrapper(
    table_paths[c("protocol_provenance_tex", "vb_model_provenance_tex", "vb_scenario_tex", "mcmc_scenario_tex", "gate_summary_tex")],
    file.path(tables_dir, "joint_qdesn_article_validation_provenance_tables.tex")
  )

  figure_paths <- c(
    vb_model_truth_error = app_joint_qdesn_article_plot_vb_model_bars(file.path(figures_dir, "joint_qdesn_article_validation_vb_fit_forecast_mae.pdf"), vb_summary),
    vb_forecast_heatmap = app_joint_qdesn_article_plot_vb_forecast_heatmap(file.path(figures_dir, "joint_qdesn_article_validation_vb_forecast_mae_heatmap.pdf"), vb_scenario_table),
    mcmc_fit_truth_error = app_joint_qdesn_article_plot_mcmc_truth(file.path(figures_dir, "joint_qdesn_article_validation_mcmc_fit_truth_mae.pdf"), mcmc_summary),
    mcmc_distance = app_joint_qdesn_article_plot_mcmc_distance(file.path(figures_dir, "joint_qdesn_article_validation_mcmc_distance_diagnostics.pdf"), mcmc_summary),
    mcmc_hit_rate = app_joint_qdesn_article_plot_mcmc_hit(file.path(figures_dir, "joint_qdesn_article_validation_mcmc_hit_rate_by_tau.pdf"), src$phase109$hit),
    overlay_normal_bridge = app_joint_qdesn_article_plot_overlay(file.path(figures_dir, "joint_qdesn_article_validation_mcmc_overlay_normal_bridge.pdf"), src$phase109$fit_truth, "normal_bridge"),
    overlay_asymmetric_laplace_tail = app_joint_qdesn_article_plot_overlay(file.path(figures_dir, "joint_qdesn_article_validation_mcmc_overlay_asymmetric_laplace_tail.pdf"), src$phase109$fit_truth, "asymmetric_laplace_tail"),
    overlay_persistent_heavy_tail = app_joint_qdesn_article_plot_overlay(file.path(figures_dir, "joint_qdesn_article_validation_mcmc_overlay_persistent_heavy_tail.pdf"), src$phase109$fit_truth, "persistent_heavy_tail")
  )
  figure_paths <- figure_paths[!is.na(figure_paths)]

  asset_paths <- c(table_paths, figure_paths)
  asset_manifest <- data.frame(
    label = names(asset_paths),
    artifact_type = ifelse(grepl("\\.pdf$", asset_paths), "figure", ifelse(grepl("\\.tex$", asset_paths), "latex_table", "csv_table")),
    path = vapply(asset_paths, app_prefer_repo_relative_path, character(1L)),
    size_bytes = as.numeric(file.info(asset_paths)$size),
    sha256 = vapply(asset_paths, app_sha256_file, character(1L)),
    source_vb_dir = app_prefer_repo_relative_path(phase107_dir),
    source_mcmc_dir = app_prefer_repo_relative_path(phase109_dir),
    stringsAsFactors = FALSE
  )
  table_paths[["asset_manifest"]] <- app_joint_qdesn_article_write_csv(
    asset_manifest,
    file.path(tables_dir, "joint_qdesn_article_validation_asset_manifest.csv")
  )

  readiness <- data.frame(
    overall_gate = app_joint_qdesn_article_gate(gate_summary$Gate),
    vb_source_gate = app_joint_qdesn_article_gate(src$phase107$health$gate_status),
    mcmc_reference_gate = app_joint_qdesn_article_gate(src$phase109$assessment$gate_status),
    selected_candidate = src$phase107$selected$candidate_id[[1L]],
    vb_source_forecast_raw_crossings = sum(src$phase107$forecast_model$raw_crossing_pairs, na.rm = TRUE),
    vb_source_forecast_contract_crossings = sum(src$phase107$forecast_model$contract_crossing_pairs, na.rm = TRUE),
    mcmc_worker_failures = nrow(src$phase109$failures),
    mcmc_contract_crossings = sum(mcmc_summary$mcmc_contract_crossing_pairs, na.rm = TRUE),
    mcmc_raw_crossings = sum(mcmc_summary$mcmc_raw_crossing_pairs, na.rm = TRUE),
    mcmc_review_scenarios = paste(mcmc_summary$scenario_id[mcmc_summary$gate_status == "review"], collapse = ","),
    recommended_next_action = "Use these assets to update the joint QDESN simulation results text; retain review language for selected-VB raw pre-rearrangement crossings and do not describe the MCMC reference as forecast validation.",
    stringsAsFactors = FALSE
  )

  run_config <- data.frame(
    run_id = basename(out_dir),
    vb_source_dir = phase107_dir,
    mcmc_reference_dir = phase109_dir,
    tables_dir = tables_dir,
    figures_dir = figures_dir,
    output_dir = out_dir,
    n_tables = sum(!grepl("\\.pdf$", asset_paths)),
    n_figures = sum(grepl("\\.pdf$", asset_paths)),
    created_at = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
    stringsAsFactors = FALSE
  )

  readme_path <- file.path(out_dir, "README.md")
  writeLines(c(
    "# Joint QDESN Article Validation Assets",
    "",
    "This directory records the article-asset verification layer for joint QDESN simulation tables and figures.",
    "",
    "No model fitting, MCMC sampling, or fixture generation is performed here. The stage verifies and summarizes:",
    "",
    "- selected VB fit and held-out forecast validation for joint and independent QDESN and exQDESN RHS rows;",
    "- VB-initialized MCMC fit-reference diagnostics for the primary Joint QDESN RHS row.",
    "",
    "`tables/joint_qdesn_article_validation_tables.tex` is the compact main-article table wrapper.",
    "`tables/joint_qdesn_article_validation_provenance_tables.tex` retains the scenario, MCMC, and diagnostic provenance tables.",
    "Generated assets are listed in `tables/joint_qdesn_article_validation_asset_manifest.csv`.",
    "",
    sprintf("Overall gate: `%s`.", readiness$overall_gate[[1L]])
  ), readme_path, useBytes = TRUE)

  cache_paths <- c(
    run_config = app_joint_qdesn_article_write_csv(run_config, file.path(out_dir, "run_config.csv")),
    source_manifest_verification = app_joint_qdesn_article_write_csv(src$source_verification, file.path(out_dir, "source_manifest_verification.csv")),
    gate_summary = app_joint_qdesn_article_write_csv(gate_summary, file.path(out_dir, "gate_summary.csv")),
    article_readiness_assessment = app_joint_qdesn_article_write_csv(readiness, file.path(out_dir, "article_readiness_assessment.csv")),
    article_asset_manifest = app_joint_qdesn_article_write_csv(asset_manifest, file.path(out_dir, "article_asset_manifest.csv")),
    provenance = app_joint_qdesn_article_write_csv(app_joint_qvp_provenance_rows(), file.path(out_dir, "provenance.csv")),
    readme = normalizePath(readme_path, winslash = "/", mustWork = TRUE)
  )
  manifest_info <- app_joint_qdesn_write_manifest(cache_paths, out_dir)

  list(
    out_dir = out_dir,
    tables_dir = tables_dir,
    figures_dir = figures_dir,
    source_verification = src$source_verification,
    vb_summary = vb_summary,
    mcmc_summary = mcmc_summary,
    gate_summary = gate_summary,
    readiness = readiness,
    asset_manifest = asset_manifest,
    artifact_manifest = manifest_info$manifest,
    artifact_manifest_path = manifest_info$manifest_path
  )
}
