# Phase 155 article promotion for the balanced joint QDESN validation.
#
# This stage consumes the frozen Phase 153 replicated VB and Phase 154 MCMC
# evidence. It verifies source manifests and rebuilds article-facing tables; it
# does not fit a model or recompute validation scores.

app_joint_qdesn_phase155_default_dir <- function() {
  app_path("application/cache/joint_qdesn_phase155_article_promotion_20260731")
}

app_joint_qdesn_phase155_model_dictionary <- function() {
  data.frame(
    source_model_id = c(
      "joint_qdesn_rhs_vb",
      "qdesn_rhs_independent_vb",
      "joint_exqdesn_rhs_vb",
      "exqdesn_rhs_independent_vb"
    ),
    model_label = c(
      "Joint QDESN RHS",
      "Independent QDESN RHS",
      "Joint exQDESN RHS",
      "Independent exQDESN RHS"
    ),
    short_label = c(
      "Joint QDESN",
      "Independent QDESN",
      "Joint exQDESN",
      "Independent exQDESN"
    ),
    likelihood = c("AL", "AL", "exAL", "exAL"),
    readout = c("joint", "independent", "joint", "independent"),
    model_order = seq_len(4L),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase155_scenario_dictionary <- function() {
  data.frame(
    scenario_id = c(
      "asymmetric_laplace_tail",
      "gaussian_mixture_bridge",
      "laplace_bridge",
      "nonlinear_reservoir_friendly",
      "normal_bridge",
      "persistent_heavy_tail",
      "regime_shift",
      "student_t_location_scale"
    ),
    scenario_label = c(
      "Asymmetric Laplace Tail",
      "Gaussian-Mixture Bridge",
      "Laplace Bridge",
      "Nonlinear Reservoir Friendly",
      "Normal Bridge",
      "Persistent Heavy Tail",
      "Regime Shift",
      "Student-t Location-Scale"
    ),
    mechanism_detail = c(
      "Asymmetric Laplace; seasonal AR(1) location-scale",
      "Gaussian mixture; seasonal AR(1) location-scale",
      "Laplace; seasonal AR(1) location-scale",
      "Gaussian mixture; nonlinear reservoir dynamics",
      "Gaussian; seasonal AR(1) location-scale",
      "Student-t; persistent seasonal AR(1) dynamics",
      "Student-t; regime-shift location-scale",
      "Student-t; seasonal AR(1) location-scale"
    ),
    scenario_order = seq_len(8L),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase155_write_csv <- function(x, path) {
  app_ensure_dir(dirname(path))
  utils::write.csv(x, path, row.names = FALSE, na = "")
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_phase155_fmt_num <- function(x, digits = 3L) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  formatC(x[[1L]], format = "f", digits = digits)
}

app_joint_qdesn_phase155_fmt_int <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  formatC(round(x[[1L]]), format = "d", big.mark = ",")
}

app_joint_qdesn_phase155_latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

app_joint_qdesn_phase155_write_latex_table <- function(
  x,
  path,
  caption,
  label,
  align,
  raw_latex_cols = character(),
  size = "\\scriptsize",
  resize = FALSE
) {
  app_ensure_dir(dirname(path))
  rows <- lapply(seq_len(nrow(x)), function(ii) {
    cells <- unlist(x[ii, , drop = FALSE], use.names = FALSE)
    raw <- names(x) %in% raw_latex_cols
    cells[!raw] <- app_joint_qdesn_phase155_latex_escape(cells[!raw])
    paste(cells, collapse = " & ")
  })
  lines <- c(
    "% Generated by application/scripts/187_build_joint_qdesn_phase155_article_assets.R.",
    "\\begin{table}[!htbp]",
    "\\centering",
    size
  )
  if (isTRUE(resize)) lines <- c(lines, "\\resizebox{\\textwidth}{!}{%")
  lines <- c(
    lines,
    sprintf("\\begin{tabular}{%s}", align),
    "\\toprule",
    paste(app_joint_qdesn_phase155_latex_escape(names(x)), collapse = " & "),
    "\\\\",
    "\\midrule",
    paste0(rows, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}"
  )
  if (isTRUE(resize)) lines <- c(lines, "}%")
  lines <- c(
    lines,
    sprintf("\\caption{%s}", caption),
    sprintf("\\label{%s}", label),
    "\\end{table}"
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_phase155_verify_manifest <- function(dir, source_id) {
  app_joint_qdesn_phase153_verify_manifest(dir, source_id)
}

app_joint_qdesn_phase155_resolve_source_dir <- function(path) {
  if (grepl("^/", path)) {
    normalizePath(path, winslash = "/", mustWork = TRUE)
  } else {
    normalizePath(app_path(path), winslash = "/", mustWork = TRUE)
  }
}

app_joint_qdesn_phase155_read_source_metric <- function(source_dir, name) {
  path <- file.path(source_dir, name)
  if (!file.exists(path)) {
    stop(sprintf("Missing Phase155 source metric: %s", path), call. = FALSE)
  }
  app_read_csv(path)
}

app_joint_qdesn_phase155_aggregate_source_metrics <- function(case_summary) {
  source_map <- unique(case_summary[, c("source_block_id", "source_dir"), drop = FALSE])
  rows <- lapply(seq_len(nrow(source_map)), function(ii) {
    source_id <- source_map$source_block_id[[ii]]
    source_dir <- app_joint_qdesn_phase155_resolve_source_dir(source_map$source_dir[[ii]])
    crps <- app_joint_qdesn_phase155_read_source_metric(source_dir, "forecast_crps_grid_summary.csv")
    hit <- app_joint_qdesn_phase155_read_source_metric(source_dir, "forecast_hit_rate_summary.csv")
    chain <- app_joint_qdesn_phase155_read_source_metric(source_dir, "chain_to_pooled_distance_summary.csv")

    crps <- crps[toupper(crps$inference) == "MCMC", , drop = FALSE]
    hit <- hit[toupper(hit$inference) == "MCMC", , drop = FALSE]
    chain <- chain[toupper(chain$inference) == "MCMC", , drop = FALSE]
    cases <- unique(case_summary$case_id[case_summary$source_block_id == source_id])
    crps <- crps[crps$case_id %in% cases, , drop = FALSE]
    hit <- hit[hit$case_id %in% cases, , drop = FALSE]
    chain <- chain[chain$case_id %in% cases, , drop = FALSE]

    lapply(cases, function(case_id) {
      c_block <- crps[crps$case_id == case_id, , drop = FALSE]
      h_block <- hit[hit$case_id == case_id, , drop = FALSE]
      d_block <- chain[chain$case_id == case_id, , drop = FALSE]
      if (nrow(c_block) != 1L || !nrow(h_block) || !nrow(d_block)) {
        stop(sprintf("Incomplete source metrics for case '%s'.", case_id), call. = FALSE)
      }
      data.frame(
        case_id = case_id,
        mcmc_forecast_crps_grid = as.numeric(c_block$crps_grid_mean[[1L]]),
        mcmc_mean_abs_hit_rate_error = mean(as.numeric(h_block$abs_hit_rate_error), na.rm = TRUE),
        mcmc_max_abs_hit_rate_error = max(as.numeric(h_block$abs_hit_rate_error), na.rm = TRUE),
        max_chain_qhat_normalized_distance = max(as.numeric(d_block$qhat_normalized_to_pooled), na.rm = TRUE),
        max_chain_sigma_normalized_distance = max(as.numeric(d_block$sigma_normalized_to_pooled), na.rm = TRUE),
        max_chain_alpha_normalized_distance = max(as.numeric(d_block$alpha_normalized_to_pooled), na.rm = TRUE),
        source_block_id = source_id,
        stringsAsFactors = FALSE
      )
    })
  })
  app_joint_qdesn_bind_rows(unlist(rows, recursive = FALSE))
}

app_joint_qdesn_phase155_load <- function(
  phase154_dir = app_joint_qdesn_phase154_default_final_dir(),
  phase153_dir = app_joint_qdesn_phase153_default_vb_dir()
) {
  phase154_dir <- normalizePath(phase154_dir, winslash = "/", mustWork = TRUE)
  phase153_dir <- normalizePath(phase153_dir, winslash = "/", mustWork = TRUE)

  phase154_manifest <- app_joint_qdesn_phase155_verify_manifest(phase154_dir, "phase154_final")
  phase153_manifest <- app_joint_qdesn_phase155_verify_manifest(phase153_dir, "phase153_replication")
  phase154_source_manifest <- app_read_csv(file.path(phase154_dir, "source_manifest_verification.csv"))
  app_check_required_columns(phase154_source_manifest, c("source_id", "relative_path", "verified"), "Phase154 source verification")

  case_summary <- app_read_csv(file.path(phase154_dir, "final_mcmc_case_summary.csv"))
  case_assessment <- app_read_csv(file.path(phase154_dir, "final_mcmc_case_assessment.csv"))
  case_audit <- app_read_csv(file.path(phase154_dir, "final_case_audit.csv"))
  final_assessment <- app_read_csv(file.path(phase154_dir, "final_assessment.csv"))
  phase153_assessment <- app_read_csv(file.path(phase153_dir, "replication_assessment.csv"))
  phase153_contrasts <- app_read_csv(file.path(phase153_dir, "paired_contrast_summary.csv"))

  app_check_required_columns(case_summary, c(
    "case_id", "scenario_id", "source_model_id", "mcmc_fit_truth_mae",
    "mcmc_forecast_truth_mae", "mcmc_forecast_check_loss_mean",
    "mcmc_forecast_raw_crossing_pairs", "mcmc_forecast_contract_crossing_pairs",
    "mcmc_n_chains", "mcmc_n_iter", "mcmc_burn", "mcmc_thin",
    "mcmc_n_keep_total", "all_chain_init_source_provided",
    "mcmc_draws_all_finite", "source_block_id", "source_dir"
  ), "Phase154 final case summary")
  app_check_required_columns(case_assessment, c(
    "case_id", "implementation_status", "distance_status", "chain_status",
    "raw_crossing_status", "gate_status", "contract_crossing_pairs",
    "status_reason"
  ), "Phase154 final case assessment")
  app_check_required_columns(case_audit, c(
    "case_id", "exact_control_match", "article_grade", "final_status"
  ), "Phase154 final case audit")
  app_check_required_columns(phase153_contrasts, c(
    "base_scenario_id", "model_a", "model_b", "metric", "n_replicates",
    "median_delta", "model_a_win_fraction", "win_fraction_ci_lower",
    "win_fraction_ci_upper"
  ), "Phase153 paired contrasts")

  source_map <- unique(case_summary[, c("source_block_id", "source_dir"), drop = FALSE])
  source_manifests <- app_joint_qdesn_bind_rows(lapply(seq_len(nrow(source_map)), function(ii) {
    app_joint_qdesn_phase155_verify_manifest(
      app_joint_qdesn_phase155_resolve_source_dir(source_map$source_dir[[ii]]),
      source_map$source_block_id[[ii]]
    )
  }))
  extra_metrics <- app_joint_qdesn_phase155_aggregate_source_metrics(case_summary)

  idx <- match(case_summary$case_id, extra_metrics$case_id)
  if (anyNA(idx)) stop("Phase155 could not match all source metric rows.", call. = FALSE)
  for (name in setdiff(names(extra_metrics), c("case_id", "source_block_id"))) {
    case_summary[[name]] <- extra_metrics[[name]][idx]
  }
  assessment_idx <- match(case_summary$case_id, case_assessment$case_id)
  audit_idx <- match(case_summary$case_id, case_audit$case_id)
  if (anyNA(assessment_idx) || anyNA(audit_idx)) {
    stop("Phase155 could not match final assessment rows.", call. = FALSE)
  }
  for (name in c(
    "implementation_status", "distance_status", "chain_status",
    "raw_crossing_status", "gate_status", "status_reason"
  )) case_summary[[name]] <- case_assessment[[name]][assessment_idx]
  for (name in c("exact_control_match", "article_grade", "final_status")) {
    case_summary[[name]] <- case_audit[[name]][audit_idx]
  }

  models <- app_joint_qdesn_phase155_model_dictionary()
  scenarios <- app_joint_qdesn_phase155_scenario_dictionary()
  model_idx <- match(case_summary$source_model_id, models$source_model_id)
  scenario_idx <- match(case_summary$scenario_id, scenarios$scenario_id)
  if (anyNA(model_idx) || anyNA(scenario_idx)) {
    stop("Phase155 found an unknown scenario or model id.", call. = FALSE)
  }
  case_summary$model_label <- models$model_label[model_idx]
  case_summary$short_label <- models$short_label[model_idx]
  case_summary$model_order <- models$model_order[model_idx]
  case_summary$scenario_label <- scenarios$scenario_label[scenario_idx]
  case_summary$mechanism_detail <- scenarios$mechanism_detail[scenario_idx]
  case_summary$scenario_order <- scenarios$scenario_order[scenario_idx]
  case_summary <- case_summary[order(case_summary$scenario_order, case_summary$model_order), , drop = FALSE]
  rownames(case_summary) <- NULL

  list(
    phase154_dir = phase154_dir,
    phase153_dir = phase153_dir,
    phase154_manifest = phase154_manifest,
    phase153_manifest = phase153_manifest,
    phase154_source_manifest = phase154_source_manifest,
    source_manifests = source_manifests,
    case_summary = case_summary,
    case_assessment = case_assessment,
    case_audit = case_audit,
    final_assessment = final_assessment,
    phase153_assessment = phase153_assessment,
    phase153_contrasts = phase153_contrasts
  )
}

app_joint_qdesn_phase155_source_gate <- function(src) {
  x <- src$case_summary
  expected <- as.vector(outer(
    app_joint_qdesn_phase155_scenario_dictionary()$scenario_id,
    app_joint_qdesn_phase155_model_dictionary()$source_model_id,
    paste,
    sep = "::"
  ))
  cells <- paste(x$scenario_id, x$source_model_id, sep = "::")
  finite_cols <- c(
    "mcmc_fit_truth_mae", "mcmc_forecast_truth_mae",
    "mcmc_forecast_check_loss_mean", "mcmc_forecast_crps_grid",
    "mcmc_mean_abs_hit_rate_error", "max_chain_qhat_normalized_distance"
  )
  checks <- c(
    all(src$phase154_manifest$verified),
    all(src$phase153_manifest$verified),
    all(as.logical(src$phase154_source_manifest$verified)),
    all(src$source_manifests$verified),
    nrow(x) == 32L,
    !anyDuplicated(cells),
    setequal(cells, expected),
    all(vapply(x[finite_cols], function(z) all(is.finite(as.numeric(z))), logical(1L))),
    all(as.logical(x$exact_control_match)),
    all(as.logical(x$article_grade)),
    all(as.logical(x$all_chain_init_source_provided)),
    all(as.logical(x$mcmc_draws_all_finite)),
    all(x$implementation_status == "pass"),
    all(x$distance_status == "pass"),
    all(x$chain_status == "pass"),
    all(x$mcmc_forecast_contract_crossing_pairs == 0L),
    !any(x$final_status == "fail"),
    identical(as.character(src$final_assessment$recommendation[[1L]]), "build_article_assets_from_phase154_final_evidence"),
    as.integer(src$phase153_assessment$completed_candidates[[1L]]) == 1600L,
    as.integer(src$phase153_assessment$remaining_candidates[[1L]]) == 0L
  )
  if (all(checks)) "pass" else "fail"
}

app_joint_qdesn_phase155_metric_winners <- function(case_summary) {
  metrics <- c(
    mcmc_fit_truth_mae = "Fit MAE",
    mcmc_forecast_truth_mae = "Forecast MAE",
    mcmc_forecast_check_loss_mean = "Check loss",
    mcmc_forecast_crps_grid = "aCRPS"
  )
  rows <- lapply(unique(case_summary$scenario_id), function(scenario_id) {
    block <- case_summary[case_summary$scenario_id == scenario_id, , drop = FALSE]
    lapply(names(metrics), function(metric) {
      ord <- order(as.numeric(block[[metric]]), block$model_order)
      best <- block[ord[[1L]], , drop = FALSE]
      second <- block[ord[[2L]], , drop = FALSE]
      data.frame(
        scenario_id = scenario_id,
        scenario_label = best$scenario_label[[1L]],
        metric = metric,
        metric_label = unname(metrics[[metric]]),
        best_source_model_id = best$source_model_id[[1L]],
        best_model_label = best$model_label[[1L]],
        best_value = as.numeric(best[[metric]][[1L]]),
        second_source_model_id = second$source_model_id[[1L]],
        second_model_label = second$model_label[[1L]],
        second_value = as.numeric(second[[metric]][[1L]]),
        best_margin = as.numeric(second[[metric]][[1L]] - best[[metric]][[1L]]),
        stringsAsFactors = FALSE
      )
    })
  })
  app_joint_qdesn_bind_rows(unlist(rows, recursive = FALSE))
}

app_joint_qdesn_phase155_main_table_data <- function(case_summary) {
  models <- app_joint_qdesn_phase155_model_dictionary()
  scenarios <- app_joint_qdesn_phase155_scenario_dictionary()
  winners <- app_joint_qdesn_phase155_metric_winners(case_summary)
  winners <- winners[winners$metric == "mcmc_forecast_truth_mae", , drop = FALSE]
  rows <- lapply(seq_len(nrow(scenarios)), function(ii) {
    scenario <- scenarios[ii, , drop = FALSE]
    block <- case_summary[case_summary$scenario_id == scenario$scenario_id[[1L]], , drop = FALSE]
    out <- data.frame(
      scenario_id = scenario$scenario_id[[1L]],
      scenario_label = scenario$scenario_label[[1L]],
      mechanism_detail = scenario$mechanism_detail[[1L]],
      stringsAsFactors = FALSE
    )
    for (jj in seq_len(nrow(models))) {
      model_id <- models$source_model_id[[jj]]
      row <- block[block$source_model_id == model_id, , drop = FALSE]
      prefix <- model_id
      out[[paste0(prefix, "__forecast_mae")]] <- row$mcmc_forecast_truth_mae[[1L]]
      out[[paste0(prefix, "__fit_mae")]] <- row$mcmc_fit_truth_mae[[1L]]
      out[[paste0(prefix, "__raw_forecast_crossings")]] <- row$mcmc_forecast_raw_crossing_pairs[[1L]]
    }
    win <- winners[winners$scenario_id == scenario$scenario_id[[1L]], , drop = FALSE]
    out$winner_source_model_id <- win$best_source_model_id[[1L]]
    out$winner_model_label <- win$best_model_label[[1L]]
    out$winner_margin <- win$best_margin[[1L]]
    out
  })
  app_joint_qdesn_bind_rows(rows)
}

app_joint_qdesn_phase155_write_main_table <- function(data, path) {
  models <- app_joint_qdesn_phase155_model_dictionary()
  app_ensure_dir(dirname(path))
  headers <- c(
    "\\shortstack{Joint QDESN\\\\\\(\\AL\\)--\\RHS}",
    "\\shortstack{Independent QDESN\\\\\\(\\AL\\)--\\RHS}",
    "\\shortstack{Joint exQDESN\\\\\\(\\exAL\\)--\\RHS}",
    "\\shortstack{Independent exQDESN\\\\\\(\\exAL\\)--\\RHS}"
  )
  body <- vapply(seq_len(nrow(data)), function(ii) {
    cells <- vapply(seq_len(nrow(models)), function(jj) {
      model_id <- models$source_model_id[[jj]]
      value <- sprintf(
        "%s (%s; %s)",
        app_joint_qdesn_phase155_fmt_num(data[[paste0(model_id, "__forecast_mae")]][[ii]], 3L),
        app_joint_qdesn_phase155_fmt_num(data[[paste0(model_id, "__fit_mae")]][[ii]], 3L),
        app_joint_qdesn_phase155_fmt_int(data[[paste0(model_id, "__raw_forecast_crossings")]][[ii]])
      )
      if (identical(model_id, data$winner_source_model_id[[ii]])) value <- sprintf("\\textbf{%s}", value)
      value
    }, character(1L))
    paste(
      c(
        app_joint_qdesn_phase155_latex_escape(data$scenario_label[[ii]]),
        app_joint_qdesn_phase155_latex_escape(data$mechanism_detail[[ii]]),
        cells
      ),
      collapse = " & "
    )
  }, character(1L))
  lines <- c(
    "% Generated by application/scripts/187_build_joint_qdesn_phase155_article_assets.R.",
    "% Source: archived Phase 154 balanced MCMC evidence.",
    "\\begin{table}[!htbp]",
    "\\centering",
    "\\scriptsize",
    "\\resizebox{\\textwidth}{!}{%",
    "\\begin{tabular}{@{}>{\\raggedright\\arraybackslash}p{0.20\\textwidth}>{\\raggedright\\arraybackslash}p{0.30\\textwidth}rrrr@{}}",
    "\\toprule",
    paste(c("Scenario", "Mechanism", headers), collapse = " & "),
    "\\\\",
    "\\midrule",
    paste0(body, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}",
    "}%",
    paste0(
      "\\caption{Scenario-level MCMC confirmation for the joint multi-quantile validation study. ",
      "Entries are forecast MAE with fit-window MAE and the number of raw forecast-window adjacent-level crossings in parentheses, written as forecast MAE (fit MAE; raw crossings). ",
      "Boldface marks the lowest forecast MAE within each scenario. QDESN uses the \\(\\AL\\) working likelihood, exQDESN uses the \\(\\exAL\\) working likelihood, and \\RHS{} denotes the regularized horseshoe prior. ",
      "All scores use the monotone quantile-grid reporting rule; raw crossings are retained only as pre-rearrangement diagnostics.}"
    ),
    "\\label{tab:joint-qdesn-article-validation-mcmc-balanced-model-summary}",
    "\\end{table}"
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_phase155_winner_table <- function(winners) {
  metrics <- c("Fit MAE", "Forecast MAE", "Check loss", "aCRPS")
  rows <- lapply(unique(winners$scenario_id), function(scenario_id) {
    block <- winners[winners$scenario_id == scenario_id, , drop = FALSE]
    values <- setNames(rep("--", length(metrics)), metrics)
    for (ii in seq_len(nrow(block))) {
      values[[block$metric_label[[ii]]]] <- sprintf(
        "%s (%s)",
        block$best_model_label[[ii]],
        app_joint_qdesn_phase155_fmt_num(block$best_value[[ii]], 3L)
      )
    }
    data.frame(
      Scenario = block$scenario_label[[1L]],
      `Fit MAE` = values[["Fit MAE"]],
      `Forecast MAE` = values[["Forecast MAE"]],
      `Check loss` = values[["Check loss"]],
      aCRPS = values[["aCRPS"]],
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  app_joint_qdesn_bind_rows(rows)
}

app_joint_qdesn_phase155_replication_table <- function(contrasts) {
  keep <- contrasts$metric == "forecast_truth_mae" & (
    (contrasts$model_a == "joint_qdesn_rhs_vb" & contrasts$model_b == "joint_exqdesn_rhs_vb") |
      (contrasts$model_a == "qdesn_rhs_independent_vb" & contrasts$model_b == "exqdesn_rhs_independent_vb")
  )
  x <- contrasts[keep, , drop = FALSE]
  scenarios <- app_joint_qdesn_phase155_scenario_dictionary()
  rows <- lapply(seq_len(nrow(scenarios)), function(ii) {
    scenario_id <- scenarios$scenario_id[[ii]]
    block <- x[x$base_scenario_id == scenario_id, , drop = FALSE]
    joint <- block[block$model_a == "joint_qdesn_rhs_vb", , drop = FALSE]
    independent <- block[block$model_a == "qdesn_rhs_independent_vb", , drop = FALSE]
    if (nrow(joint) != 1L || nrow(independent) != 1L) {
      stop(sprintf("Missing Phase153 AL/exAL contrast for '%s'.", scenario_id), call. = FALSE)
    }
    data.frame(
      Scenario = scenarios$scenario_label[[ii]],
      `Joint: AL-exAL` = sprintf(
        "%s (%d%%)",
        app_joint_qdesn_phase155_fmt_num(joint$median_delta[[1L]], 3L),
        round(100 * joint$model_a_win_fraction[[1L]])
      ),
      `Independent: AL-exAL` = sprintf(
        "%s (%d%%)",
        app_joint_qdesn_phase155_fmt_num(independent$median_delta[[1L]], 3L),
        round(100 * independent$model_a_win_fraction[[1L]])
      ),
      Replicates = as.integer(joint$n_replicates[[1L]]),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  app_joint_qdesn_bind_rows(rows)
}

app_joint_qdesn_phase155_model_summary <- function(case_summary) {
  models <- app_joint_qdesn_phase155_model_dictionary()
  rows <- lapply(seq_len(nrow(models)), function(ii) {
    model <- models[ii, , drop = FALSE]
    block <- case_summary[case_summary$source_model_id == model$source_model_id[[1L]], , drop = FALSE]
    data.frame(
      source_model_id = model$source_model_id[[1L]],
      model_label = model$model_label[[1L]],
      n_cases = nrow(block),
      n_pass = sum(block$final_status == "pass"),
      n_review = sum(block$final_status == "review"),
      n_fail = sum(block$final_status == "fail"),
      median_fit_mae = stats::median(block$mcmc_fit_truth_mae),
      median_forecast_mae = stats::median(block$mcmc_forecast_truth_mae),
      median_check_loss = stats::median(block$mcmc_forecast_check_loss_mean),
      median_grid_crps = stats::median(block$mcmc_forecast_crps_grid),
      mean_abs_hit_rate_error = mean(block$mcmc_mean_abs_hit_rate_error),
      raw_forecast_crossings = sum(block$mcmc_forecast_raw_crossing_pairs),
      contract_forecast_crossings = sum(block$mcmc_forecast_contract_crossing_pairs),
      max_chain_qhat_normalized_distance = max(block$max_chain_qhat_normalized_distance),
      stringsAsFactors = FALSE
    )
  })
  app_joint_qdesn_bind_rows(rows)
}

app_joint_qdesn_phase155_gate_summary <- function(src, winners) {
  x <- src$case_summary
  winner_counts <- table(factor(
    winners$best_source_model_id[winners$metric == "mcmc_forecast_truth_mae"],
    levels = app_joint_qdesn_phase155_model_dictionary()$source_model_id
  ))
  data.frame(
    gate = c(
      "phase154_final_manifest", "phase154_source_manifests",
      "phase153_replication_manifest", "balanced_grid", "exact_controls",
      "article_grade_effort", "finite_outputs", "vb_initialization",
      "post_rearrangement_crossings", "raw_forecast_crossings", "chain_stability",
      "article_update"
    ),
    status = c(
      ifelse(all(src$phase154_manifest$verified), "pass", "fail"),
      ifelse(all(as.logical(src$phase154_source_manifest$verified)) && all(src$source_manifests$verified), "pass", "fail"),
      ifelse(all(src$phase153_manifest$verified), "pass", "fail"),
      ifelse(nrow(x) == 32L && length(unique(x$scenario_id)) == 8L && length(unique(x$source_model_id)) == 4L, "pass", "fail"),
      ifelse(all(as.logical(x$exact_control_match)), "pass", "fail"),
      ifelse(all(as.logical(x$article_grade)), "pass", "fail"),
      ifelse(all(as.logical(x$mcmc_draws_all_finite)) && all(is.finite(x$mcmc_forecast_truth_mae)), "pass", "fail"),
      ifelse(all(as.logical(x$all_chain_init_source_provided)), "pass", "fail"),
      ifelse(sum(x$mcmc_forecast_contract_crossing_pairs) == 0L, "pass", "fail"),
      ifelse(sum(x$mcmc_forecast_raw_crossing_pairs) > 0L, "review", "pass"),
      ifelse(all(x$chain_status == "pass"), "pass", "fail"),
      ifelse(identical(app_joint_qdesn_phase155_source_gate(src), "pass"), "review", "fail")
    ),
    detail = c(
      sprintf("%d/%d final evidence-set hashes verified.", sum(src$phase154_manifest$verified), nrow(src$phase154_manifest)),
      sprintf("%d/%d nested source hashes verified.", sum(src$source_manifests$verified), nrow(src$source_manifests)),
      sprintf("%d/%d replicated-VB hashes verified.", sum(src$phase153_manifest$verified), nrow(src$phase153_manifest)),
      "All 32 scenario-model comparisons are present exactly once.",
      sprintf("%d/32 comparisons match the pre-specified scenario-specific controls.", sum(as.logical(x$exact_control_match))),
      sprintf("%d/32 comparisons meet the pre-specified model-specific MCMC effort tier.", sum(as.logical(x$article_grade))),
      "All retained draws and reported quantile-grid scores are finite.",
      sprintf("%d/32 MCMC comparisons record provided VB/VB-LD initialization.", sum(as.logical(x$all_chain_init_source_provided))),
      sprintf("%d scored forecast-grid crossings after the monotone rearrangement.", sum(x$mcmc_forecast_contract_crossing_pairs)),
      sprintf("%d raw forecast-window adjacent-level crossings: Joint AL=%d, Independent AL=%d, Joint exAL=%d, Independent exAL=%d.",
        sum(x$mcmc_forecast_raw_crossing_pairs),
        sum(x$mcmc_forecast_raw_crossing_pairs[x$source_model_id == "joint_qdesn_rhs_vb"]),
        sum(x$mcmc_forecast_raw_crossing_pairs[x$source_model_id == "qdesn_rhs_independent_vb"]),
        sum(x$mcmc_forecast_raw_crossing_pairs[x$source_model_id == "joint_exqdesn_rhs_vb"]),
        sum(x$mcmc_forecast_raw_crossing_pairs[x$source_model_id == "exqdesn_rhs_independent_vb"])),
      sprintf("All case-level chain diagnostics pass; maximum chain-to-pooled quantile-grid distance is %.4f.", max(x$max_chain_qhat_normalized_distance)),
      sprintf("Article update is supported with review language; forecast-MAE lowest-score counts are %s.", paste(as.integer(winner_counts), collapse = "/"))
    ),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase155_protocol_table <- function(src) {
  data.frame(
    Item = c(
      "Validation components", "Synthetic mechanisms", "Model comparison",
      "Quantile grid", "Fit window", "Forecast protocol", "MCMC effort",
      "Reported quantile-grid summary", "Replicated robustness check"
    ),
    Value = c(
      "Scenario-specific VB and VB-LD calibration and initialization, followed by exact-control MCMC confirmation.",
      "Eight mechanisms: three bridge cases and five stress cases with known conditional quantile paths.",
      "Joint and independent quantile regressions under AL (QDESN) and exAL (exQDESN), all with the regularized horseshoe prior.",
      "0.05, 0.10, 0.25, 0.50, 0.75, 0.90, and 0.95.",
      "500 observations after the pre-specified DESN washout.",
      "No-refit held-out forecasts at origins separated by 30 observations, scored at leads 1-30.",
      "Four chains and 3,000 retained draws per AL case; eight chains and 12,000 retained draws per exAL case.",
      "Scores evaluate posterior quantile-grid summaries after the pre-specified monotone rule; raw crossings remain diagnostics.",
      sprintf("The replicated robustness check uses %d independent replicated VB fits: 50 replicates for each of 32 scenario-model comparisons.", as.integer(src$phase153_assessment$completed_candidates[[1L]]))
    ),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase155_claim_audit <- function(case_summary, winners, src) {
  forecast <- winners[winners$metric == "mcmc_forecast_truth_mae", , drop = FALSE]
  fit <- winners[winners$metric == "mcmc_fit_truth_mae", , drop = FALSE]
  count <- function(x, id) sum(x$best_source_model_id == id)
  data.frame(
    claim_id = c(
      "balanced_mcmc_grid", "forecast_winner_pattern", "fit_winner_pattern",
      "raw_crossing_pattern", "post_rearrangement_crossings", "chain_output_stability",
      "replicated_vb_scope", "exal_interpretation", "reported_quantile_grid"
    ),
    status = c("pass", "pass", "pass", "review", "pass", "pass", "pass", "pass", "pass"),
    evidence = c(
      sprintf("%d scenario-model comparisons; %d exact-control and %d article-grade.", nrow(case_summary), sum(case_summary$exact_control_match), sum(case_summary$article_grade)),
      sprintf("Forecast-MAE lowest-score counts: Joint AL=%d, Independent AL=%d, Joint exAL=%d, Independent exAL=%d.", count(forecast, "joint_qdesn_rhs_vb"), count(forecast, "qdesn_rhs_independent_vb"), count(forecast, "joint_exqdesn_rhs_vb"), count(forecast, "exqdesn_rhs_independent_vb")),
      sprintf("Fit-MAE lowest-score counts: Joint AL=%d and Independent exAL=%d; the other rows have zero.", count(fit, "joint_qdesn_rhs_vb"), count(fit, "exqdesn_rhs_independent_vb")),
      sprintf("Raw forecast crossings total %d and are concentrated in Independent AL (%d of %d).", sum(case_summary$mcmc_forecast_raw_crossing_pairs), sum(case_summary$mcmc_forecast_raw_crossing_pairs[case_summary$source_model_id == "qdesn_rhs_independent_vb"]), sum(case_summary$mcmc_forecast_raw_crossing_pairs)),
      sprintf("Forecast crossings after monotone rearrangement=%d.", sum(case_summary$mcmc_forecast_contract_crossing_pairs)),
      sprintf("All chain diagnostics pass; max chain-to-pooled quantile-grid distance=%.4f.", max(case_summary$max_chain_qhat_normalized_distance)),
      sprintf("Phase153 completed %d independent VB fits with zero implementation failures and zero crossings after monotone rearrangement.", src$phase153_assessment$completed_candidates[[1L]]),
      "The exAL rows are valid confirmation rows but do not dominate AL in quantile-path accuracy; they should not be described as uniformly superior.",
      "All claims concern posterior quantile grids, check loss, finite-grid aCRPS, hit-rate error, and crossing diagnostics, not a unique scalar predictive density."
    ),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase155_write_wrapper <- function(paths, path, description) {
  app_ensure_dir(dirname(path))
  rel <- vapply(paths, app_prefer_repo_relative_path, character(1L))
  writeLines(c(
    "% Generated by application/scripts/187_build_joint_qdesn_phase155_article_assets.R.",
    sprintf("%% %s", description),
    sprintf("\\input{%s}", rel)
  ), path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_run_phase155_article_promotion <- function(
  phase154_dir = app_joint_qdesn_phase154_default_final_dir(),
  phase153_dir = app_joint_qdesn_phase153_default_vb_dir(),
  tables_dir = app_path("tables"),
  out_dir = app_joint_qdesn_phase155_default_dir()
) {
  tables_dir <- normalizePath(tables_dir, winslash = "/", mustWork = TRUE)
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  app_ensure_dir(out_dir)
  src <- app_joint_qdesn_phase155_load(phase154_dir, phase153_dir)
  if (!identical(app_joint_qdesn_phase155_source_gate(src), "pass")) {
    stop("Phase155 source verification failed; article assets were not modified.", call. = FALSE)
  }

  case_summary <- src$case_summary
  winners <- app_joint_qdesn_phase155_metric_winners(case_summary)
  main_data <- app_joint_qdesn_phase155_main_table_data(case_summary)
  model_summary <- app_joint_qdesn_phase155_model_summary(case_summary)
  winner_table <- app_joint_qdesn_phase155_winner_table(winners)
  replication_table <- app_joint_qdesn_phase155_replication_table(src$phase153_contrasts)
  gate_summary <- app_joint_qdesn_phase155_gate_summary(src, winners)
  gate_table <- gate_summary[, c("gate", "status", "detail"), drop = FALSE]
  gate_labels <- c(
    phase154_final_manifest = "final MCMC evidence-set manifest",
    phase154_source_manifests = "MCMC source manifests",
    phase153_replication_manifest = "replicated VB manifest"
  )
  gate_table$gate <- ifelse(
    gate_table$gate %in% names(gate_labels),
    unname(gate_labels[gate_table$gate]),
    gsub("_", " ", gate_table$gate, fixed = TRUE)
  )
  names(gate_table) <- c("Criterion", "Status", "Detail")
  protocol <- app_joint_qdesn_phase155_protocol_table(src)
  claim_audit <- app_joint_qdesn_phase155_claim_audit(case_summary, winners, src)

  table_paths <- c(
    protocol_csv = app_joint_qdesn_phase155_write_csv(protocol, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_protocol.csv")),
    protocol_tex = app_joint_qdesn_phase155_write_latex_table(
      protocol,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_protocol.tex"),
      "Protocol for the balanced joint multi-quantile validation. VB and VB-LD select scenario-specific specifications and initialize MCMC; MCMC supplies the reported quantile-grid summaries.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-protocol",
      "@{}>{\\raggedright\\arraybackslash}p{0.23\\textwidth}>{\\raggedright\\arraybackslash}p{0.67\\textwidth}@{}",
      size = "\\small"
    ),
    model_csv = app_joint_qdesn_phase155_write_csv(main_data, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_model_summary.csv")),
    model_tex = app_joint_qdesn_phase155_write_main_table(main_data, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_model_summary.tex")),
    scenario_csv = app_joint_qdesn_phase155_write_csv(case_summary, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_scenario_summary.csv")),
    gate_csv = app_joint_qdesn_phase155_write_csv(gate_summary, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_gate_summary.csv")),
    gate_tex = app_joint_qdesn_phase155_write_latex_table(
      gate_table,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_gate_summary.tex"),
      "Reproducibility checks and diagnostic criteria for the balanced MCMC confirmation evidence set. Review denotes retained raw-crossing diagnostics, not a failure of the scored monotone quantile grid.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-criteria-summary",
      "@{}>{\\raggedright\\arraybackslash}p{0.23\\textwidth}l>{\\raggedright\\arraybackslash}p{0.60\\textwidth}@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    winner_csv = app_joint_qdesn_phase155_write_csv(winners, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_winner_summary.csv")),
    winner_tex = app_joint_qdesn_phase155_write_latex_table(
      winner_table,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_winner_summary.tex"),
      "Lowest MCMC value within each scenario and metric. The winning model varies by metric and mechanism; the table is a diagnostic summary rather than evidence for a universal ordering.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-winner-summary",
      "@{}>{\\raggedright\\arraybackslash}p{0.20\\textwidth}>{\\raggedright\\arraybackslash}p{0.18\\textwidth}>{\\raggedright\\arraybackslash}p{0.18\\textwidth}>{\\raggedright\\arraybackslash}p{0.18\\textwidth}>{\\raggedright\\arraybackslash}p{0.18\\textwidth}@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    replication_csv = app_joint_qdesn_phase155_write_csv(replication_table, file.path(tables_dir, "joint_qdesn_article_validation_phase153_replication_summary.csv")),
    replication_tex = app_joint_qdesn_phase155_write_latex_table(
      replication_table,
      file.path(tables_dir, "joint_qdesn_article_validation_phase153_replication_summary.tex"),
      "Replicated VB comparison of AL and exAL forecast quantile-path MAE over 50 independent data-generating realizations per scenario. Entries are the median paired difference AL minus exAL, with the percentage of replicates favoring AL in parentheses. Negative differences favor AL. These rows assess robustness of the pre-specified specifications; they are not the reported MCMC estimates.",
      "tab:joint-qdesn-article-validation-phase153-replication-summary",
      "@{}>{\\raggedright\\arraybackslash}p{0.30\\textwidth}rrr@{}",
      size = "\\scriptsize"
    )
  )
  table_paths[["scenario_tex"]] <- app_joint_qdesn_phase155_write_wrapper(
    table_paths[["model_tex"]],
    file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_scenario_summary.tex"),
    "Compatibility alias for the Phase155 scenario-level main table."
  )
  table_paths[["main_wrapper"]] <- app_joint_qdesn_phase155_write_wrapper(
    table_paths[["model_tex"]],
    file.path(tables_dir, "joint_qdesn_article_validation_tables.tex"),
    "Compact Phase155 balanced MCMC article table."
  )
  table_paths[["provenance_wrapper"]] <- app_joint_qdesn_phase155_write_wrapper(
    table_paths[c("protocol_tex", "gate_tex", "winner_tex", "replication_tex")],
    file.path(tables_dir, "joint_qdesn_article_validation_provenance_tables.tex"),
    "Phase155 protocol, diagnostic, metric-specific, and replicated-VB tables."
  )

  asset_paths <- table_paths
  asset_manifest <- data.frame(
    label = names(asset_paths),
    artifact_type = ifelse(grepl("\\.tex$", asset_paths), "latex_table", "csv_table"),
    path = vapply(asset_paths, app_prefer_repo_relative_path, character(1L)),
    size_bytes = as.numeric(file.info(asset_paths)$size),
    sha256 = vapply(asset_paths, app_sha256_file, character(1L)),
    source_phase154_dir = app_prefer_repo_relative_path(src$phase154_dir),
    source_phase153_dir = app_prefer_repo_relative_path(src$phase153_dir),
    source_validation_contract = "posterior_quantile_grid_with_monotone_scoring_contract",
    stringsAsFactors = FALSE
  )
  asset_manifest_path <- app_joint_qdesn_phase155_write_csv(
    asset_manifest,
    file.path(tables_dir, "joint_qdesn_article_validation_asset_manifest.csv")
  )

  promotion <- data.frame(
    phase_id = "phase155_article_promotion",
    gate_status = "review",
    hard_implementation_gate = "pass",
    mcmc_cells = nrow(case_summary),
    phase153_vb_fits = as.integer(src$phase153_assessment$completed_candidates[[1L]]),
    contract_forecast_crossings = sum(case_summary$mcmc_forecast_contract_crossing_pairs),
    raw_forecast_crossings = sum(case_summary$mcmc_forecast_raw_crossing_pairs),
    article_assets_modified = TRUE,
    recommendation = "integrate_phase155_tables_with_scoped_interpretation",
    next_scientific_action = "freeze_current_validation_evidence; do_not_launch_additional_sampler_runs solely for article promotion",
    stringsAsFactors = FALSE
  )
  run_config <- data.frame(
    run_id = "joint_qdesn_phase155_article_promotion",
    phase154_dir = src$phase154_dir,
    phase153_dir = src$phase153_dir,
    tables_dir = tables_dir,
    output_dir = out_dir,
    mcmc_cells = nrow(case_summary),
    phase153_vb_fits = promotion$phase153_vb_fits[[1L]],
    source_gate = app_joint_qdesn_phase155_source_gate(src),
    validation_contract = "posterior_quantile_grid_with_monotone_scoring_contract",
    scalar_predictive_density_claim = FALSE,
    created_at = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
    stringsAsFactors = FALSE
  )
  readme_path <- file.path(out_dir, "README.md")
  writeLines(c(
    "# Joint QDESN Phase 155 Article Update",
    "",
    "Phase 155 rebuilds reported joint-validation tables from the archived Phase 154 balanced MCMC evidence set and the Phase 153 replicated VB robustness evidence set.",
    "",
    sprintf("- Phase 154 MCMC cells: `%d/32`", nrow(case_summary)),
    sprintf("- Phase 153 independent VB fits: `%d/1600`", promotion$phase153_vb_fits[[1L]]),
    sprintf("- Forecast crossings after monotone rearrangement: `%d`", promotion$contract_forecast_crossings[[1L]]),
    sprintf("- Raw forecast crossings retained for review: `%d`", promotion$raw_forecast_crossings[[1L]]),
    "- No model fitting or score recomputation occurs in this stage.",
    "- Main claims remain restricted to posterior quantile-grid validation."
  ), readme_path, useBytes = TRUE)

  cache_paths <- c(
    run_config = app_joint_qdesn_phase155_write_csv(run_config, file.path(out_dir, "run_config.csv")),
    phase154_manifest_verification = app_joint_qdesn_phase155_write_csv(src$phase154_manifest, file.path(out_dir, "phase154_manifest_verification.csv")),
    phase154_source_manifest_verification = app_joint_qdesn_phase155_write_csv(src$phase154_source_manifest, file.path(out_dir, "phase154_source_manifest_verification.csv")),
    direct_source_manifest_verification = app_joint_qdesn_phase155_write_csv(src$source_manifests, file.path(out_dir, "direct_source_manifest_verification.csv")),
    phase153_manifest_verification = app_joint_qdesn_phase155_write_csv(src$phase153_manifest, file.path(out_dir, "phase153_manifest_verification.csv")),
    final_case_summary = app_joint_qdesn_phase155_write_csv(case_summary, file.path(out_dir, "final_case_summary.csv")),
    model_summary = app_joint_qdesn_phase155_write_csv(model_summary, file.path(out_dir, "model_summary.csv")),
    scenario_winner_summary = app_joint_qdesn_phase155_write_csv(winners, file.path(out_dir, "scenario_winner_summary.csv")),
    phase153_replication_summary = app_joint_qdesn_phase155_write_csv(replication_table, file.path(out_dir, "phase153_replication_summary.csv")),
    gate_summary = app_joint_qdesn_phase155_write_csv(gate_summary, file.path(out_dir, "gate_summary.csv")),
    article_claim_audit = app_joint_qdesn_phase155_write_csv(claim_audit, file.path(out_dir, "article_claim_audit.csv")),
    promotion_assessment = app_joint_qdesn_phase155_write_csv(promotion, file.path(out_dir, "promotion_assessment.csv")),
    article_asset_manifest = app_joint_qdesn_phase155_write_csv(asset_manifest, file.path(out_dir, "article_asset_manifest.csv")),
    provenance = app_joint_qdesn_phase155_write_csv(app_joint_qvp_provenance_rows(), file.path(out_dir, "provenance.csv")),
    readme = normalizePath(readme_path, winslash = "/", mustWork = TRUE)
  )
  old_manifest <- file.path(out_dir, "artifact_manifest.csv")
  if (file.exists(old_manifest)) unlink(old_manifest)
  manifest <- app_joint_qdesn_write_manifest(cache_paths, out_dir)

  list(
    out_dir = out_dir,
    tables_dir = tables_dir,
    source = src,
    case_summary = case_summary,
    model_summary = model_summary,
    winners = winners,
    main_table_data = main_data,
    gate_summary = gate_summary,
    claim_audit = claim_audit,
    promotion = promotion,
    article_asset_manifest = asset_manifest,
    paths = c(cache_paths, table_paths, article_asset_manifest = asset_manifest_path, artifact_manifest = manifest$manifest_path)
  )
}

app_joint_qdesn_phase155_verify_article_manifest <- function(path) {
  manifest <- app_read_csv(path)
  app_check_required_columns(manifest, c("label", "path", "size_bytes", "sha256"), "Phase155 article asset manifest")
  app_joint_qdesn_bind_rows(lapply(seq_len(nrow(manifest)), function(ii) {
    artifact <- if (grepl("^/", manifest$path[[ii]])) manifest$path[[ii]] else app_path(manifest$path[[ii]])
    exists <- file.exists(artifact)
    actual_sha <- if (exists) app_sha256_file(artifact) else NA_character_
    actual_size <- if (exists) as.numeric(file.info(artifact)$size) else NA_real_
    data.frame(
      label = manifest$label[[ii]],
      path = manifest$path[[ii]],
      exists = exists,
      declared_size_bytes = as.numeric(manifest$size_bytes[[ii]]),
      actual_size_bytes = actual_size,
      declared_sha256 = manifest$sha256[[ii]],
      actual_sha256 = actual_sha,
      verified = exists && identical(actual_size, as.numeric(manifest$size_bytes[[ii]])) && identical(tolower(actual_sha), tolower(manifest$sha256[[ii]])),
      stringsAsFactors = FALSE
    )
  }))
}

app_joint_qdesn_phase155_text_contains <- function(path, pattern) {
  if (!file.exists(path)) return(FALSE)
  grepl(pattern, paste(readLines(path, warn = FALSE), collapse = "\n"), fixed = TRUE)
}

app_joint_qdesn_run_phase155_article_audit <- function(
  phase155_dir = app_joint_qdesn_phase155_default_dir(),
  main_tex = app_path("main.tex"),
  supplement_tex = app_path("qdesn-supplement.tex"),
  out_dir = file.path(phase155_dir, "article_readiness_audit")
) {
  phase155_dir <- normalizePath(phase155_dir, winslash = "/", mustWork = TRUE)
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  app_ensure_dir(out_dir)
  artifact <- app_joint_qdesn_phase155_verify_manifest(phase155_dir, "phase155")
  assets <- app_joint_qdesn_phase155_verify_article_manifest(file.path(phase155_dir, "article_asset_manifest.csv"))
  claims <- app_read_csv(file.path(phase155_dir, "article_claim_audit.csv"))
  promotion <- app_read_csv(file.path(phase155_dir, "promotion_assessment.csv"))
  table_data <- app_read_csv(file.path(phase155_dir, "final_case_summary.csv"))

  manuscript <- data.frame(
    check = c(
      "mcmc_confirmation_named", "replicated_vb_layer_named",
      "forecast_winner_pattern_updated", "fit_winner_pattern_updated",
      "raw_crossing_scope_updated", "contract_crossings_reported",
      "predictive_contract_preserved", "supplement_wrapper_present",
      "stale_five_of_eight_removed", "stale_gamma_sensitivity_claim_removed"
    ),
    status = c(
      ifelse(app_joint_qdesn_phase155_text_contains(main_tex, "balanced MCMC confirmation"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase155_text_contains(main_tex, "50 independently generated fixtures"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase155_text_contains(main_tex, "four of the eight") && app_joint_qdesn_phase155_text_contains(main_tex, "two scenarios each"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase155_text_contains(main_tex, "six of the eight fit windows"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase155_text_contains(main_tex, "24 of the 25 raw forecast-window crossings"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase155_text_contains(main_tex, "zero crossings after the monotone reporting rule"), "pass", "fail"),
      ifelse(
        app_joint_qdesn_phase155_text_contains(main_tex, "quantile-grid readout paths") &&
          app_joint_qdesn_phase155_text_contains(main_tex, "scalar predictive density"),
        "pass",
        "fail"
      ),
      ifelse(app_joint_qdesn_phase155_text_contains(supplement_tex, "joint_qdesn_article_validation_provenance_tables.tex"), "pass", "fail"),
      ifelse(!app_joint_qdesn_phase155_text_contains(main_tex, "lowest-forecast-MAE row in five of the eight"), "pass", "fail"),
      ifelse(!app_joint_qdesn_phase155_text_contains(main_tex, "sampled-gamma exAL sensitivity rows"), "pass", "fail")
    ),
    stringsAsFactors = FALSE
  )
  data_checks <- data.frame(
    check = c(
      "phase155_manifest", "article_asset_manifest", "balanced_grid",
      "finite_scores", "exact_controls", "article_grade", "contract_crossings",
      "source_claim_audit", "promotion_gate"
    ),
    status = c(
      ifelse(all(artifact$verified), "pass", "fail"),
      ifelse(all(assets$verified), "pass", "fail"),
      ifelse(nrow(table_data) == 32L && length(unique(table_data$scenario_id)) == 8L && length(unique(table_data$source_model_id)) == 4L, "pass", "fail"),
      ifelse(all(is.finite(table_data$mcmc_forecast_truth_mae)), "pass", "fail"),
      ifelse(all(as.logical(table_data$exact_control_match)), "pass", "fail"),
      ifelse(all(as.logical(table_data$article_grade)), "pass", "fail"),
      ifelse(sum(table_data$mcmc_forecast_contract_crossing_pairs) == 0L, "pass", "fail"),
      ifelse(!any(claims$status == "fail"), "pass", "fail"),
      ifelse(identical(promotion$hard_implementation_gate[[1L]], "pass"), "pass", "fail")
    ),
    stringsAsFactors = FALSE
  )
  statuses <- c(manuscript$status, data_checks$status)
  audit_status <- if (any(statuses == "fail")) "fail" else if (any(claims$status == "review")) "review" else "pass"
  summary <- data.frame(
    phase_id = "phase155_article_readiness_audit",
    audit_status = audit_status,
    manifest_rows_verified = sum(artifact$verified),
    manifest_rows_total = nrow(artifact),
    article_assets_verified = sum(assets$verified),
    article_assets_total = nrow(assets),
    manuscript_checks_passed = sum(manuscript$status == "pass"),
    manuscript_checks_total = nrow(manuscript),
    failed_checks = sum(statuses == "fail"),
    recommendation = if (identical(audit_status, "fail")) "repair_before_article_use" else "phase155_article_assets_ready_with_raw_crossing_review_language",
    stringsAsFactors = FALSE
  )
  readme_path <- file.path(out_dir, "README.md")
  writeLines(c(
    "# Phase 155 Article Readiness Audit",
    "",
    sprintf("- Audit status: `%s`", audit_status),
    sprintf("- Cache hashes: `%d/%d`", summary$manifest_rows_verified[[1L]], summary$manifest_rows_total[[1L]]),
    sprintf("- Article assets: `%d/%d`", summary$article_assets_verified[[1L]], summary$article_assets_total[[1L]]),
    sprintf("- Manuscript checks: `%d/%d`", summary$manuscript_checks_passed[[1L]], summary$manuscript_checks_total[[1L]])
  ), readme_path, useBytes = TRUE)
  paths <- c(
    audit_summary = app_joint_qdesn_phase155_write_csv(summary, file.path(out_dir, "audit_summary.csv")),
    artifact_manifest_verification = app_joint_qdesn_phase155_write_csv(artifact, file.path(out_dir, "artifact_manifest_verification.csv")),
    article_asset_manifest_verification = app_joint_qdesn_phase155_write_csv(assets, file.path(out_dir, "article_asset_manifest_verification.csv")),
    manuscript_checks = app_joint_qdesn_phase155_write_csv(manuscript, file.path(out_dir, "manuscript_checks.csv")),
    data_checks = app_joint_qdesn_phase155_write_csv(data_checks, file.path(out_dir, "data_checks.csv")),
    provenance = app_joint_qdesn_phase155_write_csv(app_joint_qvp_provenance_rows(), file.path(out_dir, "provenance.csv")),
    readme = normalizePath(readme_path, winslash = "/", mustWork = TRUE)
  )
  old_manifest <- file.path(out_dir, "artifact_manifest.csv")
  if (file.exists(old_manifest)) unlink(old_manifest)
  manifest <- app_joint_qdesn_write_manifest(paths, out_dir)
  list(
    out_dir = out_dir,
    summary = summary,
    manuscript_checks = manuscript,
    data_checks = data_checks,
    paths = c(paths, artifact_manifest = manifest$manifest_path)
  )
}
