# Phase 126 article assets for the balanced joint QDESN MCMC validation.
#
# This stage consumes the frozen Phase 125 balanced MCMC audit.  It does not
# rerun VB, VB-LD, MCMC, fixture generation, or validation scoring.

app_joint_qdesn_default_phase126_article_assets_dir <- function() {
  app_path("application/cache/joint_qdesn_phase126_article_assets_20260712")
}

app_joint_qdesn_phase126_write_csv <- function(x, path) {
  app_ensure_dir(dirname(path))
  utils::write.csv(x, path, row.names = FALSE, na = "")
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_phase126_fmt_num <- function(x, digits = 3L) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  formatC(x[[1L]], format = "f", digits = digits)
}

app_joint_qdesn_phase126_fmt_int <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  if (!length(x) || !is.finite(x[[1L]])) return("--")
  formatC(round(x[[1L]]), format = "d", big.mark = ",")
}

app_joint_qdesn_phase126_latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

app_joint_qdesn_phase126_write_latex_table <- function(
  x,
  path,
  caption,
  label,
  align = NULL,
  size = "\\scriptsize",
  resize = FALSE,
  raw_latex_cols = character()
) {
  app_ensure_dir(dirname(path))
  if (is.null(align)) align <- paste0("@{}", paste(rep("l", ncol(x)), collapse = ""), "@{}")
  body <- lapply(seq_len(nrow(x)), function(ii) {
    cells <- unlist(x[ii, , drop = FALSE], use.names = FALSE)
    is_raw <- names(x) %in% raw_latex_cols
    cells[!is_raw] <- app_joint_qdesn_phase126_latex_escape(cells[!is_raw])
    paste(cells, collapse = " & ")
  })
  lines <- c(
    "% Generated by application/scripts/130_build_joint_qdesn_phase126_article_assets.R.",
    "\\begin{table}[!htbp]",
    "\\centering",
    size
  )
  if (isTRUE(resize)) lines <- c(lines, "\\resizebox{\\textwidth}{!}{%")
  lines <- c(
    lines,
    sprintf("\\begin{tabular}{%s}", align),
    "\\toprule",
    paste(app_joint_qdesn_phase126_latex_escape(names(x)), collapse = " & "),
    "\\\\",
    "\\midrule",
    paste0(body, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}"
  )
  if (isTRUE(resize)) lines <- c(lines, "}%")
  lines <- c(
    lines,
    sprintf("\\caption{%s}", caption),
    sprintf("\\label{%s}", label),
    "\\end{table}"
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_phase126_write_wrapper <- function(paths, path, header = "Joint QDESN Phase126 article validation tables.") {
  app_ensure_dir(dirname(path))
  rel <- vapply(paths, app_prefer_repo_relative_path, character(1L))
  writeLines(c(
    "% Generated by application/scripts/130_build_joint_qdesn_phase126_article_assets.R.",
    sprintf("%% %s", header),
    sprintf("\\input{%s}", rel)
  ), path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

app_joint_qdesn_phase126_verify_manifest <- function(dir, manifest_name = "artifact_manifest.csv", artifact_label = "artifact") {
  manifest_path <- file.path(dir, manifest_name)
  if (!file.exists(manifest_path)) {
    return(data.frame(
      artifact_label = artifact_label,
      label = manifest_name,
      relative_path = manifest_name,
      path = normalizePath(manifest_path, winslash = "/", mustWork = FALSE),
      exists = FALSE,
      declared_size_bytes = NA_real_,
      actual_size_bytes = NA_real_,
      declared_sha256 = NA_character_,
      actual_sha256 = NA_character_,
      status = "fail",
      stringsAsFactors = FALSE
    ))
  }
  manifest <- app_read_csv(manifest_path)
  app_check_required_columns(manifest, c("label", "relative_path", "size_bytes", "sha256"), artifact_label)
  app_bind_rows_fill(lapply(seq_len(nrow(manifest)), function(ii) {
    rel <- manifest$relative_path[[ii]]
    path <- if (grepl("^/", rel)) rel else file.path(dir, rel)
    exists <- file.exists(path)
    actual_sha <- if (exists) app_sha256_file(path) else NA_character_
    actual_size <- if (exists) as.numeric(file.info(path)$size) else NA_real_
    data.frame(
      artifact_label = artifact_label,
      label = manifest$label[[ii]],
      relative_path = rel,
      path = normalizePath(path, winslash = "/", mustWork = FALSE),
      exists = exists,
      declared_size_bytes = as.numeric(manifest$size_bytes[[ii]]),
      actual_size_bytes = actual_size,
      declared_sha256 = manifest$sha256[[ii]],
      actual_sha256 = actual_sha,
      status = if (exists &&
        identical(as.numeric(actual_size), as.numeric(manifest$size_bytes[[ii]])) &&
        identical(tolower(actual_sha), tolower(manifest$sha256[[ii]]))) "pass" else "fail",
      stringsAsFactors = FALSE
    )
  }))
}

app_joint_qdesn_phase126_verify_article_asset_manifest <- function(manifest_path) {
  if (!file.exists(manifest_path)) {
    return(data.frame(
      label = "article_asset_manifest",
      path = normalizePath(manifest_path, winslash = "/", mustWork = FALSE),
      exists = FALSE,
      status = "fail",
      stringsAsFactors = FALSE
    ))
  }
  manifest <- app_read_csv(manifest_path)
  app_check_required_columns(manifest, c("label", "path", "size_bytes", "sha256"), "Phase126 article asset manifest")
  app_bind_rows_fill(lapply(seq_len(nrow(manifest)), function(ii) {
    path <- manifest$path[[ii]]
    abs_path <- if (grepl("^/", path)) path else app_path(path)
    exists <- file.exists(abs_path)
    actual_sha <- if (exists) app_sha256_file(abs_path) else NA_character_
    actual_size <- if (exists) as.numeric(file.info(abs_path)$size) else NA_real_
    data.frame(
      label = manifest$label[[ii]],
      artifact_type = manifest$artifact_type[[ii]] %||% NA_character_,
      path = normalizePath(abs_path, winslash = "/", mustWork = FALSE),
      exists = exists,
      declared_size_bytes = as.numeric(manifest$size_bytes[[ii]]),
      actual_size_bytes = actual_size,
      declared_sha256 = manifest$sha256[[ii]],
      actual_sha256 = actual_sha,
      status = if (exists &&
        identical(as.numeric(actual_size), as.numeric(manifest$size_bytes[[ii]])) &&
        identical(tolower(actual_sha), tolower(manifest$sha256[[ii]]))) "pass" else "fail",
      stringsAsFactors = FALSE
    )
  }))
}

app_joint_qdesn_phase126_load_phase125 <- function(phase125_dir) {
  phase125_dir <- normalizePath(phase125_dir, winslash = "/", mustWork = TRUE)
  artifact_manifest <- app_joint_qdesn_phase126_verify_manifest(phase125_dir, "artifact_manifest.csv", "phase125_artifact")
  source_manifest <- app_read_csv(file.path(phase125_dir, "source_artifact_manifest_verification.csv"))
  vb_manifest <- app_read_csv(file.path(phase125_dir, "source_vb_freeze_manifest_verification.csv"))
  fixture_manifest <- app_read_csv(file.path(phase125_dir, "fixture_source_manifest_verification.csv"))
  gate <- app_read_csv(file.path(phase125_dir, "balanced_gate_summary.csv"))
  scope <- app_read_csv(file.path(phase125_dir, "balanced_scope_matrix.csv"))
  model <- app_read_csv(file.path(phase125_dir, "model_confirmation_summary.csv"))
  case <- app_read_csv(file.path(phase125_dir, "scenario_model_confirmation_summary.csv"))
  winners <- app_read_csv(file.path(phase125_dir, "scenario_winner_summary.csv"))
  raw_contract <- app_read_csv(file.path(phase125_dir, "raw_contract_crossing_summary.csv"))
  run_config <- app_read_csv(file.path(phase125_dir, "run_config.csv"))
  health <- app_read_csv(file.path(phase125_dir, "health_check_summary.csv"))
  recommendation <- app_read_csv(file.path(phase125_dir, "article_promotion_recommendation.csv"))

  app_check_required_columns(gate, c("gate", "status", "detail"), "Phase125 balanced gate summary")
  app_check_required_columns(scope, c("scenario_id", "source_model_id", "present_in_balanced_mcmc", "n_matching_rows"), "Phase125 balanced scope")
  app_check_required_columns(model, c(
    "model_label", "n_cases", "n_pass", "n_review", "n_fail",
    "mcmc_fit_truth_mae", "mcmc_forecast_truth_mae",
    "mcmc_forecast_check_loss", "mcmc_forecast_crps_grid",
    "mcmc_abs_hit_rate_error", "mcmc_forecast_raw_crossing_pairs",
    "mcmc_forecast_contract_crossing_pairs", "gate_status"
  ), "Phase125 model confirmation summary")
  app_check_required_columns(case, c(
    "scenario_id", "scenario_label", "model_label", "source_model_id",
    "mcmc_fit_truth_mae", "mcmc_forecast_truth_mae",
    "mcmc_forecast_check_loss_mean", "mcmc_forecast_raw_crossing_pairs",
    "mcmc_forecast_contract_crossing_pairs", "gate_status"
  ), "Phase125 scenario-model summary")
  app_check_required_columns(winners, c("scenario_id", "scenario_label", "metric", "best_model_label", "best_value"), "Phase125 scenario winner summary")
  app_check_required_columns(raw_contract, c(
    "source_model_id", "mcmc_forecast_raw_crossing_pairs",
    "mcmc_forecast_contract_crossing_pairs"
  ), "Phase125 raw/contract crossing summary")

  list(
    phase125_dir = phase125_dir,
    artifact_manifest_verification = artifact_manifest,
    source_artifact_manifest_verification = source_manifest,
    source_vb_freeze_manifest_verification = vb_manifest,
    fixture_source_manifest_verification = fixture_manifest,
    gate = gate,
    scope = scope,
    model = model,
    case = case,
    winners = winners,
    raw_contract = raw_contract,
    run_config = run_config,
    health = health,
    recommendation = recommendation
  )
}

app_joint_qdesn_phase126_source_gate <- function(src) {
  checks <- c(
    all(src$artifact_manifest_verification$status == "pass"),
    all(src$source_artifact_manifest_verification$status == "pass"),
    all(src$source_vb_freeze_manifest_verification$status == "pass"),
    all(src$fixture_source_manifest_verification$status == "pass"),
    all(src$scope$present_in_balanced_mcmc),
    all(src$scope$n_matching_rows == 1L),
    !any(src$gate$status == "fail"),
    identical(as.character(src$run_config$hard_implementation_gate[[1L]]), "pass")
  )
  if (all(checks)) "pass" else "fail"
}

app_joint_qdesn_phase126_model_order <- function(model_label) {
  match(model_label, c(
    "Joint QDESN RHS",
    "Independent QDESN RHS",
    "Joint exQDESN RHS",
    "Independent exQDESN RHS"
  ))
}

app_joint_qdesn_phase126_make_model_table <- function(model) {
  model <- model[order(app_joint_qdesn_phase126_model_order(model$model_label)), , drop = FALSE]
  data.frame(
    Model = model$model_label,
    Cases = vapply(model$n_cases, app_joint_qdesn_phase126_fmt_int, character(1L)),
    `Fit MAE` = vapply(model$mcmc_fit_truth_mae, app_joint_qdesn_phase126_fmt_num, character(1L), digits = 3),
    `Forecast MAE` = vapply(model$mcmc_forecast_truth_mae, app_joint_qdesn_phase126_fmt_num, character(1L), digits = 3),
    `Check loss` = vapply(model$mcmc_forecast_check_loss, app_joint_qdesn_phase126_fmt_num, character(1L), digits = 3),
    `Grid CRPS` = vapply(model$mcmc_forecast_crps_grid, app_joint_qdesn_phase126_fmt_num, character(1L), digits = 3),
    `Hit error` = vapply(model$mcmc_abs_hit_rate_error, app_joint_qdesn_phase126_fmt_num, character(1L), digits = 3),
    `Raw crossings` = vapply(model$mcmc_forecast_raw_crossing_pairs, app_joint_qdesn_phase126_fmt_int, character(1L)),
    `Contract crossings` = vapply(model$mcmc_forecast_contract_crossing_pairs, app_joint_qdesn_phase126_fmt_int, character(1L)),
    Gate = model$gate_status,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

app_joint_qdesn_phase126_make_scenario_table <- function(case, bold_winners = FALSE) {
  model_labels <- c("Joint QDESN RHS", "Independent QDESN RHS", "Joint exQDESN RHS", "Independent exQDESN RHS")
  rows <- lapply(unique(case$scenario_id), function(sc) {
    block <- case[case$scenario_id == sc & case$model_label %in% model_labels, , drop = FALSE]
    block <- block[order(app_joint_qdesn_phase126_model_order(block$model_label)), , drop = FALSE]
    min_mae <- min(block$mcmc_forecast_truth_mae, na.rm = TRUE)
    vals <- setNames(rep("--", length(model_labels)), model_labels)
    for (ii in seq_len(nrow(block))) {
      val <- sprintf(
        "%s (%s)",
        app_joint_qdesn_phase126_fmt_num(block$mcmc_forecast_truth_mae[[ii]], 3),
        app_joint_qdesn_phase126_fmt_num(block$mcmc_fit_truth_mae[[ii]], 3)
      )
      if (isTRUE(bold_winners) && isTRUE(all.equal(block$mcmc_forecast_truth_mae[[ii]], min_mae, tolerance = 1e-12))) {
        val <- sprintf("\\textbf{%s}", val)
      }
      vals[[block$model_label[[ii]]]] <- val
    }
    data.frame(
      Scenario = block$scenario_label[[1L]],
      `Joint QDESN` = vals[["Joint QDESN RHS"]],
      `Independent QDESN` = vals[["Independent QDESN RHS"]],
      `Joint exQDESN` = vals[["Joint exQDESN RHS"]],
      `Independent exQDESN` = vals[["Independent exQDESN RHS"]],
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  app_bind_rows_fill(rows)
}

app_joint_qdesn_phase126_make_gate_table <- function(gate) {
  keep <- gate$gate %in% c(
    "source_artifact_manifests", "source_vb_freeze_manifests",
    "fixture_source_manifests", "worker_failures", "balanced_grid_complete",
    "finite_mcmc_draws", "provided_vb_initialization", "contract_crossings",
    "raw_crossings", "chain_stability", "vb_mcmc_distance",
    "quantile_grid_predictive_contract", "article_asset_build_readiness"
  )
  out <- gate[keep, c("gate", "status", "detail"), drop = FALSE]
  out$gate <- gsub("_", " ", out$gate, fixed = TRUE)
  names(out) <- c("Gate", "Status", "Detail")
  out
}

app_joint_qdesn_phase126_make_winner_table <- function(winners) {
  metrics <- c(
    mcmc_fit_truth_mae = "Fit MAE",
    mcmc_forecast_truth_mae = "Forecast MAE",
    mcmc_forecast_check_loss_mean = "Check loss",
    crps_grid_mean = "Grid CRPS"
  )
  rows <- lapply(unique(winners$scenario_id), function(sc) {
    block <- winners[winners$scenario_id == sc & winners$metric %in% names(metrics), , drop = FALSE]
    vals <- setNames(rep("--", length(metrics)), unname(metrics))
    for (ii in seq_len(nrow(block))) {
      vals[[unname(metrics[block$metric[[ii]]])]] <- sprintf(
        "%s (%s)",
        block$best_model_label[[ii]],
        app_joint_qdesn_phase126_fmt_num(block$best_value[[ii]], 3)
      )
    }
    data.frame(
      Scenario = block$scenario_label[[1L]],
      `Fit MAE winner` = vals[["Fit MAE"]],
      `Forecast MAE winner` = vals[["Forecast MAE"]],
      `Check-loss winner` = vals[["Check loss"]],
      `Grid-CRPS winner` = vals[["Grid CRPS"]],
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })
  app_bind_rows_fill(rows)
}

app_joint_qdesn_phase126_protocol_table <- function(src) {
  n_scenarios <- length(unique(src$scope$scenario_id))
  n_models <- length(unique(src$scope$source_model_id))
  tau_grid <- unique(src$case$tau_grid %||% NA_character_)
  tau_grid <- tau_grid[!is.na(tau_grid)]
  data.frame(
    Item = c(
      "Evidence layer",
      "Synthetic scenarios",
      "Model rows",
      "Quantile grid",
      "Fit window",
      "Forecast window",
      "Prediction contract",
      "Diagnostic policy"
    ),
    Value = c(
      "VB/VB-LD screening and calibration followed by VB-initialized MCMC confirmation.",
      sprintf("%d mechanisms: three bridge cases and five stress cases with known conditional quantile paths.", n_scenarios),
      sprintf("%d readout-likelihood combinations: Joint QDESN RHS, Independent QDESN RHS, Joint exQDESN RHS, and Independent exQDESN RHS.", n_models),
      if (length(tau_grid)) gsub(",", ", ", tau_grid[[1L]], fixed = TRUE) else "0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95",
      sprintf("%s observations after DESN washout.", unique(src$case$n_train)[[1L]] %||% 500),
      "No-refit held-out forecast scoring over the common validation origin grid inherited from the frozen validation fixtures.",
      "Scores validate posterior quantile grids/readout paths, not a scalar posterior predictive density.",
      "Reported scores use monotone contract quantile grids; raw adjacent-level crossings are retained as pre-contract diagnostics."
    ),
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase126_readiness <- function(src, asset_manifest) {
  source_gate <- app_joint_qdesn_phase126_source_gate(src)
  model <- src$model
  case <- src$case
  raw_total <- sum(case$mcmc_forecast_raw_crossing_pairs, na.rm = TRUE)
  contract_total <- sum(case$mcmc_forecast_contract_crossing_pairs, na.rm = TRUE)
  data.frame(
    overall_gate = ifelse(identical(source_gate, "pass") && contract_total == 0L, "review", "fail"),
    hard_implementation_gate = source_gate,
    balanced_cells = nrow(src$scope),
    n_scenarios = length(unique(src$scope$scenario_id)),
    n_model_rows = nrow(model),
    n_case_rows = nrow(case),
    n_pass_cases = sum(case$gate_status == "pass", na.rm = TRUE),
    n_review_cases = sum(case$gate_status == "review", na.rm = TRUE),
    n_fail_cases = sum(case$gate_status == "fail", na.rm = TRUE),
    mcmc_forecast_raw_crossing_pairs = raw_total,
    mcmc_forecast_contract_crossing_pairs = contract_total,
    primary_joint_qdesn_raw_crossings = sum(model$mcmc_forecast_raw_crossing_pairs[model$model_label == "Joint QDESN RHS"], na.rm = TRUE),
    independent_qdesn_raw_crossings = sum(model$mcmc_forecast_raw_crossing_pairs[model$model_label == "Independent QDESN RHS"], na.rm = TRUE),
    joint_exqdesn_raw_crossings = sum(model$mcmc_forecast_raw_crossing_pairs[model$model_label == "Joint exQDESN RHS"], na.rm = TRUE),
    independent_exqdesn_raw_crossings = sum(model$mcmc_forecast_raw_crossing_pairs[model$model_label == "Independent exQDESN RHS"], na.rm = TRUE),
    n_article_assets = nrow(asset_manifest),
    recommended_article_message = "Use balanced MCMC confirmation as article-facing evidence; keep raw crossings as diagnostics and contract crossings as scored-grid behavior.",
    stringsAsFactors = FALSE
  )
}

app_joint_qdesn_phase126_readme <- function(run_config, readiness) {
  c(
    "# Joint QDESN Phase 126 Article Assets",
    "",
    "This artifact rebuilds article-facing joint QDESN validation assets from the frozen Phase 125 balanced MCMC audit.",
    "",
    "No model fitting, MCMC sampling, fixture generation, or validation scoring is performed in Phase 126.",
    "",
    sprintf("- Output directory: `%s`", run_config$output_dir[[1L]]),
    sprintf("- Phase 125 source: `%s`", run_config$phase125_dir[[1L]]),
    sprintf("- Balanced cells: `%s`", readiness$balanced_cells[[1L]]),
    sprintf("- Scenarios: `%s`", readiness$n_scenarios[[1L]]),
    sprintf("- Model rows: `%s`", readiness$n_model_rows[[1L]]),
    sprintf("- Hard implementation gate: `%s`", readiness$hard_implementation_gate[[1L]]),
    sprintf("- Overall gate: `%s`", readiness$overall_gate[[1L]]),
    "",
    "Interpretation:",
    "",
    "- VB/VB-LD is the screening, calibration, and initialization layer.",
    "- MCMC is the article-facing confirmation layer for the balanced four-model grid.",
    "- Metrics are quantile-grid/readout scores, not scalar posterior predictive-density scores.",
    "- Contract quantiles are monotone and used for scoring.",
    "- Raw crossings are pre-contract diagnostics."
  )
}

app_joint_qdesn_run_phase126_article_assets <- function(
  phase125_dir = app_joint_qdesn_default_phase125_balanced_mcmc_audit_dir(),
  tables_dir = app_path("tables"),
  out_dir = app_joint_qdesn_default_phase126_article_assets_dir()
) {
  phase125_dir <- normalizePath(phase125_dir, winslash = "/", mustWork = TRUE)
  tables_dir <- normalizePath(tables_dir, winslash = "/", mustWork = TRUE)
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  app_ensure_dir(out_dir)

  src <- app_joint_qdesn_phase126_load_phase125(phase125_dir)
  if (!identical(app_joint_qdesn_phase126_source_gate(src), "pass")) {
    stop("Phase126 source verification failed; refusing to build article assets.", call. = FALSE)
  }

  protocol <- app_joint_qdesn_phase126_protocol_table(src)
  model_table <- app_joint_qdesn_phase126_make_model_table(src$model)
  scenario_table <- app_joint_qdesn_phase126_make_scenario_table(src$case, bold_winners = FALSE)
  scenario_latex_table <- app_joint_qdesn_phase126_make_scenario_table(src$case, bold_winners = TRUE)
  gate_table <- app_joint_qdesn_phase126_make_gate_table(src$gate)
  winner_table <- app_joint_qdesn_phase126_make_winner_table(src$winners)

  table_paths <- c(
    protocol_csv = app_joint_qdesn_phase126_write_csv(protocol, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_protocol.csv")),
    protocol_tex = app_joint_qdesn_phase126_write_latex_table(
      protocol,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_protocol.tex"),
      "Balanced joint multi-quantile MCMC validation protocol. The table records the evidence layer, scenario scope, predictive contract, and diagnostic policy used for the article-facing summaries.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-protocol",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.24\\textwidth}>{\\raggedright\\arraybackslash}p{0.66\\textwidth}@{}",
      size = "\\small"
    ),
    model_csv = app_joint_qdesn_phase126_write_csv(src$model, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_model_summary.csv")),
    model_tex = app_joint_qdesn_phase126_write_latex_table(
      model_table,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_model_summary.tex"),
      "Balanced MCMC confirmation summary for the joint multi-quantile validation study. Each row averages over the same eight synthetic scenarios. QDESN denotes the AL working likelihood, exQDESN denotes the exAL working likelihood, Joint and Independent indicate the readout structure, and RHS denotes the regularized horseshoe prior. Fit and forecast MAE compare posterior quantile grids with oracle conditional quantiles; check loss and grid CRPS score the reported monotone quantile grid. Raw crossings are pre-contract diagnostics, whereas contract crossings are measured after the declared monotone rearrangement used for scoring.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-model-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.22\\textwidth}rrrrrrrrl@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    scenario_csv = app_joint_qdesn_phase126_write_csv(src$case, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_scenario_summary.csv")),
    scenario_tex = app_joint_qdesn_phase126_write_latex_table(
      scenario_latex_table,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_scenario_summary.tex"),
      "Scenario-level balanced MCMC forecast recovery. Entries report forecast MAE with fit-window MAE in parentheses; boldface marks the lowest forecast MAE within each scenario. The table is a mechanism-specific diagnostic, not a uniform global ranking.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-scenario-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.26\\textwidth}rrrr@{}",
      size = "\\scriptsize",
      resize = TRUE,
      raw_latex_cols = c("Joint QDESN", "Independent QDESN", "Joint exQDESN", "Independent exQDESN")
    ),
    gate_csv = app_joint_qdesn_phase126_write_csv(src$gate, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_gate_summary.csv")),
    gate_tex = app_joint_qdesn_phase126_write_latex_table(
      gate_table,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_gate_summary.tex"),
      "Validation gates for the Phase 125 balanced MCMC evidence packet used to build the article-facing joint QDESN tables.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-gate-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.24\\textwidth}l>{\\raggedright\\arraybackslash}p{0.58\\textwidth}@{}",
      size = "\\scriptsize",
      resize = TRUE
    ),
    winner_csv = app_joint_qdesn_phase126_write_csv(src$winners, file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_winner_summary.csv")),
    winner_tex = app_joint_qdesn_phase126_write_latex_table(
      winner_table,
      file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_winner_summary.tex"),
      "Per-scenario metric winners in the balanced MCMC confirmation grid. The winner can differ by metric, so this table is intended for diagnostic interpretation rather than a single-model ranking.",
      "tab:joint-qdesn-article-validation-mcmc-balanced-winner-summary",
      align = "@{}>{\\raggedright\\arraybackslash}p{0.21\\textwidth}>{\\raggedright\\arraybackslash}p{0.17\\textwidth}>{\\raggedright\\arraybackslash}p{0.17\\textwidth}>{\\raggedright\\arraybackslash}p{0.17\\textwidth}>{\\raggedright\\arraybackslash}p{0.17\\textwidth}@{}",
      size = "\\scriptsize",
      resize = TRUE
    )
  )

  table_paths[["main_wrapper"]] <- app_joint_qdesn_phase126_write_wrapper(
    table_paths[c("model_tex")],
    file.path(tables_dir, "joint_qdesn_article_validation_tables.tex"),
    "Compact balanced MCMC article table."
  )
  table_paths[["provenance_wrapper"]] <- app_joint_qdesn_phase126_write_wrapper(
    table_paths[c("protocol_tex", "scenario_tex", "gate_tex", "winner_tex")],
    file.path(tables_dir, "joint_qdesn_article_validation_provenance_tables.tex"),
    "Balanced MCMC protocol and provenance tables."
  )

  asset_paths <- table_paths
  asset_manifest <- data.frame(
    label = names(asset_paths),
    artifact_type = ifelse(grepl("\\.tex$", asset_paths), "latex_table", "csv_table"),
    path = vapply(asset_paths, app_prefer_repo_relative_path, character(1L)),
    size_bytes = as.numeric(file.info(asset_paths)$size),
    sha256 = vapply(asset_paths, app_sha256_file, character(1L)),
    source_phase125_dir = app_prefer_repo_relative_path(phase125_dir),
    source_validation_contract = "quantile_grid_readout_fit_and_no_refit_forecast",
    stringsAsFactors = FALSE
  )
  table_paths[["asset_manifest"]] <- app_joint_qdesn_phase126_write_csv(
    asset_manifest,
    file.path(tables_dir, "joint_qdesn_article_validation_asset_manifest.csv")
  )

  readiness <- app_joint_qdesn_phase126_readiness(src, asset_manifest)
  run_config <- data.frame(
    run_id = "joint_qdesn_phase126_article_assets",
    phase125_dir = phase125_dir,
    tables_dir = tables_dir,
    output_dir = out_dir,
    n_article_assets = nrow(asset_manifest),
    n_scenarios = readiness$n_scenarios[[1L]],
    n_case_rows = readiness$n_case_rows[[1L]],
    n_model_rows = readiness$n_model_rows[[1L]],
    hard_implementation_gate = readiness$hard_implementation_gate[[1L]],
    overall_gate = readiness$overall_gate[[1L]],
    validation_contract = "quantile_grid_readout_fit_and_no_refit_forecast",
    scalar_predictive_density_claim = FALSE,
    created_at = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
    stringsAsFactors = FALSE
  )

  readme_path <- file.path(out_dir, "README.md")
  writeLines(app_joint_qdesn_phase126_readme(run_config, readiness), readme_path, useBytes = TRUE)

  cache_paths <- c(
    run_config = app_joint_qdesn_phase126_write_csv(run_config, file.path(out_dir, "run_config.csv")),
    phase125_artifact_manifest_verification = app_joint_qdesn_phase126_write_csv(src$artifact_manifest_verification, file.path(out_dir, "phase125_artifact_manifest_verification.csv")),
    source_artifact_manifest_verification = app_joint_qdesn_phase126_write_csv(src$source_artifact_manifest_verification, file.path(out_dir, "source_artifact_manifest_verification.csv")),
    source_vb_freeze_manifest_verification = app_joint_qdesn_phase126_write_csv(src$source_vb_freeze_manifest_verification, file.path(out_dir, "source_vb_freeze_manifest_verification.csv")),
    fixture_source_manifest_verification = app_joint_qdesn_phase126_write_csv(src$fixture_source_manifest_verification, file.path(out_dir, "fixture_source_manifest_verification.csv")),
    model_article_table = app_joint_qdesn_phase126_write_csv(model_table, file.path(out_dir, "mcmc_balanced_model_article_table.csv")),
    scenario_article_table = app_joint_qdesn_phase126_write_csv(scenario_table, file.path(out_dir, "mcmc_balanced_scenario_article_table.csv")),
    winner_article_table = app_joint_qdesn_phase126_write_csv(winner_table, file.path(out_dir, "mcmc_balanced_winner_article_table.csv")),
    gate_article_table = app_joint_qdesn_phase126_write_csv(gate_table, file.path(out_dir, "mcmc_balanced_gate_article_table.csv")),
    protocol_table = app_joint_qdesn_phase126_write_csv(protocol, file.path(out_dir, "mcmc_balanced_protocol_table.csv")),
    article_asset_manifest = app_joint_qdesn_phase126_write_csv(asset_manifest, file.path(out_dir, "article_asset_manifest.csv")),
    readiness = app_joint_qdesn_phase126_write_csv(readiness, file.path(out_dir, "article_asset_readiness.csv")),
    provenance = app_joint_qdesn_phase126_write_csv(app_joint_qvp_provenance_rows(), file.path(out_dir, "provenance.csv")),
    readme = normalizePath(readme_path, winslash = "/", mustWork = TRUE)
  )
  manifest_info <- app_joint_qdesn_write_manifest(cache_paths, out_dir)

  list(
    out_dir = normalizePath(out_dir, winslash = "/", mustWork = TRUE),
    tables_dir = tables_dir,
    paths = c(cache_paths, article_artifacts = table_paths, artifact_manifest = manifest_info$manifest_path),
    phase125 = src,
    run_config = run_config,
    readiness = readiness,
    asset_manifest = asset_manifest,
    artifact_manifest = manifest_info$manifest,
    artifact_manifest_path = manifest_info$manifest_path,
    model_table = model_table,
    scenario_table = scenario_table,
    gate_table = gate_table,
    winner_table = winner_table
  )
}

app_joint_qdesn_phase126_text_contains <- function(path, pattern, fixed = TRUE) {
  if (!file.exists(path)) return(FALSE)
  txt <- paste(readLines(path, warn = FALSE), collapse = "\n")
  grepl(pattern, txt, fixed = fixed)
}

app_joint_qdesn_run_phase126_article_asset_audit <- function(
  phase126_dir = app_joint_qdesn_default_phase126_article_assets_dir(),
  tables_dir = app_path("tables"),
  main_tex = app_path("main.tex"),
  supplement_tex = app_path("qdesn-supplement.tex"),
  out_dir = file.path(phase126_dir, "phase126_readiness_audit")
) {
  phase126_dir <- normalizePath(phase126_dir, winslash = "/", mustWork = TRUE)
  tables_dir <- normalizePath(tables_dir, winslash = "/", mustWork = TRUE)
  main_tex <- normalizePath(main_tex, winslash = "/", mustWork = TRUE)
  supplement_tex <- normalizePath(supplement_tex, winslash = "/", mustWork = TRUE)
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  app_ensure_dir(out_dir)

  artifact_verification <- app_joint_qdesn_phase126_verify_manifest(phase126_dir, "artifact_manifest.csv", "phase126_artifact")
  article_asset_manifest_path <- file.path(phase126_dir, "article_asset_manifest.csv")
  article_asset_verification <- app_joint_qdesn_phase126_verify_article_asset_manifest(article_asset_manifest_path)
  readiness <- app_read_csv(file.path(phase126_dir, "article_asset_readiness.csv"))
  asset_manifest <- app_read_csv(article_asset_manifest_path)

  manuscript_checks <- data.frame(
    check = c(
      "main_uses_balanced_mcmc_table",
      "main_does_not_use_stale_primary_mcmc_table",
      "main_mentions_eight_scenarios",
      "main_mentions_32_rows",
      "main_mentions_quantile_grid_contract",
      "main_avoids_scalar_density_claim",
      "main_avoids_nine_mechanism_claim",
      "main_avoids_zero_raw_crossing_claim",
      "supplement_uses_balanced_provenance_wrapper"
    ),
    status = c(
      ifelse(app_joint_qdesn_phase126_text_contains(main_tex, "joint_qdesn_article_validation_mcmc_balanced_model_summary.tex"), "pass", "fail"),
      ifelse(!app_joint_qdesn_phase126_text_contains(main_tex, "joint_qdesn_article_validation_mcmc_main_summary.tex"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase126_text_contains(main_tex, "eight synthetic") || app_joint_qdesn_phase126_text_contains(main_tex, "eight-scenario"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase126_text_contains(main_tex, "32") && app_joint_qdesn_phase126_text_contains(main_tex, "scenario--model"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase126_text_contains(main_tex, "quantile-grid") || app_joint_qdesn_phase126_text_contains(main_tex, "quantile grid"), "pass", "fail"),
      ifelse(!app_joint_qdesn_phase126_text_contains(main_tex, "scalar posterior predictive density validation"), "pass", "fail"),
      ifelse(!app_joint_qdesn_phase126_text_contains(main_tex, "nine synthetic data-generating mechanisms") && !app_joint_qdesn_phase126_text_contains(main_tex, "all nine mechanisms"), "pass", "fail"),
      ifelse(!app_joint_qdesn_phase126_text_contains(main_tex, "raw adjacent-level crossing count is zero"), "pass", "fail"),
      ifelse(app_joint_qdesn_phase126_text_contains(supplement_tex, "joint_qdesn_article_validation_provenance_tables.tex"), "pass", "fail")
    ),
    detail = c(
      "Main text should input the Phase126 balanced MCMC model table.",
      "Main text should not input the older primary-row MCMC table.",
      "Main text should describe the Phase125/126 eight-scenario balanced grid.",
      "Main text should state the 32 scenario-model rows.",
      "Main text should keep claims scoped to the quantile-grid predictive contract.",
      "Main text should not claim scalar posterior predictive density validation.",
      "Main text should not retain old nine-mechanism language.",
      "Main text should not claim all raw crossings are zero in the balanced grid.",
      "Supplement should include the balanced protocol/provenance wrapper."
    ),
    stringsAsFactors = FALSE
  )

  asset_checks <- data.frame(
    check = c(
      "phase126_manifest_hashes",
      "article_asset_manifest_hashes",
      "article_assets_source_phase125",
      "balanced_model_table_present",
      "balanced_model_table_in_manifest",
      "hard_implementation_gate",
      "contract_crossings_zero",
      "raw_crossings_reviewed"
    ),
    status = c(
      ifelse(all(artifact_verification$status == "pass"), "pass", "fail"),
      ifelse(all(article_asset_verification$status == "pass"), "pass", "fail"),
      ifelse(all(grepl("phase125", asset_manifest$source_phase125_dir)), "pass", "fail"),
      ifelse(file.exists(file.path(tables_dir, "joint_qdesn_article_validation_mcmc_balanced_model_summary.tex")), "pass", "fail"),
      ifelse(any(asset_manifest$label == "model_tex"), "pass", "fail"),
      ifelse(identical(as.character(readiness$hard_implementation_gate[[1L]]), "pass"), "pass", "fail"),
      ifelse(as.numeric(readiness$mcmc_forecast_contract_crossing_pairs[[1L]]) == 0, "pass", "fail"),
      ifelse(as.numeric(readiness$mcmc_forecast_raw_crossing_pairs[[1L]]) > 0, "review", "pass")
    ),
    detail = c(
      sprintf("%d/%d Phase126 manifest rows pass.", sum(artifact_verification$status == "pass"), nrow(artifact_verification)),
      sprintf("%d/%d article asset rows pass.", sum(article_asset_verification$status == "pass"), nrow(article_asset_verification)),
      "Generated article asset manifest records Phase125 as the source evidence packet.",
      "Balanced model table exists in the requested tables directory.",
      "Balanced model table is present in the Phase126 article asset manifest.",
      sprintf("hard_implementation_gate=%s", readiness$hard_implementation_gate[[1L]]),
      sprintf("mcmc_forecast_contract_crossing_pairs=%s", readiness$mcmc_forecast_contract_crossing_pairs[[1L]]),
      sprintf("mcmc_forecast_raw_crossing_pairs=%s", readiness$mcmc_forecast_raw_crossing_pairs[[1L]])
    ),
    stringsAsFactors = FALSE
  )

  all_status <- c(manuscript_checks$status, asset_checks$status)
  audit_status <- if (any(all_status == "fail")) "fail" else if (any(all_status == "review")) "review" else "pass"
  audit_summary <- data.frame(
    audit_status = audit_status,
    phase126_dir = phase126_dir,
    n_asset_checks = nrow(asset_checks),
    n_manuscript_checks = nrow(manuscript_checks),
    n_fail = sum(all_status == "fail"),
    n_review = sum(all_status == "review"),
    n_pass = sum(all_status == "pass"),
    next_action = if (identical(audit_status, "fail")) {
      "Fix failed asset or manuscript checks before using Phase126 in the article."
    } else {
      "Use Phase126 assets with explicit review language for raw pre-contract crossings."
    },
    stringsAsFactors = FALSE
  )

  readme_path <- file.path(out_dir, "README.md")
  writeLines(c(
    "# Joint QDESN Phase 126 Article-Asset Audit",
    "",
    sprintf("- Audit status: `%s`", audit_status),
    sprintf("- Phase126 directory: `%s`", phase126_dir),
    sprintf("- Failed checks: `%s`", audit_summary$n_fail[[1L]]),
    sprintf("- Review checks: `%s`", audit_summary$n_review[[1L]]),
    "",
    "This audit verifies hashes, source provenance, balanced-table presence, and manuscript wording against the Phase125 balanced MCMC evidence packet."
  ), readme_path, useBytes = TRUE)

  paths <- c(
    audit_summary = app_joint_qdesn_phase126_write_csv(audit_summary, file.path(out_dir, "phase126_article_asset_audit_summary.csv")),
    asset_checks = app_joint_qdesn_phase126_write_csv(asset_checks, file.path(out_dir, "phase126_asset_checks.csv")),
    manuscript_checks = app_joint_qdesn_phase126_write_csv(manuscript_checks, file.path(out_dir, "phase126_manuscript_checks.csv")),
    artifact_manifest_verification = app_joint_qdesn_phase126_write_csv(artifact_verification, file.path(out_dir, "phase126_artifact_manifest_verification.csv")),
    article_asset_manifest_verification = app_joint_qdesn_phase126_write_csv(article_asset_verification, file.path(out_dir, "phase126_article_asset_manifest_verification.csv")),
    readiness = app_joint_qdesn_phase126_write_csv(readiness, file.path(out_dir, "phase126_article_asset_readiness.csv")),
    provenance = app_joint_qdesn_phase126_write_csv(app_joint_qvp_provenance_rows(), file.path(out_dir, "provenance.csv")),
    readme = normalizePath(readme_path, winslash = "/", mustWork = TRUE)
  )
  manifest_info <- app_joint_qdesn_write_manifest(paths, out_dir)

  list(
    out_dir = normalizePath(out_dir, winslash = "/", mustWork = TRUE),
    audit_summary = audit_summary,
    asset_checks = asset_checks,
    manuscript_checks = manuscript_checks,
    artifact_manifest_verification = artifact_verification,
    article_asset_manifest_verification = article_asset_verification,
    paths = c(paths, artifact_manifest = manifest_info$manifest_path),
    artifact_manifest = manifest_info$manifest
  )
}
