# Manuscript-output generation for the GloFAS application.

app_manuscript_latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

app_manuscript_model_label <- function(model_id) {
  id <- tolower(as.character(model_id %||% ""))
  if (grepl("qdesn", id)) return("Q--DESN calibration")
  if (grepl("raw_glofas", id)) return("Raw GloFAS")
  as.character(model_id)
}

app_make_score_table_tex <- function(score_summary, path) {
  app_ensure_dir(dirname(path))
  lines <- c(
    "% Generated by application/R/make_manuscript_outputs.R",
    "\\begin{tabular}{lrrrr}",
    "\\toprule",
    "Model & Check loss & Interval score & Coverage & CRPS \\\\",
    "\\midrule"
  )
  for (i in seq_len(nrow(score_summary))) {
    row <- score_summary[i, , drop = FALSE]
    lines <- c(lines, sprintf(
      "%s & %.4f & %.4f & %.3f & %.4f \\\\",
      app_manuscript_latex_escape(app_manuscript_model_label(row$model_id)),
      row$check_loss_mean,
      row$interval_score_mean,
      row$interval_coverage_mean,
      row$crps_quantile_grid_mean
    ))
  }
  lines <- c(lines, "\\bottomrule", "\\end{tabular}")
  writeLines(lines, path)
  invisible(path)
}

app_model_pdf_plot <- function(path, width, height, expr) {
  app_ensure_dir(dirname(path))
  grDevices::pdf(path, width = width, height = height)
  on.exit(grDevices::dev.off(), add = TRUE)
  force(expr)
  invisible(path)
}

app_prediction_quantile_plot_data <- function(predictions) {
  predictions$origin_date <- as.Date(predictions$origin_date)
  predictions$target_date <- as.Date(predictions$target_date)
  predictions$horizon <- as.integer(predictions$horizon)
  predictions$quantile_level <- as.numeric(predictions$quantile_level)
  predictions$qhat <- as.numeric(predictions$qhat)
  predictions$y_reference <- as.numeric(predictions$y_reference)
  predictions
}

app_plot_discrepancy_corrected_quantile_paths <- function(
  predictions,
  path,
  title = "Discrepancy-corrected Q-DESN quantile paths",
  value_col = "qhat"
) {
  pred <- app_prediction_quantile_plot_data(predictions)
  if (!value_col %in% names(pred)) {
    stop(sprintf("Prediction table is missing value column '%s'.", value_col), call. = FALSE)
  }
  pred$qhat_plot <- as.numeric(pred[[value_col]])
  disc <- pred[pred$model_family == "qdesn_glofas_discrepancy", , drop = FALSE]
  raw <- pred[pred$model_family == "raw_glofas", , drop = FALSE]
  if (!nrow(disc)) stop("No Q-DESN discrepancy rows are available for the quantile-path figure.", call. = FALSE)

  target_dates <- sort(unique(disc$target_date))
  y_ref <- disc[!duplicated(disc$target_date), c("target_date", "y_reference"), drop = FALSE]
  y_ref <- y_ref[order(y_ref$target_date), , drop = FALSE]
  values <- c(disc$qhat_plot, raw$qhat_plot, y_ref$y_reference)
  values <- values[is.finite(values)]
  p_levels <- sort(unique(disc$quantile_level))
  q_cols <- grDevices::hcl.colors(length(p_levels), "Dark 3")

  app_model_pdf_plot(path, 7.0, 4.5, {
    plot(
      range(target_dates),
      range(values) + c(-0.05, 0.05) * diff(range(values)),
      type = "n",
      xlab = "Target date",
      ylab = "Transformed streamflow",
      main = title
    )
    grid(col = "gray90")
    if (nrow(raw)) {
      raw_med <- raw[abs(raw$quantile_level - 0.5) < 1.0e-12, , drop = FALSE]
      if (nrow(raw_med)) {
        raw_med <- raw_med[order(raw_med$target_date), , drop = FALSE]
        lines(raw_med$target_date, raw_med$qhat_plot, col = "#8a8a8a", lwd = 1.7, lty = 3)
      }
    }
    for (j in seq_along(p_levels)) {
      block <- disc[abs(disc$quantile_level - p_levels[[j]]) < 1.0e-12, , drop = FALSE]
      block <- block[order(block$target_date), , drop = FALSE]
      lines(block$target_date, block$qhat_plot, col = q_cols[[j]], lwd = if (abs(p_levels[[j]] - 0.5) < 1.0e-12) 2.2 else 1.6)
    }
    lines(y_ref$target_date, y_ref$y_reference, col = "#111111", lwd = 2.0)
    points(y_ref$target_date, y_ref$y_reference, col = "#111111", pch = 19, cex = 0.45)
    legend(
      "topleft",
      legend = c(paste0("Q-DESN p=", format(p_levels, trim = TRUE)), "Raw GloFAS median", "Observed reference"),
      col = c(q_cols, "#8a8a8a", "#111111"),
      lty = c(rep(1, length(p_levels)), 3, 1),
      lwd = c(rep(1.7, length(p_levels)), 1.7, 2.0),
      bty = "n",
      cex = 0.78
    )
  })
}

app_draw_horizon_summary <- function(draws, value_col) {
  draws$horizon <- as.integer(draws$horizon)
  draws$quantile_level <- as.numeric(draws$quantile_level)
  split_key <- interaction(draws$horizon, draws$quantile_level, drop = TRUE)
  rows <- lapply(split(draws, split_key), function(block) {
    x <- as.numeric(block[[value_col]])
    data.frame(
      horizon = unique(block$horizon),
      quantile_level = unique(block$quantile_level),
      lo = as.numeric(stats::quantile(x, 0.10, na.rm = TRUE, names = FALSE)),
      mid = as.numeric(stats::quantile(x, 0.50, na.rm = TRUE, names = FALSE)),
      hi = as.numeric(stats::quantile(x, 0.90, na.rm = TRUE, names = FALSE)),
      stringsAsFactors = FALSE
    )
  })
  out <- do.call(rbind, rows)
  out[order(out$quantile_level, out$horizon), , drop = FALSE]
}

app_plot_discrepancy_draws_by_horizon <- function(draws, path, title = "Discrepancy posterior draws by horizon") {
  if (!nrow(draws)) stop("No posterior draw rows are available for the discrepancy figure.", call. = FALSE)
  summary <- app_draw_horizon_summary(draws, "d_g_draw")
  values <- c(summary$lo, summary$mid, summary$hi)
  values <- values[is.finite(values)]
  p_levels <- sort(unique(summary$quantile_level))
  q_cols <- grDevices::hcl.colors(length(p_levels), "Dark 3")

  app_model_pdf_plot(path, 7.0, 4.5, {
    plot(
      range(summary$horizon),
      range(values) + c(-0.05, 0.05) * diff(range(values)),
      type = "n",
      xlab = "Forecast horizon",
      ylab = "GloFAS discrepancy draw",
      main = title
    )
    grid(col = "gray90")
    abline(h = 0, lty = 2, col = "gray50")
    for (j in seq_along(p_levels)) {
      block <- summary[abs(summary$quantile_level - p_levels[[j]]) < 1.0e-12, , drop = FALSE]
      block <- block[order(block$horizon), , drop = FALSE]
      polygon(
        c(block$horizon, rev(block$horizon)),
        c(block$lo, rev(block$hi)),
        border = NA,
        col = grDevices::adjustcolor(q_cols[[j]], alpha.f = 0.18)
      )
      lines(block$horizon, block$mid, col = q_cols[[j]], lwd = 1.8)
    }
    legend(
      "topright",
      legend = paste0("p=", format(p_levels, trim = TRUE)),
      col = q_cols,
      lty = 1,
      lwd = 1.8,
      bty = "n",
      cex = 0.82
    )
  })
}

app_make_model_diagnostic_figures <- function(predictions, draws, out_dir) {
  app_ensure_dir(out_dir)
  out <- c(
    discrepancy_corrected_quantile_paths = file.path(out_dir, "glofas_qdesn_discrepancy_corrected_quantile_paths.pdf")
  )
  main_value_col <- if ("qhat_monotone" %in% names(predictions)) "qhat_monotone" else "qhat"
  main_title <- if (identical(main_value_col, "qhat_monotone")) {
    "Discrepancy-corrected Q-DESN quantile paths after monotone synthesis"
  } else {
    "Discrepancy-corrected Q-DESN quantile paths"
  }
  app_plot_discrepancy_corrected_quantile_paths(
    predictions,
    out[["discrepancy_corrected_quantile_paths"]],
    title = main_title,
    value_col = main_value_col
  )

  if ("qhat_monotone" %in% names(predictions)) {
    out <- c(
      out,
      discrepancy_corrected_quantile_paths_independent = file.path(out_dir, "glofas_qdesn_discrepancy_corrected_quantile_paths_independent.pdf"),
      discrepancy_corrected_quantile_paths_monotone = file.path(out_dir, "glofas_qdesn_discrepancy_corrected_quantile_paths_monotone.pdf")
    )
    app_plot_discrepancy_corrected_quantile_paths(
      predictions,
      out[["discrepancy_corrected_quantile_paths_independent"]],
      title = "Independent Q-DESN quantile paths before monotone synthesis",
      value_col = "qhat"
    )
    app_plot_discrepancy_corrected_quantile_paths(
      predictions,
      out[["discrepancy_corrected_quantile_paths_monotone"]],
      title = "Q-DESN quantile paths after monotone synthesis",
      value_col = "qhat_monotone"
    )
  }

  if (!is.null(draws) && nrow(draws)) {
    out <- c(
      out,
      discrepancy_draws_by_horizon = file.path(out_dir, "glofas_qdesn_discrepancy_draws_by_horizon.pdf")
    )
    app_plot_discrepancy_draws_by_horizon(draws, out[["discrepancy_draws_by_horizon"]])
  }
  out
}

app_write_output_provenance <- function(outputs, run_dirs, cfg, path) {
  out <- data.frame(
    output_path = unname(outputs),
    output_role = names(outputs),
    run_id = basename(run_dirs$run_dir),
    config_path = cfg$.__config_path__,
    git_sha = app_git_sha(short = FALSE),
    created_at = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
    stringsAsFactors = FALSE
  )
  app_write_csv(out, path)
  invisible(out)
}
