#!/usr/bin/env Rscript

options(stringsAsFactors = FALSE)

`%||%` <- function(lhs, rhs) {
  if (is.null(lhs) || !length(lhs) || all(is.na(lhs))) rhs else lhs
}

script_path <- {
  file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(file_arg)) {
    normalizePath(sub("^--file=", "", file_arg[[1L]]), winslash = "/", mustWork = TRUE)
  } else {
    normalizePath("scripts/build_qdesn_mcmc_current_best_validation_tables.R", winslash = "/", mustWork = TRUE)
  }
}
repo_root <- normalizePath(file.path(dirname(script_path), ".."), winslash = "/", mustWork = TRUE)

args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(flag, default) {
  idx <- which(args == flag)
  if (!length(idx) || idx[[1L]] >= length(args)) return(default)
  args[[idx[[1L]] + 1L]]
}

source_dir <- get_arg(
  "--source-dir",
  "/data/jaguir26/local/src/exdqlm__wt__shared_fitforecast_v2_1p0p0/validation/fitforecast_v2/promotions/qdesn_dqlm_500obs_mcmc_current_best_20260723"
)
source_csv <- get_arg(
  "--source-csv",
  file.path(source_dir, "qdesn_dqlm_500obs_mcmc_current_best_clean_20260723.csv")
)
source_manifest <- get_arg(
  "--source-manifest",
  file.path(source_dir, "qdesn_dqlm_500obs_mcmc_current_best_manifest_20260723.json")
)

out_dir <- file.path(repo_root, "tables")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

stop_if_missing <- function(path, label) {
  if (!file.exists(path)) stop(sprintf("Missing %s: %s", label, path), call. = FALSE)
}
stop_if_missing(source_csv, "current-best clean evidence table")
stop_if_missing(source_manifest, "current-best manifest")

clean <- read.csv(source_csv, check.names = FALSE, stringsAsFactors = FALSE)
required <- c(
  "model_variant", "family", "tau", "comparison_eligible", "status",
  "signoff_grade", "fit_qtrue_rmse", "forecast_qtrue_mae_H1000",
  "forecast_check_loss_H1000", "source_key", "source_promotion_id",
  "source_table_sha256", "source_registry_hash_value"
)
missing <- setdiff(required, names(clean))
if (length(missing)) {
  stop(sprintf("Current-best clean table is missing required columns: %s", paste(missing, collapse = ", ")), call. = FALSE)
}

clean <- clean[clean$comparison_eligible == "TRUE" & clean$status %in% c("SUCCESS", "done"), , drop = FALSE]
if (!nrow(clean)) stop("No clean comparison-eligible rows are available.", call. = FALSE)
if (length(unique(clean$source_registry_hash_value)) != 1L) {
  stop("Current-best rows do not share one source registry hash.", call. = FALSE)
}

families <- c(normal = "Gaussian", laplace = "Laplace", gausmix = "Gaussian-mixture")
family_order <- names(families)
taus <- c(0.05, 0.25, 0.50)
models <- c(
  dqlm_c13_mcmc = "DQLM",
  exdqlm_c13_mcmc = "exDQLM",
  qdesn_al_rhs_ns = "Q-DESN AL--RHS",
  qdesn_exal_rhs_ns = "Q-DESN exAL--RHS"
)

num <- function(x) suppressWarnings(as.numeric(x))
fmt <- function(x) {
  x <- num(x)
  if (!is.finite(x)) return("--")
  if (abs(x) >= 10) formatC(x, format = "f", digits = 2) else formatC(x, format = "f", digits = 3)
}
latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x
}
metric_cols <- c(
  fit = "fit_qtrue_rmse",
  forecast = "forecast_qtrue_mae_H1000",
  check = "forecast_check_loss_H1000"
)
metric_headers <- c("Fit RMSE", "Forecast MAE", "Forecast check")

row_for <- function(family, tau, model_variant) {
  hit <- clean[
    clean$family == family &
      abs(num(clean$tau) - tau) < 1e-9 &
      clean$model_variant == model_variant,
    ,
    drop = FALSE
  ]
  if (nrow(hit) > 1L) {
    hit <- hit[order(num(hit$decision_objective)), , drop = FALSE]
  }
  if (nrow(hit)) hit[1L, , drop = FALSE] else NULL
}

best_values <- function(family, tau, metric_col) {
  vals <- vapply(names(models), function(model_variant) {
    row <- row_for(family, tau, model_variant)
    if (is.null(row)) NA_real_ else num(row[[metric_col]][[1L]])
  }, numeric(1L))
  if (all(!is.finite(vals))) return(NA_real_)
  min(vals, na.rm = TRUE)
}

format_metric <- function(value, best) {
  value <- num(value)
  out <- fmt(value)
  if (is.finite(value) && is.finite(best) && abs(value - best) < 1e-10) {
    return(paste0("\\textbf{", out, "}"))
  }
  out
}

model_label_for_family <- function(family, model_variant) {
  rows <- clean[clean$family == family & clean$model_variant == model_variant, , drop = FALSE]
  label <- models[[model_variant]]
  if (nrow(rows) && any(rows$signoff_grade == "WARN")) {
    label <- paste0(label, "$^{\\dagger}$")
  }
  label
}

write_family_table <- function(family) {
  path <- file.path(out_dir, sprintf("qdesn_validation_tt500_final_mcmc_%s.tex", family))
  lines <- c(
    "% Generated by scripts/build_qdesn_mcmc_current_best_validation_tables.R.",
    sprintf("%% Source: %s", normalizePath(source_csv, winslash = "/", mustWork = TRUE)),
    "\\begin{table}[!htbp]",
    "\\centering",
    "\\scriptsize",
    "\\setlength{\\tabcolsep}{3.4pt}",
    "\\resizebox{\\textwidth}{!}{%",
    "\\begin{tabular}{@{}lrrrrrrrrr@{}}",
    "\\toprule",
    "Model & \\multicolumn{3}{c}{$p=0.05$} & \\multicolumn{3}{c}{$p=0.25$} & \\multicolumn{3}{c}{$p=0.50$} \\\\",
    "\\cmidrule(lr){2-4} \\cmidrule(lr){5-7} \\cmidrule(lr){8-10}",
    paste(" &", paste(rep(metric_headers, length(taus)), collapse = " & "), "\\\\"),
    "\\midrule"
  )
  for (model_variant in names(models)) {
    cells <- character(0)
    for (tau in taus) {
      row <- row_for(family, tau, model_variant)
      for (metric_col in metric_cols) {
        if (is.null(row)) {
          cells <- c(cells, "--")
        } else {
          cells <- c(cells, format_metric(row[[metric_col]][[1L]], best_values(family, tau, metric_col)))
        }
      }
    }
    lines <- c(lines, paste0(model_label_for_family(family, model_variant), " & ", paste(cells, collapse = " & "), " \\\\"))
  }
  caption <- sprintf(
    "MCMC single-quantile fit-and-forecast comparison for the %s simulation family. Forecast entries average scored rolling-origin lead-target pairs over the held-out forecast window of length 1000 using leads 1--30 with origin stride 30. Lower values are better for all displayed metrics, and boldface marks the lowest clean comparison value within each quantile level and metric. Daggered Q--DESN rows contain at least one diagnostically usable WARN row; failed-signoff rows are excluded from this table.",
    families[[family]]
  )
  lines <- c(
    lines,
    "\\bottomrule",
    "\\end{tabular}%",
    "}",
    sprintf("\\caption{%s}", caption),
    sprintf("\\label{tab:simulation-500obs-mcmc-%s}", family),
    "\\end{table}"
  )
  writeLines(lines, path, useBytes = TRUE)
  normalizePath(path, winslash = "/", mustWork = TRUE)
}

written <- vapply(family_order, write_family_table, character(1L))

wrapper <- file.path(out_dir, "qdesn_validation_tt500_final_mcmc_tables.tex")
writeLines(c(
  "% Generated by scripts/build_qdesn_mcmc_current_best_validation_tables.R.",
  "\\input{tables/qdesn_validation_tt500_final_mcmc_normal.tex}",
  "\\input{tables/qdesn_validation_tt500_final_mcmc_laplace.tex}",
  "\\input{tables/qdesn_validation_tt500_final_mcmc_gausmix.tex}"
), wrapper, useBytes = TRUE)

manifest_path <- file.path(out_dir, "qdesn_validation_tt500_mcmc_current_best_manifest.txt")
artifact_paths <- c(written, wrapper)
artifact_hashes <- tools::sha256sum(artifact_paths)
manifest_lines <- c(
  "Q-DESN/DQLM 500-observation MCMC current-best article tables",
  sprintf("generated_at: %s", Sys.time()),
  sprintf("source_csv: %s", normalizePath(source_csv, winslash = "/", mustWork = TRUE)),
  sprintf("source_manifest: %s", normalizePath(source_manifest, winslash = "/", mustWork = TRUE)),
  sprintf("source_csv_sha256: %s", tools::sha256sum(source_csv)[[1L]]),
  sprintf("source_registry_hash: %s", unique(clean$source_registry_hash_value)),
  sprintf("row_count_clean_input: %d", nrow(clean)),
  sprintf("table_normal: %s", written[["normal"]]),
  sprintf("table_laplace: %s", written[["laplace"]]),
  sprintf("table_gausmix: %s", written[["gausmix"]]),
  sprintf("wrapper: %s", normalizePath(wrapper, winslash = "/", mustWork = TRUE)),
  "artifact_sha256:",
  sprintf("  %s: %s", basename(names(artifact_hashes)), unname(artifact_hashes))
)
writeLines(manifest_lines, manifest_path, useBytes = TRUE)

cat(sprintf("wrote %d family tables\n", length(written)))
cat(sprintf("manifest: %s\n", normalizePath(manifest_path, winslash = "/", mustWork = TRUE)))
